'use strict';
const zlib = require('zlib');
const DEFAULT_TIMEOUT_MS = 20000;
const DEFAULT_MAX_BYTES = 8 * 1024 * 1024;
function envNumber(name,fallback,min,max){const v=Number(process.env[name]);return Number.isFinite(v)?Math.min(max,Math.max(min,v)):fallback;}
function normalizeDigits(v){return String(v??'').replace(/[۰-۹]/g,d=>String('۰۱۲۳۴۵۶۷۸۹'.indexOf(d))).replace(/[٠-٩]/g,d=>String('٠١٢٣٤٥٦٧٨٩'.indexOf(d)));}
function normalizeText(v){return normalizeDigits(v).replace(/[\u200c\u200f\u200e]/g,' ').replace(/[يى]/g,'ی').replace(/ك/g,'ک').replace(/ة/g,'ه').replace(/\s+/g,' ').trim();}
function normalizeMetricLabel(v){return normalizeText(v).toLowerCase().replace(/[()\[\]{}،,؛:٫٬–—-]/g,' ').replace(/\s+/g,' ').trim();}
function parseNumber(v){if(typeof v==='number'&&Number.isFinite(v))return v;const t=normalizeDigits(v).replace(/[٬،,]/g,'').replace(/\s+/g,'').replace(/[٪%]/g,'').trim();if(!t||t==='-'||t==='—')return null;const neg=/^\(.*\)$/.test(t)||t.startsWith('-');const c=t.replace(/[()]/g,'').replace(/[^0-9.+-]/g,'');if(!c||c==='-'||c==='.')return null;const n=Number(c);return Number.isFinite(n)?(neg?-Math.abs(n):n):null;}
function getAllowedHosts(){return String(process.env.CODAL_DOCUMENT_ALLOWED_HOSTS||'').split(',').map(x=>x.trim().toLowerCase()).filter(Boolean);}
function validateDocumentUrl(raw){if(!raw)return{ok:false,reason:'empty-url'};let url;try{url=new URL(raw);}catch{return{ok:false,reason:'invalid-url'};}if(url.username||url.password)return{ok:false,reason:'credentials-not-allowed'};if(url.protocol!=='https:')return{ok:false,reason:'https-required'};const allowed=getAllowedHosts();if(allowed.length&&!allowed.includes(url.hostname.toLowerCase()))return{ok:false,reason:'host-not-allowed'};return{ok:true,url};}
async function downloadDocument(raw){const validation=validateDocumentUrl(raw);if(!validation.ok)throw new Error(`CODAL document URL rejected: ${validation.reason}`);const timeoutMs=envNumber('CODAL_DOCUMENT_TIMEOUT_MS',DEFAULT_TIMEOUT_MS,3000,60000),maxBytes=envNumber('CODAL_DOCUMENT_MAX_BYTES',DEFAULT_MAX_BYTES,256*1024,32*1024*1024),controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeoutMs);try{const relayBase=String(process.env.CODAL_DOCUMENT_RELAY_URL||'').trim();let requestUrl=validation.url.toString();if(relayBase){const relayUrl=new URL(relayBase);relayUrl.searchParams.set('url',validation.url.toString());requestUrl=relayUrl.toString();}const response=await fetch(requestUrl,{method:'GET',redirect:'follow',signal:controller.signal,headers:{Accept:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.ms-excel,application/octet-stream;q=0.8,*/*;q=0.1','User-Agent':'RoniyaAnalyzer/5.2.1'}});if(!response.ok)throw new Error(`CODAL document HTTP ${response.status}`);const length=Number(response.headers.get('content-length'));if(Number.isFinite(length)&&length>maxBytes)throw new Error(`CODAL document exceeds ${maxBytes} bytes`);const chunks=[];let total=0;for await(const chunk of response.body){total+=chunk.length;if(total>maxBytes)throw new Error(`CODAL document exceeds ${maxBytes} bytes`);chunks.push(Buffer.from(chunk));}const buffer=Buffer.concat(chunks);return{buffer,contentType:String(response.headers.get('content-type')||'').toLowerCase(),finalUrl:response.url,bytes:buffer.length};}finally{clearTimeout(timer);}}
function looksLikeExcel(contentType,url){return/spreadsheet|excel|vnd\.ms-excel|officedocument\.spreadsheet/.test(contentType)||/\.(xlsx|xls)(?:$|[?#])/i.test(url);}
function findEndOfCentralDirectory(buffer){const start=Math.max(0,buffer.length-65557);for(let o=buffer.length-22;o>=start;o--)if(buffer.readUInt32LE(o)===0x06054b50)return o;throw new Error('Invalid XLSX ZIP: end of central directory not found');}
function extractZipEntries(buffer){const e=findEndOfCentralDirectory(buffer),count=buffer.readUInt16LE(e+10),size=buffer.readUInt32LE(e+12),offset=buffer.readUInt32LE(e+16),entries=new Map();let cursor=offset;const end=offset+size;for(let i=0;i<count&&cursor<end;i++){if(buffer.readUInt32LE(cursor)!==0x02014b50)throw new Error('Invalid XLSX ZIP: central directory entry not found');const method=buffer.readUInt16LE(cursor+10),cs=buffer.readUInt32LE(cursor+20),us=buffer.readUInt32LE(cursor+24),nl=buffer.readUInt16LE(cursor+28),el=buffer.readUInt16LE(cursor+30),cl=buffer.readUInt16LE(cursor+32),lo=buffer.readUInt32LE(cursor+42),name=buffer.slice(cursor+46,cursor+46+nl).toString('utf8');if(cs>32*1024*1024||us>64*1024*1024)throw new Error('XLSX entry exceeds safety limits');const lnl=buffer.readUInt16LE(lo+26),lel=buffer.readUInt16LE(lo+28),dataStart=lo+30+lnl+lel,compressed=buffer.slice(dataStart,dataStart+cs);let content;if(method===0)content=compressed;else if(method===8)content=zlib.inflateRawSync(compressed);else throw new Error(`Unsupported XLSX compression method: ${method}`);if(content.length!==us)throw new Error(`Invalid XLSX entry size for ${name}`);entries.set(name,content);cursor+=46+nl+el+cl;}return entries;}
function decodeXml(v){return String(v||'').replace(/&#(x[0-9a-f]+|[0-9]+);/gi,(_,c)=>{const n=c.toLowerCase().startsWith('x')?parseInt(c.slice(1),16):parseInt(c,10);return Number.isFinite(n)?String.fromCodePoint(n):'';}).replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&apos;/g,"'");}
function attr(tag,name){const m=String(tag||'').match(new RegExp(`${name}=["']([^"']*)["']`,'i'));return m?decodeXml(m[1]):null;}
function parseSharedStrings(xml){if(!xml)return[];return[...xml.matchAll(/<si\b[\s\S]*?<\/si>/g)].map(m=>[...m[0].matchAll(/<t\b[^>]*>([\s\S]*?)<\/t>/g)].map(x=>decodeXml(x[1])).join(''));}
function columnIndex(column){let r=0;for(const ch of String(column||'').toUpperCase()){if(ch<'A'||ch>'Z')continue;r=r*26+ch.charCodeAt(0)-64;}return Math.max(0,r-1);}
function parseWorksheet(xml,shared){const rows=[];for(const rm of String(xml||'').matchAll(/<row\b([^>]*)>([\s\S]*?)<\/row>/g)){const rn=Number(attr(rm[1],'r'))||rows.length+1,row=[];for(const cm of rm[2].matchAll(/<c\b([^>]*)>([\s\S]*?)<\/c>/g)){const a=cm[1],body=cm[2],ref=attr(a,'r')||'',idx=columnIndex(ref.replace(/[0-9]/g,'')),type=attr(a,'t'),vm=body.match(/<v\b[^>]*>([\s\S]*?)<\/v>/),im=body.match(/<is\b[\s\S]*?<t\b[^>]*>([\s\S]*?)<\/t>[\s\S]*?<\/is>/);let value=vm?decodeXml(vm[1]):null;if(type==='s'&&value!==null){const si=Number(value);value=Number.isInteger(si)?(shared[si]||''):'';}else if(type==='inlineStr')value=im?decodeXml(im[1]):'';else if(value!==null){const n=parseNumber(value);if(n!==null)value=n;}row[idx]=value;}rows[rn-1]=row;}return rows.filter(Array.isArray);}
function stripHtml(v){return decodeXml(String(v||'').replace(/<!--[\s\S]*?-->/g,' ').replace(/<script\b[\s\S]*?<\/script>/gi,' ').replace(/<style\b[\s\S]*?<\/style>/gi,' ').replace(/<br\s*\/?>/gi,' ').replace(/<[^>]+>/g,' '));}
function parseHtmlWorkbook(buffer){const html=buffer.toString('utf8').replace(/^\uFEFF/,'');if(!/<(?:html|table|tr|td|th)\b/i.test(html))throw new Error('Unsupported legacy Excel document format');const rows=[];for(const rm of html.matchAll(/<tr\b[^>]*>([\s\S]*?)<\/tr>/gi)){const cells=[...rm[1].matchAll(/<(?:td|th)\b[^>]*>([\s\S]*?)<\/(?:td|th)>/gi)].map(c=>normalizeText(stripHtml(c[1])));if(cells.length)rows.push(cells);}if(!rows.length)throw new Error('Legacy Excel workbook contains no HTML table rows');return[{name:'codal-html-workbook',rows:rows.slice(0,5000)}];}
function extractExcelRows(buffer){if(buffer.slice(0,4).toString('hex')!=='504b0304')return parseHtmlWorkbook(buffer);const entries=extractZipEntries(buffer),shared=parseSharedStrings(entries.has('xl/sharedStrings.xml')?entries.get('xl/sharedStrings.xml').toString('utf8'):''),sheets=[];for(const [name,content] of entries){if(!/^xl\/worksheets\/sheet\d+\.xml$/i.test(name))continue;sheets.push({name,rows:parseWorksheet(content.toString('utf8'),shared).slice(0,2000)});}return sheets.sort((a,b)=>a.name.localeCompare(b.name));}
const METRIC_PATTERNS={revenue:['فروش','درآمد عملیاتی','درآمد حاصل از فروش','درآمد'],operatingProfit:['سود عملیاتی','سود زیان عملیاتی','سود و زیان عملیاتی'],netProfit:['سود خالص','سود زیان خالص','سود و زیان خالص'],assets:['جمع دارایی','جمع داراییها','جمع دارایی ها','داراییهای کل','دارایی های کل'],liabilities:['جمع بدهی','جمع بدهیها','جمع بدهی ها','بدهیهای کل','بدهی های کل'],equity:['حقوق مالکانه','حقوق صاحبان سهام','جمع حقوق مالکانه'],cash:['وجه نقد','موجودی نقد','نقد و معادل نقد'],eps:['سود هر سهم','سود پایه هر سهم','سود زیان خالص هر سهم','سود و زیان خالص هر سهم','eps']};
const METRIC_PRIORITY={assets:['جمع دارایی ها','جمع داراییها','جمع دارایی','دارایی های کل','داراییهای کل'],liabilities:['جمع بدهی ها','جمع بدهیها','جمع بدهی','بدهی های کل','بدهیهای کل'],equity:['جمع حقوق مالکانه','حقوق صاحبان سهام','حقوق مالکانه'],revenue:['درآمدهای عملیاتی','درآمد عملیاتی','درآمد حاصل از فروش','فروش','درآمد'],operatingProfit:['سود زیان عملیاتی','سود و زیان عملیاتی','سود عملیاتی'],netProfit:['سود زیان خالص','سود و زیان خالص','سود خالص'],eps:['سود پایه هر سهم','سود زیان خالص هر سهم','سود و زیان خالص هر سهم','سود هر سهم','eps'],cash:['موجودی نقد','وجه نقد','نقد و معادل نقد']};
function metricPriority(metric,label){const normalized=normalizeMetricLabel(label);const patterns=METRIC_PRIORITY[metric]||[];const index=patterns.findIndex(p=>normalized===normalizeMetricLabel(p));if(index>=0)return 100-index;return patterns.some(p=>normalized.includes(normalizeMetricLabel(p)))?50:10;}
function findMetricValues(sheets){const best={};for(const sheet of sheets)for(const row of sheet.rows){const cells=row.map(normalizeText),normalizedCells=cells.map(normalizeMetricLabel);for(let i=0;i<cells.length;i++){const label=cells[i],normalizedLabel=normalizedCells[i];if(!normalizedLabel)continue;for(const [metric,patterns] of Object.entries(METRIC_PATTERNS)){if(!patterns.some(p=>normalizedLabel.includes(normalizeMetricLabel(p))))continue;const candidates=cells.slice(i+1).map(parseNumber).filter(v=>v!==null);if(!candidates.length)continue;const candidate={value:candidates[0],sheet:sheet.name,label,priority:metricPriority(metric,label)};if(!best[metric]||candidate.priority>best[metric].priority)best[metric]=candidate;}}}return Object.fromEntries(Object.entries(best).map(([k,v])=>[k,{value:v.value,sheet:v.sheet,label:v.label}]));}
async function extractFinancialDataFromExcel(rawUrl){const downloaded=await downloadDocument(rawUrl);if(!looksLikeExcel(downloaded.contentType,downloaded.finalUrl))throw new Error('CODAL attachment is not recognized as an Excel document');const sheets=extractExcelRows(downloaded.buffer);return{sourceType:'excel',url:downloaded.finalUrl,bytes:downloaded.bytes,sheetCount:sheets.length,metrics:findMetricValues(sheets)};}
async function extractFinancialDataFromAnnouncement(announcement){const excelUrl=announcement&&(announcement.link_excel||announcement.linkExcel);if(!excelUrl)return{available:false,sourceType:null,reason:'excel-link-not-available',metrics:{}};try{const result=await extractFinancialDataFromExcel(excelUrl);return{available:Object.keys(result.metrics).length>0,...result};}catch(error){return{available:false,sourceType:'excel',reason:error.message,metrics:{}};}}
module.exports={normalizeDigits,normalizeText,normalizeMetricLabel,parseNumber,validateDocumentUrl,downloadDocument,extractZipEntries,extractExcelRows,findMetricValues,extractFinancialDataFromExcel,extractFinancialDataFromAnnouncement};
