'use strict';
const fs=require('fs'); const path=require('path');
const brs=require('./brs.service.cjs');
const REFRESH_MS=300000, MAX_ROWS=50;
const file=path.join(__dirname,'..','data','daily-filters.json');
const defs=[
['high-buy-power','قدرت خرید بالا'],['highest-volume','بالاترین حجم'],['positive','سهم‌های مثبت'],['negative','سهم‌های منفی'],['highest-value','بالاترین ارزش معاملات'],['real-buy-volume','بالاترین حجم خرید حقیقی'],['real-sell-volume','بالاترین حجم فروش حقیقی'],['legal-buy-volume','بالاترین حجم خرید حقوقی'],['legal-sell-volume','بالاترین حجم فروش حقوقی'],['highest-buy-power','بالاترین قدرت خرید'],['growth-candidates','مستعد رشد'],['buy-queue','صف‌های خرید'],['sell-queue','صف‌های فروش']
];
let snap={updatedAt:null,filters:{}};
try{if(fs.existsSync(file))snap=JSON.parse(fs.readFileSync(file,'utf8'));}catch(e){}
const n=v=>Number.isFinite(Number(v))?Number(v):0;
function row(x){const rb=n(x.realBuyVolume),rs=n(x.realSellVolume),lb=n(x.instBuyVolume),ls=n(x.instSellVolume),rc=n(x.realBuyCount||x.Buy_I_Count||x.Buy_CountI),sc=n(x.realSellCount||x.Sell_I_Count||x.Sell_CountI);const bp=sc&&rc?((rb/rc)/(rs/sc||1)):0;return {symbol:x.symbol||x.l18||'',name:x.name||x.l30||'',buyPower:Number(bp.toFixed(2)),lastPrice:n(x.lastPrice||x.last),closingPrice:n(x.closingPrice||x.closePrice||x.close),lastChangePercent:n(x.lastChangePercent||x.plp),volume:n(x.tradeVolume||x.tradedVolume||x.volume),value:n(x.tradeValue||x.tradedValue||x.value),realBuyVolume:rb,realSellVolume:rs,legalBuyVolume:lb,legalSellVolume:ls,realBuyCount:rc,realSellCount:sc,legalBuyCount:n(x.instBuyCount||x.Buy_N_Count||x.Buy_CountN),legalSellCount:n(x.instSellCount||x.Sell_N_Count||x.Sell_CountN),pe:n(x.pe),eps:n(x.eps),buyQueueVolume:0,buyQueueCount:0,sellQueueVolume:0,sellQueueCount:0};}
function calc(a,id){const s=a.slice();const desc=(f)=>s.sort((x,y)=>f(y)-f(x)).slice(0,MAX_ROWS);if(id==='positive')return s.filter(x=>x.lastChangePercent>0).sort((x,y)=>y.lastChangePercent-x.lastChangePercent).slice(0,MAX_ROWS);if(id==='negative')return s.filter(x=>x.lastChangePercent<0).sort((x,y)=>x.lastChangePercent-y.lastChangePercent).slice(0,MAX_ROWS);if(id==='highest-volume')return desc(x=>x.volume);if(id==='highest-value')return desc(x=>x.value);if(id==='real-buy-volume')return desc(x=>x.realBuyVolume);if(id==='real-sell-volume')return desc(x=>x.realSellVolume);if(id==='legal-buy-volume')return desc(x=>x.legalBuyVolume);if(id==='legal-sell-volume')return desc(x=>x.legalSellVolume);if(id==='high-buy-power'||id==='highest-buy-power')return desc(x=>x.buyPower);if(id==='growth-candidates')return desc(x=>x.buyPower*2+Math.max(0,x.lastChangePercent));return s.slice(0,MAX_ROWS);}
async function refresh(){const status=await brs.getMarketStatus();if(!status.isOpen)return false;const r=await brs.getAllSymbols();const rows=(r.data||[]).map(row).filter(x=>x.symbol);for(const d of defs)snap.filters[d[0]]={rows:calc(rows,d[0]),updatedAt:new Date().toISOString()};snap.updatedAt=new Date().toISOString();snap.marketStatus=status;try{fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,JSON.stringify(snap));}catch(e){}return true;}
async function getFilters(force){const status=await brs.getMarketStatus();const age=snap.updatedAt?Date.now()-Date.parse(snap.updatedAt):Infinity;if(status.isOpen&&(force||age>=REFRESH_MS||!snap.updatedAt))await refresh();return {success:true,marketStatus:status,filters:defs.map(d=>({id:d[0],label:d[1],count:(snap.filters[d[0]]?.rows||[]).length,updatedAt:snap.filters[d[0]]?.updatedAt||snap.updatedAt,rows:snap.filters[d[0]]?.rows||[]}))};}
module.exports={getFilters,REFRESH_MS};
