'use strict';
const fs=require('fs'); const path=require('path'); const brs=require('./brs.service.cjs');
const REFRESH_MS=300000,MAX_ROWS=50,file=path.join(__dirname,'..','data','daily-filters.json');
const defs=[['high-buy-power','قدرت خرید بالا'],['highest-volume','بالاترین حجم'],['positive','سهم‌های مثبت'],['negative','سهم‌های منفی'],['highest-value','بالاترین ارزش معاملات'],['real-buy-volume','بالاترین حجم خرید حقیقی'],['real-sell-volume','بالاترین حجم فروش حقیقی'],['legal-buy-volume','بالاترین حجم خرید حقوقی'],['legal-sell-volume','بالاترین حجم فروش حقوقی'],['highest-buy-power','بالاترین قدرت خرید'],['growth-candidates','مستعد رشد'],['buy-queue','صف‌های خرید'],['sell-queue','صف‌های فروش'],['suspicious-volume','حجم معاملات مشکوک'],['buy-queue-contracting','جمع شدن صف خرید'],['sell-queue-contracting','جمع شدن صف فروش']];
let snap={updatedAt:null,marketStatus:null,filters:{},previous:{buy:{},sell:{}}};
try{if(fs.existsSync(file))snap=Object.assign(snap,JSON.parse(fs.readFileSync(file,'utf8')));}catch(e){}
const n=v=>Number.isFinite(Number(v))?Number(v):0; const first=(o,ks)=>{for(const k of ks)if(o&&o[k]!=null&&o[k]!=='')return o[k];return 0;};
function row(x,raw){const rb=n(x.realBuyVolume),rs=n(x.realSellVolume),lb=n(x.legalBuyVolume),ls=n(x.legalSellVolume),rc=n(x.realBuyCount),sc=n(x.realSellCount),lc=n(x.legalBuyCount),lsc=n(x.legalSellCount);const avg=n(first(raw,['tvol_avg_1m','volumeAvg1m','avgVolume1M'])),v=n(x.tradeVolume),last=n(x.lastPrice),max=n(first(raw,['tmax','allowedMax'])),min=n(first(raw,['tmin','allowedMin']));const bqv=n(first(raw,['qd1','Buy_Q_Volume','buyQueueVolume'])),bqc=n(first(raw,['zd1','Buy_Q_Count','buyQueueCount'])),sqv=n(first(raw,['qo1','Sell_Q_Volume','sellQueueVolume'])),sqc=n(first(raw,['zo1','Sell_Q_Count','sellQueueCount']));const isB=max>0&&last>=max&&bqv>0,isS=min>0&&last<=min&&sqv>0;const bp=rc>0&&sc>0&&rs>0?(rb/rc)/(rs/sc):0;return{symbol:x.symbol||'',name:x.name||'',buyPower:Number(bp.toFixed(2)),lastPrice:last,closingPrice:n(x.closingPrice),lastChangePercent:n(x.lastChangePercent),volume:v,value:n(x.tradeValue),realBuyVolume:rb,realSellVolume:rs,legalBuyVolume:lb,legalSellVolume:ls,realBuyCount:rc,realSellCount:sc,legalBuyCount:lc,legalSellCount:lsc,pe:n(x.pe),eps:n(x.eps),volumeAvg1m:avg,volumeRatio1m:avg>0?Number((v/avg).toFixed(2)):0,buyQueueVolume:isB?bqv:0,buyQueueCount:isB?bqc:0,sellQueueVolume:isS?sqv:0,sellQueueCount:isS?sqc:0};}
function desc(a,k){return a.slice().sort((x,y)=>n(y[k])-n(x[k])).slice(0,MAX_ROWS)}
function calc(a,id,p){if(id==='positive')return a.filter(x=>x.lastChangePercent>0).sort((x,y)=>y.lastChangePercent-x.lastChangePercent).slice(0,MAX_ROWS);if(id==='negative')return a.filter(x=>x.lastChangePercent<0).sort((x,y)=>x.lastChangePercent-y.lastChangePercent).slice(0,MAX_ROWS);if(id==='highest-volume')return desc(a,'volume');if(id==='highest-value')return desc(a,'value');if(id==='real-buy-volume')return desc(a,'realBuyVolume');if(id==='real-sell-volume')return desc(a,'realSellVolume');if(id==='legal-buy-volume')return desc(a,'legalBuyVolume');if(id==='legal-sell-volume')return desc(a,'legalSellVolume');if(id==='high-buy-power'||id==='highest-buy-power')return desc(a,'buyPower');if(id==='growth-candidates')return a.slice().sort((x,y)=>(y.buyPower*2+Math.max(0,y.lastChangePercent))-(x.buyPower*2+Math.max(0,x.lastChangePercent))).slice(0,MAX_ROWS);if(id==='buy-queue')return a.filter(x=>x.buyQueueVolume>0).sort((x,y)=>y.buyQueueVolume-x.buyQueueVolume).slice(0,MAX_ROWS);if(id==='sell-queue')return a.filter(x=>x.sellQueueVolume>0).sort((x,y)=>y.sellQueueVolume-x.sellQueueVolume).slice(0,MAX_ROWS);if(id==='suspicious-volume')return a.filter(x=>x.volumeAvg1m>0&&x.volumeRatio1m>4).sort((x,y)=>y.volumeRatio1m-x.volumeRatio1m).slice(0,MAX_ROWS);if(id==='buy-queue-contracting')return a.filter(x=>{const q=p.buy[x.symbol];return x.buyQueueVolume>0&&q&&(x.buyQueueVolume<q.volume||x.buyQueueCount<q.count)}).sort((x,y)=>y.buyQueueVolume-x.buyQueueVolume).slice(0,MAX_ROWS);if(id==='sell-queue-contracting')return a.filter(x=>{const q=p.sell[x.symbol];return x.sellQueueVolume>0&&q&&(x.sellQueueVolume<q.volume||x.sellQueueCount<q.count)}).sort((x,y)=>y.sellQueueVolume-x.sellQueueVolume).slice(0,MAX_ROWS);return a.slice(0,MAX_ROWS)}
async function refresh(){const status=await brs.getMarketStatus();if(!status.isOpen)return false;const r=await brs.getAllSymbols(),mapped=Array.isArray(r.data)?r.data:[],raw=Array.isArray(r.raw)?r.raw:[],rawMap=new Map();raw.forEach(z=>{const s=z&&(z.l18||z.symbol);if(s)rawMap.set(String(s),z)});const rows=mapped.map(x=>row(x,rawMap.get(String(x.symbol))||{})).filter(x=>x.symbol),prev={buy:{},sell:{}};(snap.filters['buy-queue']?.rows||[]).forEach(x=>prev.buy[x.symbol]={volume:n(x.buyQueueVolume),count:n(x.buyQueueCount)});(snap.filters['sell-queue']?.rows||[]).forEach(x=>prev.sell[x.symbol]={volume:n(x.sellQueueVolume),count:n(x.sellQueueCount)});snap.previous=prev;const now=new Date().toISOString();for(const [id,label] of defs)snap.filters[id]={label,rows:calc(rows,id,prev),updatedAt:now};snap.updatedAt=now;snap.marketStatus=status;fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,JSON.stringify(snap),'utf8');return true}
async function getFilters(force){const status=await brs.getMarketStatus(),age=snap.updatedAt?Date.now()-Date.parse(snap.updatedAt):Infinity;if(status.isOpen&&(force||age>=REFRESH_MS||!snap.updatedAt))await refresh();return{success:true,marketStatus:status,filters:defs.map(([id,label])=>({id,label,count:status.isOpen?(snap.filters[id]?.rows||[]).length:0,updatedAt:snap.filters[id]?.updatedAt||snap.updatedAt||null,rows:status.isOpen?(snap.filters[id]?.rows||[]):[]}))}}
module.exports={getFilters,refresh,REFRESH_MS};
