'use strict';
const express=require('express');
const {prisma}=require('../config/prisma.cjs');
const authMiddleware=require('../middlewares/auth.middleware.cjs');
const {hasPermission}=require('../services/rbac.service.cjs');
const router=express.Router();
const uid=req=>Number(req.user?.id??req.user?.userId??0)||null;
async function admin(req,res,next){const id=uid(req);if(!id)return res.status(401).json({success:false,message:'احراز هویت الزامی است.'});try{if(!(await hasPermission(id,'admin.payments.manage')))return res.status(403).json({success:false,message:'دسترسی مدیریت پرداخت‌ها مجاز نیست.'});next();}catch(e){res.status(500).json({success:false,message:'بررسی دسترسی ناموفق بود.'});}}
async function ensure(){await prisma.$executeRawUnsafe(`IF OBJECT_ID(N'dbo.AdminPaymentTransaction',N'U') IS NULL BEGIN CREATE TABLE dbo.AdminPaymentTransaction(id BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,userId INT NOT NULL,amount DECIMAL(18,2) NOT NULL,currency NVARCHAR(10) NOT NULL DEFAULT N'IRR',gateway NVARCHAR(50) NULL,authority NVARCHAR(200) NULL,referenceNo NVARCHAR(200) NULL,status NVARCHAR(30) NOT NULL DEFAULT N'pending',description NVARCHAR(500) NULL,createdAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),updatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),paidAt DATETIME2 NULL); CREATE INDEX IX_AdminPaymentTransaction_userId ON dbo.AdminPaymentTransaction(userId); CREATE INDEX IX_AdminPaymentTransaction_status ON dbo.AdminPaymentTransaction(status); END;`);}
router.use(authMiddleware,admin);
router.get('/summary',async(req,res)=>{try{await ensure();const rows=await prisma.$queryRawUnsafe(`SELECT currency,COUNT_BIG(*) total,COALESCE(SUM(CASE WHEN status=N'paid' THEN amount ELSE 0 END),0) paidAmount,COALESCE(SUM(CASE WHEN status=N'pending' THEN amount ELSE 0 END),0) pendingAmount,COALESCE(SUM(CASE WHEN status=N'refunded' THEN amount ELSE 0 END),0) refundedAmount,COALESCE(SUM(CASE WHEN status=N'failed' THEN amount ELSE 0 END),0) failedAmount,COALESCE(SUM(CASE WHEN status=N'paid' THEN 1 ELSE 0 END),0) paidCount,COALESCE(SUM(CASE WHEN status=N'pending' THEN 1 ELSE 0 END),0) pendingCount,COALESCE(SUM(CASE WHEN status=N'refunded' THEN 1 ELSE 0 END),0) refundedCount,COALESCE(SUM(CASE WHEN status=N'failed' THEN 1 ELSE 0 END),0) failedCount FROM dbo.AdminPaymentTransaction GROUP BY currency`);const data={total:0,paidCount:0,pendingCount:0,refundedCount:0,failedCount:0,byCurrency:{}};for(const r of rows){const currency=String(r.currency||'IRR');data.total+=Number(r.total||0);data.paidCount+=Number(r.paidCount||0);data.pendingCount+=Number(r.pendingCount||0);data.refundedCount+=Number(r.refundedCount||0);data.failedCount+=Number(r.failedCount||0);data.byCurrency[currency]={paidAmount:Number(r.paidAmount||0),pendingAmount:Number(r.pendingAmount||0),refundedAmount:Number(r.refundedAmount||0),failedAmount:Number(r.failedAmount||0)};}return res.json({success:true,data});}catch(e){console.error('[AdminPayments] summary:',e);res.status(500).json({success:false,message:'دریافت خلاصه مالی ناموفق بود.'});}});
router.get('/transactions',async(req,res)=>{try{await ensure();const page=Math.max(1,Number(req.query.page)||1),limit=Math.min(100,Math.max(1,Number(req.query.limit)||20)),userId=Number(req.query.userId)||0,search=String(req.query.search||'').trim(),status=String(req.query.status||'').trim().toLowerCase(),gateway=String(req.query.gateway||'').trim(),currency=String(req.query.currency||'').trim().toUpperCase(),from=String(req.query.from||'').trim(),to=String(req.query.to||'').trim();const conditions=[];const params=[];if(userId){conditions.push(`userId=@p${params.length+1}`);params.push(userId);}if(status){conditions.push(`status=@p${params.length+1}`);params.push(status);}if(gateway){conditions.push(`gateway LIKE @p${params.length+1}`);params.push(`%${gateway}%`);}if(currency){conditions.push(`currency=@p${params.length+1}`);params.push(currency);}if(search){conditions.push(`(referenceNo LIKE @p${params.length+1} OR authority LIKE @p${params.length+1} OR description LIKE @p${params.length+1})`);params.push(`%${search}%`);}if(from){const d=new Date(from);if(!Number.isNaN(d.getTime())){conditions.push(`createdAt>=@p${params.length+1}`);params.push(d);}}if(to){const d=new Date(to);if(!Number.isNaN(d.getTime())){d.setHours(23,59,59,999);conditions.push(`createdAt<=@p${params.length+1}`);params.push(d);}}const where=conditions.length?`WHERE ${conditions.join(' AND ')}`:'';const countRows=await prisma.$queryRawUnsafe(`SELECT COUNT_BIG(*) total FROM dbo.AdminPaymentTransaction ${where}`,...params);const total=Number(countRows[0]?.total||0);const offset=(page-1)*limit;const rows=await prisma.$queryRawUnsafe(`SELECT id,userId,amount,currency,gateway,authority,referenceNo,status,description,createdAt,paidAt FROM dbo.AdminPaymentTransaction ${where} ORDER BY id DESC OFFSET ${offset} ROWS FETCH NEXT ${limit} ROWS ONLY`,...params);return res.json({success:true,data:{items:rows,pagination:{page,limit,total,totalPages:Math.ceil(total/limit)}}});}catch(e){console.error('[AdminPayments] transactions:',e);res.status(500).json({success:false,message:'دریافت تراکنش‌ها ناموفق بود.'});}});
module.exports=router;
