'use strict';
const express=require('express');
const {prisma}=require('../config/prisma.cjs');
const authMiddleware=require('../middlewares/auth.middleware.cjs');
const {hasPermission}=require('../services/rbac.service.cjs');
const router=express.Router();
const uid=req=>Number(req.user?.id??req.user?.userId??0)||null;
async function admin(req,res,next){const id=uid(req);if(!id)return res.status(401).json({success:false,message:'احراز هویت الزامی است.'});try{if(!(await hasPermission(id,'admin.analysis.manage')))return res.status(403).json({success:false,message:'دسترسی مدیریت تحلیل‌ها مجاز نیست.'});next();}catch(e){console.error('[AdminAnalyses] permission:',e.message);res.status(500).json({success:false,message:'بررسی دسترسی ناموفق بود.'});}}
function parseResult(raw){if(!raw)return {};try{const x=JSON.parse(raw);return x&&typeof x==='object'&&!Array.isArray(x)?x:{}}catch{return {}}}
function first(o,keys){for(const k of keys)if(o[k]!==undefined&&o[k]!==null&&o[k]!=='')return o[k];return undefined}
function normalizeType(v){const s=String(v??'').trim().toLowerCase();const m={technical:'technical',fundamental:'fundamental',comparison:'comparison',scalping:'scalping',summary:'summary',portfolio:'portfolio',تکنیکال:'technical',بنیادی:'fundamental',مقایسه:'comparison',نوسان‌گیری:'scalping','نوسان گیری':'scalping','خلاصه بازار':'summary',سبد:'portfolio','سبد سرمایه‌گذاری':'portfolio'};return m[s]||s}
function typeLabel(v){const k=normalizeType(v);return {technical:'تکنیکال',fundamental:'بنیادی',comparison:'مقایسه',scalping:'نوسان‌گیری',summary:'خلاصه بازار',portfolio:'سبد سرمایه‌گذاری'}[k]||String(v??'تحلیل')||'تحلیل'}
function item(r){const x=parseResult(r.resultJson),s=String(first(x,['status','analysisStatus','state'])??'completed').toLowerCase(),t=first(x,['analysisType','type','featureKey']);return {id:r.id,userId:r.userId,username:r.user?.username||'—',email:r.user?.email||null,name:r.user?.name||null,symbol:r.stock||'—',createdAt:r.createdAt,status:s==='failed'?'failed':s==='pending'?'pending':'completed',statusLabel:s==='failed'?'ناموفق':s==='pending'?'در انتظار':'تکمیل‌شده',analysisType:typeLabel(t),analysisTypeKey:normalizeType(t),hasResult:!!r.resultJson,result:r.resultJson||null};}
router.use(authMiddleware,admin);
router.get('/analytics',async(req,res)=>{try{const rows=await prisma.analysisHistory.findMany({select:{id:true,userId:true,stock:true,resultJson:true,createdAt:true,user:{select:{username:true,email:true,name:true}}},orderBy:{createdAt:'desc'}});const now=Date.now(),d24=new Date(now-86400000),d7=new Date(now-7*86400000),d30=new Date(now-30*86400000);const stats={total:rows.length,last24h:0,last7d:0,last30d:0,completed:0,failed:0,pending:0,withResult:0,failedRate:0,byType:{},topSymbols:[],topUsers:[]};const symbols=new Map(),users=new Map();for(const r of rows){const x=item(r),t=r.createdAt?new Date(r.createdAt):null;if(t&&t>=d24)stats.last24h++;if(t&&t>=d7)stats.last7d++;if(t&&t>=d30)stats.last30d++;stats[x.status]++;if(x.hasResult)stats.withResult++;const type=x.analysisTypeKey||'other';stats.byType[type]=(stats.byType[type]||0)+1;const sym=String(x.symbol||'—').trim()||'—';symbols.set(sym,(symbols.get(sym)||0)+1);const user=x.name||x.username||'—';users.set(user,(users.get(user)||0)+1);}stats.failedRate=stats.total?Number((stats.failed*100/stats.total).toFixed(1)):0;stats.topSymbols=[...symbols.entries()].sort((a,b)=>b[1]-a[1]).slice(0,8).map(([symbol,count])=>({symbol,count}));stats.topUsers=[...users.entries()].sort((a,b)=>b[1]-a[1]).slice(0,8).map(([user,count])=>({user,count}));return res.json({success:true,data:stats});}catch(e){console.error('[AdminAnalyses] analytics:',e);res.status(500).json({success:false,message:'دریافت آمار مصرف تحلیل‌ها ناموفق بود.'});}});
router.get('/',async(req,res)=>{try{const page=Math.max(1,Number(req.query.page)||1),limit=Math.min(100,Math.max(1,Number(req.query.limit)||20)),search=String(req.query.search||'').trim(),symbol=String(req.query.symbol||'').trim(),status=String(req.query.status||'').trim(),type=normalizeType(req.query.type),from=String(req.query.from||'').trim(),to=String(req.query.to||'').trim();const where={};if(symbol)where.stock={contains:symbol};if(from){const d=new Date(from);if(!Number.isNaN(d.getTime()))where.createdAt={gte:d}}if(to){const d=new Date(to);if(!Number.isNaN(d.getTime())){d.setHours(23,59,59,999);where.createdAt={...(where.createdAt||{}),lte:d}}}if(search)where.user={OR:[{username:{contains:search}},{email:{contains:search}}]};const rows=await prisma.analysisHistory.findMany({where,orderBy:{createdAt:'desc'},select:{id:true,userId:true,stock:true,resultJson:true,createdAt:true,user:{select:{username:true,email:true,name:true}}}});let filtered=rows.map(item);if(status)filtered=filtered.filter(x=>x.status===status);if(type)filtered=filtered.filter(x=>x.analysisTypeKey===type);const total=filtered.length,items=filtered.slice((page-1)*limit,page*limit),completed=filtered.filter(x=>x.status==='completed').length,failed=filtered.filter(x=>x.status==='failed').length;return res.json({success:true,data:{items,pagination:{page,limit,total,totalPages:Math.ceil(total/limit)},summary:{total,shown:items.length,completed,failed,analysisCount:filtered.length}}});}catch(e){console.error('[AdminAnalyses] list:',e);res.status(500).json({success:false,message:'دریافت فهرست تحلیل‌ها ناموفق بود.'});}});
module.exports=router;
