'use strict';

const express = require('express');
const { prisma } = require('../config/prisma.cjs');
const authMiddleware = require('../middlewares/auth.middleware.cjs');
const { hasPermission } = require('../services/rbac.service.cjs');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const router = express.Router();
const MODULE_ACTIONS = {
  users: ['activate-user', 'deactivate-user'], subscriptions: ['set-subscription'], analysis: ['delete-analysis'], history: ['delete-history-item'], notifications: ['broadcast'],
  sessions: ['list-sessions', 'revoke-session', 'revoke-all-user-sessions'], api: ['list-api-keys', 'revoke-api-key'], roles: ['list-roles', 'assign-role'],
  security: ['set-policy'], settings: ['set-setting'], maintenance: ['enable', 'disable'], ai: ['set-config'], prompts: ['set-prompt'], market: ['health-check'], scalping: ['health-check'], monitoring: ['health-check'], reports: ['snapshot'], infrastructure: ['health-check'],
  updates: ['set-channel', 'record-deployment', 'get-deployments'], backup: ['set-policy', 'create-backup', 'get-status', 'validate-backup', 'list-restorable', 'prepare-restore', 'restore-backup'], payments: ['create-transaction', 'set-status', 'list-transactions'], audit: [], dashboard: [],
};
const VIEW_ONLY_MODULES = new Set(['dashboard', 'monitoring', 'reports', 'audit']);
function userId(req) { return Number(req.user?.id ?? req.user?.userId ?? 0) || null; }
function isAdmin(req) { const u=req.user||{}; if(u.isAdmin===true||['admin','superadmin'].includes(String(u.role||'').toLowerCase())) return true; return (Array.isArray(u.roles)?u.roles:[]).some(r=>['admin','superadmin'].includes(String(typeof r==='string'?r:r?.name).toLowerCase())); }
function fail(res,status,message){return res.status(status).json({success:false,message});}
function requiredPermission(moduleKey){return `admin.${moduleKey}.${VIEW_ONLY_MODULES.has(moduleKey)?'view':'manage'`;}
async function canUseModule(req,moduleKey){return !!(userId(req)&&await hasPermission(userId(req),requiredPermission(moduleKey)));}
async function audit(req,moduleKey,action,statusCode,details){try{await prisma.$executeRawUnsafe(`IF OBJECT_ID(N'dbo.AdminAuditLog',N'U') IS NOT NULL INSERT INTO dbo.AdminAuditLog(adminUserId,action,moduleKey,targetId,method,path,statusCode,ipAddress,userAgent,detailsJson) VALUES(@p1,@p2,@p3,@p4,@p5,@p6,@p7,@p8,@p9,@p10)`,userId(req),action,moduleKey,details?.targetId==null?null:String(details.targetId),req.method,req.originalUrl,statusCode,req.ip||null,String(req.get('user-agent')||'').slice(0,500),details?JSON.stringify(details):null);}catch(_){} }
async function setGlobalSetting(key,value,category='admin'){const serialized=typeof value==='string'?value:JSON.stringify(value);await prisma.$executeRawUnsafe(`MERGE dbo.GlobalSetting AS target USING (SELECT @p1 AS [key],@p2 AS [value],@p3 AS [category]) AS source ON target.[key]=source.[key] WHEN MATCHED THEN UPDATE SET [value]=source.[value],category=source.[category],version=target.version+1,updatedAt=SYSDATETIME() WHEN NOT MATCHED THEN INSERT ([category],[key],[value],[version],[isPublic],[updatedAt]) VALUES(source.[category],source.[key],source.[value],1,0,SYSDATETIME());`,key,serialized,category);}
async function ensureOperationalTables(){await prisma.$executeRawUnsafe(`IF OBJECT_ID(N'dbo.AdminPaymentTransaction',N'U') IS NULL BEGIN CREATE TABLE dbo.AdminPaymentTransaction(id BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,userId INT NOT NULL,amount DECIMAL(18,2) NOT NULL,currency NVARCHAR(10) NOT NULL DEFAULT N'IRR',gateway NVARCHAR(50) NULL,authority NVARCHAR(200) NULL,referenceNo NVARCHAR(200) NULL,status NVARCHAR(30) NOT NULL DEFAULT N'pending',description NVARCHAR(500) NULL,createdAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),updatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),paidAt DATETIME2 NULL); CREATE INDEX IX_AdminPaymentTransaction_userId ON dbo.AdminPaymentTransaction(userId); CREATE INDEX IX_AdminPaymentTransaction_status ON dbo.AdminPaymentTransaction(status); END; IF OBJECT_ID(N'dbo.AdminBackupJob',N'U') IS NULL BEGIN CREATE TABLE dbo.AdminBackupJob(id BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,type NVARCHAR(30) NOT NULL DEFAULT N'database',filePath NVARCHAR(500) NULL,status NVARCHAR(30) NOT NULL,startedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),finishedAt DATETIME2 NULL,sizeBytes BIGINT NULL,errorMessage NVARCHAR(1000) NULL,createdBy INT NULL); CREATE INDEX IX_AdminBackupJob_startedAt ON dbo.AdminBackupJob(startedAt); END; IF OBJECT_ID(N'dbo.AdminDeploymentLog',N'U') IS NULL BEGIN CREATE TABLE dbo.AdminDeploymentLog(id BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,version NVARCHAR(100) NULL,channel NVARCHAR(30) NOT NULL,commitSha NVARCHAR(100) NULL,status NVARCHAR(30) NOT NULL,detailsJson NVARCHAR(MAX) NULL,createdAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),createdBy INT NULL); CREATE INDEX IX_AdminDeploymentLog_createdAt ON dbo.AdminDeploymentLog(createdAt); END;`);}
function safeBackupPath(value){const dir=process.env.ADMIN_BACKUP_DIR;if(!dir||!value)return null;const root=path.resolve(dir),candidate=path.resolve(value);return candidate===root||candidate.startsWith(root+path.sep)?candidate:null;}
function currentDbName(){try{return new URL(process.env.DATABASE_URL).pathname.replace(/^\\//,'').split('?')[0]||null;}catch(_){return null;}}
router.use(authMiddleware,(req,res,next)=>isAdmin(req)?next():fail(res,403,'این عملیات فقط برای ادمین مجاز است.'));
router.get('/capabilities/:moduleKey',async(req,res)=>{const key=req.params.moduleKey;if(!(key in MODULE_ACTIONS))return fail(res,404,'ماژول مدیریتی پیدا نشد.');if(!(await canUseModule(req,key)))return fail(res,403,'دسترسی مشاهده این ماژول برای شما مجاز نیست.');return res.json({success:true,data:{moduleKey:key,actions:MODULE_ACTIONS[key],transactional:MODULE_ACTIONS[key].length>0}});});
router.post('/:moduleKey/:action',async(req,res)=>{const {moduleKey,action}=req.params;if(!(Object.prototype.hasOwnProperty.call(MODULE_ACTIONS,moduleKey)&&MODULE_ACTIONS[moduleKey].includes(action)))return fail(res,404,'عملیات مدیریتی پشتیبانی نمی‌شود.');if(!(await canUseModule(req,moduleKey)))return fail(res,403,'سطح دسترسی لازم برای این عملیات را ندارید.');const body=req.body||{};try{let data;switch(`${moduleKey}:${action}`){
case 'users:activate-user':case 'users:deactivate-user':{const id=Number(body.userId);if(!id)return fail(res,400,'شناسه کاربر الزامی است.');data=await prisma.user.update({where:{id},data:{isActive:action==='activate-user',isDeleted:false}});break;}
case 'subscriptions:set-subscription':{const id=Number(body.userId);if(!id)return fail(res,400,'شناسه کاربر الزامی است.');const months=Math.max(0,Number(body.subscriptionMonths??0)||0);const end=body.subscriptionEnd?new Date(body.subscriptionEnd):null;if(end&&Number.isNaN(end.getTime()))return fail(res,400,'تاریخ پایان اشتراک نامعتبر است.');data=await prisma.user.update({where:{id},data:{subscriptionType:body.subscriptionType==null?undefined:String(body.subscriptionType).slice(0,50),subscriptionMonths:months,subscriptionStart:body.subscriptionStart?new Date(body.subscriptionStart):undefined,subscriptionEnd:end,analysisLimit:Math.max(0,Number(body.analysisLimit??0)||0)}});break;}
case 'analysis:delete-analysis':case 'history:delete-history-item':{const id=Number(body.id);if(!id)return fail(res,400,'شناسه تحلیل الزامی است.');data=await prisma.analysisHistory.delete({where:{id}});break;}
case 'notifications:broadcast':{const title=String(body.title||'').trim(),message=String(body.message||'').trim();if(!title||!message)return fail(res,400,'عنوان و متن اعلان الزامی است.');const users=await prisma.user.findMany({where:{isDeleted:false,isActive:true},select:{id:true}});if(users.length)await prisma.notification.createMany({data:users.map(u=>({userId:u.id,title,message,type:String(body.type||'info').slice(0,50)}))});data={recipients:users.length};break;}
case 'sessions:list-sessions':{data=await prisma.$queryRawUnsafe(`SELECT TOP 50 s.id,s.userId,u.username,u.email,s.createdAt FROM dbo.Session s LEFT JOIN dbo.[User] u ON u.id=s.userId ORDER BY s.createdAt DESC`);break;}
case 'sessions:revoke-session':{const id=Number(body.sessionId);if(!id)return fail(res,400,'شناسه نشست الزامی است.');await prisma.session.delete({where:{id}});data={revoked:true,sessionId:id};break;}
case 'sessions:revoke-all-user-sessions':{const id=Number(body.userId);if(!id)return fail(res,400,'شناسه کاربر الزامی است.');const result=await prisma.session.deleteMany({where:{userId:id}});data={revoked:result.count,userId:id};break;}
case 'api:list-api-keys':{data=await prisma.$queryRawUnsafe(`SELECT TOP 100 k.id,k.userId,k.name,k.createdAt,k.isRevoked,u.username,u.email FROM dbo.ApiKey k LEFT JOIN dbo.[User] u ON u.id=k.userId ORDER BY k.createdAt DESC`);break;}
case 'api:revoke-api-key':{const id=Number(body.apiKeyId);if(!id)return fail(res,400,'شناسه API Key الزامی است.');data=await prisma.apiKey.update({where:{id},data:{isRevoked:true},select:{id:true,isRevoked:true}});break;}
case 'roles:list-roles':{const roles=await prisma.role.findMany({orderBy:{id:'asc'},include:{_count:{select:{users:true,permissions:true}}}});data=roles.map(r=>({id:r.id,name:r.name,title:r.title,userCount:r._count.users,permissionCount:r._count.permissions}));break;}
case 'roles:assign-role':{const id=Number(body.userId),roleId=Number(body.roleId);if(!id||!roleId)return fail(res,400,'شناسه کاربر و نقش الزامی است.');await prisma.role.findUniqueOrThrow({where:{id:roleId}});data=await prisma.user.update({where:{id},data:{roleId},select:{id:true,roleId:true}});break;}
case 'security:set-policy':await setGlobalSetting(`security.${String(body.key||'policy')}`,body.value??{},'security');data={saved:true};break;
case 'settings:set-setting':if(!body.key)return fail(res,400,'کلید تنظیمات الزامی است.');await setGlobalSetting(String(body.key).slice(0,100),body.value??'','settings');data={saved:true,key:body.key};break;
case 'maintenance:enable':case 'maintenance:disable':await setGlobalSetting('maintenance.enabled',action==='enable','maintenance');data={enabled:action==='enable'};break;
case 'ai:set-config':await setGlobalSetting(`ai.${String(body.key||'config')}`,body.value??{},'ai');data={saved:true};break;
case 'prompts:set-prompt':if(!body.name)return fail(res,400,'نام پرامپت الزامی است.');await setGlobalSetting(`prompt.${String(body.name).slice(0,90)}`,String(body.value||''),'prompts');data={saved:true,name:body.name};break;
case 'updates:set-channel':{const ch=String(body.channel||'stable').toLowerCase();if(!['stable','beta'].includes(ch))return fail(res,400,'کانال انتشار نامعتبر است.');await setGlobalSetting('updates.channel',ch,'updates');data={channel:ch};break;}
case 'updates:record-deployment':{await ensureOperationalTables();const version=String(body.version||'').slice(0,100);const sha=String(body.commitSha||'').slice(0,100);if(!version&&!sha)return fail(res,400,'نسخه یا Commit SHA الزامی است.');const status=String(body.status||'completed').slice(0,30);const executionSource=String(body.executionSource||'admin-record').slice(0,40);const backupId=body.backupId==null?null:Number(body.backupId)||null;await prisma.$executeRawUnsafe(`INSERT INTO dbo.AdminDeploymentLog(version,channel,commitSha,status,detailsJson,createdBy) VALUES(@p1,@p2,@p3,@p4,@p5,@p6)`,version,String(body.channel||'stable'),sha,status,JSON.stringify({...(body.details||{}),executionSource,actualCiCd:executionSource==='ci-cd',backupId}),userId(req));data={recorded:true,version,commitSha:sha,status,executionSource,actualCiCd:executionSource==='ci-cd',backupId};break;}
case 'updates:get-deployments':{await ensureOperationalTables();data=await prisma.$queryRawUnsafe(`SELECT TOP 15 id,version,channel,commitSha,status,detailsJson,createdAt FROM dbo.AdminDeploymentLog ORDER BY id DESC`);data=data.map(r=>{let details={};try{details=r.detailsJson?JSON.parse(r.detailsJson):{};}catch(_){ }return {...r,executionSource:details.executionSource||'admin-record',actualCiCd:details.actualCiCd===true,backupId:details.backupId??null};});break;}
case 'backup:set-policy':{const value=body.value&&typeof body.value==='object'?body.value:{};const policy={enabled:value.enabled!==false,retentionDays:Math.max(1,Number(value.retentionDays??30)||30),maxVersions:Math.max(1,Number(value.maxVersions??10)||10),path:String(value.path||process.env.ADMIN_BACKUP_DIR||'').slice(0,500),warnIfMissing:value.warnIfMissing!==false};await setGlobalSetting('backup.policy',policy,'backup');data={saved:true,policy};break;}
case 'backup:get-status':{await ensureOperationalTables();const rows=await prisma.$queryRawUnsafe(`SELECT TOP 50 id,type,filePath,status,startedAt,finishedAt,sizeBytes,errorMessage FROM dbo.AdminBackupJob ORDER BY id DESC`);const dir=process.env.ADMIN_BACKUP_DIR||null;const successful=rows.filter(r=>r.status==='completed').length,failed=rows.filter(r=>r.status==='failed').length;const latest=rows.find(r=>r.status==='completed')||rows[0]||null;const valid=latest&&latest.filePath&&safeBackupPath(latest.filePath)&&fs.existsSync(latest.filePath)&&Number(fs.statSync(latest.filePath).size)>0;data={rows,summary:{total:rows.length,successful,failed,latest,latestValid:!!valid,backupDirectory:dir}};break;}
case 'backup:create-backup':{await ensureOperationalTables();const dir=process.env.ADMIN_BACKUP_DIR;if(!dir)return fail(res,503,'ADMIN_BACKUP_DIR تنظیم نشده است.');fs.mkdirSync(dir,{recursive:true});const dbName=currentDbName();if(!dbName)return fail(res,503,'نام دیتابیس از DATABASE_URL قابل تشخیص نیست.');const filename=`roniya-${new Date().toISOString().replace(/[:.]/g,'-')}.bak`;const filePath=path.join(dir,filename);const job=await prisma.$queryRawUnsafe(`INSERT INTO dbo.AdminBackupJob(type,filePath,status,createdBy) OUTPUT INSERTED.id VALUES(N'database',@p1,N'running',@p2)`,filePath,userId(req));const id=Number(job[0].id);try{await prisma.$executeRawUnsafe(`BACKUP DATABASE [${dbName.replace(/]/g,']]')}] TO DISK=@p1 WITH INIT, CHECKSUM`,filePath);const stat=fs.statSync(filePath);if(stat.size<=0)throw new Error('فایل Backup ایجاد شد ولی حجم آن صفر است.');await prisma.$executeRawUnsafe(`UPDATE dbo.AdminBackupJob SET status=N'completed',finishedAt=SYSDATETIME(),sizeBytes=@p1 WHERE id=@p2`,stat.size,id);data={jobId:id,status:'completed',filePath,sizeBytes:stat.size,dbName};}catch(error){await prisma.$executeRawUnsafe(`UPDATE dbo.AdminBackupJob SET status=N'failed',finishedAt=SYSDATETIME(),errorMessage=@p1 WHERE id=@p2`,String(error.message).slice(0,1000),id);throw error;}break;}
case 'backup:validate-backup':{await ensureOperationalTables();const id=Number(body.jobId);if(!id)return fail(res,400,'شناسه Backup الزامی است.');const rows=await prisma.$queryRawUnsafe(`SELECT TOP 1 id,filePath,status,sizeBytes FROM dbo.AdminBackupJob WHERE id=@p1`,id);if(!rows.length)return fail(res,404,'Backup پیدا نشد.');const row=rows[0],resolved=safeBackupPath(row.filePath),exists=!!resolved&&fs.existsSync(resolved);let sizeBytes=exists?fs.statSync(resolved).size:0,verifyOnly=false,errorMessage=null;if(exists&&sizeBytes>0){try{await prisma.$executeRawUnsafe(`RESTORE VERIFYONLY FROM DISK=@p1 WITH CHECKSUM`,resolved);verifyOnly=true;}catch(error){errorMessage=String(error.message).slice(0,1000);}}data={jobId:id,filePath:row.filePath,exists,sizeBytes,nonEmpty:sizeBytes>0,verifyOnly,valid:exists&&sizeBytes>0&&verifyOnly,errorMessage};break;}
case 'backup:list-restorable':{await ensureOperationalTables();const rows=await prisma.$queryRawUnsafe(`SELECT TOP 20 id,filePath,status,startedAt,finishedAt,sizeBytes,errorMessage FROM dbo.AdminBackupJob WHERE status=N'completed' ORDER BY id DESC`);data=rows.map(r=>{const resolved=safeBackupPath(r.filePath),exists=!!resolved&&fs.existsSync(resolved),sizeBytes=exists?fs.statSync(resolved).size:Number(r.sizeBytes||0);return {...r,exists,nonEmpty:sizeBytes>0,sizeBytes,restorableCandidate:exists&&sizeBytes>0};}).filter(r=>r.restorableCandidate);break;}
case 'backup:prepare-restore':{await ensureOperationalTables();const id=Number(body.jobId);if(!id)return fail(res,400,'شناسه Backup الزامی است.');const rows=await prisma.$queryRawUnsafe(`SELECT TOP 1 id,filePath,status FROM dbo.AdminBackupJob WHERE id=@p1`,id);if(!rows.length||rows[0].status!=='completed')return fail(res,400,'Backup انتخاب‌شده قابل آماده‌سازی برای بازیابی نیست.');const resolved=safeBackupPath(rows[0].filePath);if(!resolved||!fs.existsSync(resolved)||fs.statSync(resolved).size<=0)return fail(res,400,'فایل Backup معتبر نیست.');const token=crypto.randomBytes(18).toString('hex');await setGlobalSetting(`backup.restore.challenge.${id}`,{token,expiresAt:Date.now()+10*60*1000},'backup');data={jobId:id,confirmationToken:token,expiresInSeconds:600,warning:'این مرحله فقط مجوز موقت ایجاد می‌کند و هنوز Restore انجام نشده است.'};break;}
case 'backup:restore-backup':{await ensureOperationalTables();const id=Number(body.jobId);const token=String(body.confirmationToken||'');const target=String(body.targetDatabase||'').trim();if(!id||!token||!target)return fail(res,400,'Backup، توکن تأیید و دیتابیس مقصد الزامی است.');const productionDb=currentDbName();if(process.env.ADMIN_RESTORE_ENABLED!=='true')return fail(res,403,'Restore از پنل غیرفعال است؛ ابتدا ADMIN_RESTORE_ENABLED=true را صریحاً فعال کنید.');if(process.env.ADMIN_ALLOW_PRODUCTION_RESTORE!=='true'&&target===productionDb)return fail(res,403,'Restore مستقیم روی دیتابیس Production مسدود است.');if(process.env.ADMIN_RESTORE_TARGET&&target!==process.env.ADMIN_RESTORE_TARGET)return fail(res,403,'دیتابیس مقصد با مقصد مجاز Restore یکسان نیست.');const settingRows=await prisma.$queryRawUnsafe(`SELECT TOP 1 [value] FROM dbo.GlobalSetting WHERE [key]=@p1`,`backup.restore.challenge.${id}`);let challenge=null;try{challenge=settingRows.length?JSON.parse(settingRows[0].value):null;}catch(_){ }if(!challenge||challenge.token!==token||Number(challenge.expiresAt||0)<Date.now())return fail(res,403,'توکن تأیید Restore نامعتبر یا منقضی شده است.');const rows=await prisma.$queryRawUnsafe(`SELECT TOP 1 id,filePath,status FROM dbo.AdminBackupJob WHERE id=@p1`,id);if(!rows.length||rows[0].status!=='completed')return fail(res,400,'Backup قابل بازیابی نیست.');const resolved=safeBackupPath(rows[0].filePath);if(!resolved||!fs.existsSync(resolved)||fs.statSync(resolved).size<=0)return fail(res,400,'فایل Backup معتبر نیست.');await prisma.$executeRawUnsafe(`RESTORE VERIFYONLY FROM DISK=@p1 WITH CHECKSUM`,resolved);if(target===productionDb&&process.env.ADMIN_ALLOW_PRODUCTION_RESTORE!=='true')return fail(res,403,'Restore روی Production مجاز نیست.');await prisma.$executeRawUnsafe(`RESTORE DATABASE [${target.replace(/]/g,']]')}] FROM DISK=@p1 WITH REPLACE, RECOVERY`,resolved);await setGlobalSetting(`backup.restore.challenge.${id}`,{usedAt:Date.now()},'backup');data={restored:true,jobId:id,targetDatabase:target};break;}
case 'payments:create-transaction':{await ensureOperationalTables();const uid=Number(body.userId),amount=Number(body.amount);if(!uid||!Number.isFinite(amount)||amount<=0)return fail(res,400,'کاربر و مبلغ معتبر الزامی است.');await prisma.user.findUniqueOrThrow({where:{id:uid}});const rows=await prisma.$queryRawUnsafe(`INSERT INTO dbo.AdminPaymentTransaction(userId,amount,currency,gateway,authority,description,status) OUTPUT INSERTED.id VALUES(@p1,@p2,@p3,@p4,@p5,@p6,N'pending')`,uid,amount,String(body.currency||'IRR').slice(0,10),String(body.gateway||'').slice(0,50),String(body.authority||'').slice(0,200),String(body.description||'').slice(0,500));data={id:Number(rows[0].id),status:'pending'};break;}
case 'payments:set-status':{await ensureOperationalTables();const id=Number(body.transactionId),status=String(body.status||'').toLowerCase();if(!id||!['pending','paid','failed','cancelled','refunded'].includes(status))return fail(res,400,'شناسه تراکنش و وضعیت معتبر الزامی است.');const rows=await prisma.$queryRawUnsafe(`UPDATE dbo.AdminPaymentTransaction SET status=@p1,referenceNo=@p2,updatedAt=SYSDATETIME(),paidAt=CASE WHEN @p1=N'paid' THEN SYSDATETIME() ELSE paidAt END OUTPUT INSERTED.id,INSERTED.status WHERE id=@p3`,status,String(body.referenceNo||'').slice(0,200),id);if(!rows.length)return fail(res,404,'تراکنش پیدا نشد.');data={id:Number(rows[0].id),status:rows[0].status};break;}
case 'payments:list-transactions':{await ensureOperationalTables();data=await prisma.$queryRawUnsafe(`SELECT TOP 25 id,userId,amount,currency,gateway,referenceNo,status,description,createdAt,paidAt FROM dbo.AdminPaymentTransaction ORDER BY id DESC`);break;}
case 'market:health-check':case 'scalping:health-check':case 'infrastructure:health-check':case 'monitoring:health-check':{const check=async(name,url)=>{const started=Date.now();if(!url)return{name,status:'unknown',latencyMs:null,message:'نشانی سرویس تنظیم نشده است.'};const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),4000);try{const r=await fetch(url,{signal:controller.signal});return{name,status:r.ok?'healthy':'degraded',httpStatus:r.status,latencyMs:Date.now()-started};}catch(error){return{name,status:'down',latencyMs:Date.now()-started,message:String(error.message||error).slice(0,180)};}finally{clearTimeout(timer);}};const dbStarted=Date.now();let db;try{await prisma.$queryRawUnsafe('SELECT 1 AS ok');db={name:'database',status:'healthy',latencyMs:Date.now()-dbStarted};}catch(error){db={name:'database',status:'down',latencyMs:Date.now()-dbStarted,message:String(error.message||error).slice(0,180)};}const mem=process.memoryUsage();const model=process.env.GOOGLE_MODEL||'gemini-1.5-flash';const aiUrl=process.env.GEMINI_HEALTH_URL||(process.env.GOOGLE_API_KEY?'https://generativelanguage.googleapis.com/v1beta/models/'+encodeURIComponent(model)+'?key='+encodeURIComponent(process.env.GOOGLE_API_KEY):'');const services=await Promise.all([check('tsetmc',process.env.TSETMC_HEALTH_URL||'https://old.tsetmc.com/Loader.aspx?ParTree=111C1417'),check('codal',process.env.CODAL_HEALTH_URL||'https://codal.ir'),check('ai',aiUrl)]);const node={name:'node',status:'healthy',uptimeSeconds:Math.floor(process.uptime()),latencyMs:0};const all=[db,node,...services];data={status:all.some(x=>x.status==='down')?'down':all.some(x=>x.status==='degraded'||x.status==='unknown')?'degraded':'healthy',checkedAt:new Date().toISOString(),node,memory:{rss:mem.rss,heapUsed:mem.heapUsed,heapTotal:mem.heapTotal},services:all};break;}
case 'reports:snapshot':case 'dashboard:':data={ok:true};break;
default:return fail(res,400,'عملیات تعریف نشده است.');}
await audit(req,moduleKey,action,200,{targetId:body.userId??body.id??body.sessionId??body.apiKeyId??body.transactionId??body.jobId,success:true,backupId:body.jobId??body.backupId??null,commitSha:body.commitSha??null});return res.json({success:true,data});}catch(error){await audit(req,moduleKey,action,500,{targetId:body.userId??body.id??body.sessionId??body.apiKeyId??body.transactionId??body.jobId,success:false,error:String(error.message).slice(0,500),backupId:body.jobId??body.backupId??null,commitSha:body.commitSha??null});return fail(res,500,error.message||'خطای داخلی سرور.');}});
module.exports=router;
