'use strict';
const express=require('express');
const {prisma}=require('../config/prisma.cjs');
const authMiddleware=require('../middlewares/auth.middleware.cjs');
const {hasPermission}=require('../services/rbac.service.cjs');
const router=express.Router();
const uid=req=>Number(req.user?.id??req.user?.userId??0)||null;
async function admin(req,res,next){const id=uid(req);if(!id)return res.status(401).json({success:false,message:'احراز هویت الزامی است.'});try{if(!(await hasPermission(id,'admin.payments.manage')))return res.status(403).json({success:false,message:'دسترسی مدیریت پرداخت‌ها مجاز نیست.'});next();}catch(e){res.status(500).json({success:false,message:'بررسی دسترسی ناموفق بود.'});}}
async function ensure(){await prisma.$executeRawUnsafe(`IF OBJECT_ID(N'dbo.AdminPaymentTransaction',N'U') IS NULL BEGIN CREATE TABLE dbo.AdminPaymentTransaction(id BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,userId INT NOT NULL,amount DECIMAL(18,2) NOT NULL,currency NVARCHAR(10) NOT NULL DEFAULT N'IRR',gateway NVARCHAR(50) NULL,authority NVARCHAR(200) NULL,referenceNo NVARCHAR(200) NULL,status NVARCHAR(30) NOT NULL DEFAULT N'pending',description NVARCHAR(500) NULL,createdAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),updatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),paidAt DATETIME2 NULL); CREATE INDEX IX_AdminPaymentTransaction_userId ON dbo.AdminPaymentTransaction(userId); CREATE INDEX IX_AdminPaymentTransaction_status ON dbo.AdminPaymentTransaction(status); END;`);}
router.use(authMiddleware,admin);
router.get('/summary',async(req,res)=>{try{await ensure();const rows=await prisma.$queryRawUnsafe(`SELECT COUNT_BIG(*) total,COALESCE(SUM(CASE WHEN status=N'paid' THEN amount ELSE 0 END),0) paidAmount,COALESCE(SUM(CASE WHEN status=N'pending' THEN amount ELSE 0 END),0) pendingAmount,COALESCE(SUM(CASE WHEN status=N'refunded' THEN amount ELSE 0 END),0) refundedAmount,COALESCE(SUM(CASE WHEN status=N'failed' THEN amount ELSE 0 END),0) failedAmount,COALESCE(SUM(CASE WHEN status=N'paid' THEN 1 ELSE 0 END),0) paidCount,COALESCE(SUM(CASE WHEN status=N'pending' THEN 1 ELSE 0 END),0) pendingCount FROM dbo.AdminPaymentTransaction`);const r=rows[0]||{};return res.json({success:true,data:{total:Number(r.total||0),paidCount:Number(r.paidCount||0),pendingCount:Number(r.pendingCount||0),paidAmount:Number(r.paidAmount||0),pendingAmount:Number(r.pendingAmount||0),refundedAmount:Number(r.refundedAmount||0),failedAmount:Number(r.failedAmount||0)}});}catch(e){console.error('[AdminPayments] summary:',e);res.status(500).json({success:false,message:'دریافت خلاصه مالی ناموفق بود.'});}});
module.exports=router;
