'use strict';

const express = require('express');
const router = express.Router();
const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();
const authMiddleware = require('../middlewares/auth.middleware.cjs');

const MODULES = [
  'dashboard','users','subscriptions','analysis','market','scalping','ai','prompts','history','notifications',
  'monitoring','reports','security','settings','maintenance','updates','backup','payments','roles','audit','sessions','api','infrastructure'
];
const MODULE_TITLES = {
  dashboard:'داشبورد مدیریتی', users:'مدیریت کاربران', subscriptions:'اشتراک‌ها و اعتبار', analysis:'مدیریت تحلیل‌ها', market:'مدیریت بازار',
  scalping:'نوسان‌گیری', ai:'هوش مصنوعی', prompts:'پرامپت‌ها', history:'تاریخچه تحلیل‌ها', notifications:'اطلاع‌رسانی', monitoring:'مانیتورینگ سیستم',
  reports:'گزارش‌ها', security:'امنیت و دسترسی', settings:'تنظیمات سامانه', maintenance:'حالت تعمیرات', updates:'بروزرسانی و استقرار',
  backup:'پشتیبان‌گیری و بازیابی', payments:'پرداخت‌ها و تراکنش‌ها', roles:'نقش‌ها و مجوزها', audit:'گزارش Audit Log', sessions:'مدیریت نشست‌ها', api:'سرویس‌ها و APIها', infrastructure:'سلامت زیرساخت'
};
function uid(req) { return Number(req.user && (req.user.id || req.user.userId)); }
function fail(res,status,message,details){return res.status(status).json({success:false,message,...(details?{details}:{})});}
function validateModule(value){return typeof value==='string'&&MODULES.includes(value);}
async function ensureTables(){
 await prisma.$executeRawUnsafe(`
 IF OBJECT_ID(N'dbo.AdminControlRecord',N'U') IS NULL BEGIN CREATE TABLE dbo.AdminControlRecord(id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,moduleKey NVARCHAR(50) NOT NULL UNIQUE,title NVARCHAR(200) NOT NULL,enabled BIT NOT NULL CONSTRAINT DF_AdminControlRecord_enabled DEFAULT 1,configJson NVARCHAR(MAX) NULL,version INT NOT NULL CONSTRAINT DF_AdminControlRecord_version DEFAULT 1,updatedBy INT NULL,createdAt DATETIME2 NOT NULL CONSTRAINT DF_AdminControlRecord_createdAt DEFAULT SYSDATETIME(),updatedAt DATETIME2 NOT NULL CONSTRAINT DF_AdminControlRecord_updatedAt DEFAULT SYSDATETIME()); END;
 IF OBJECT_ID(N'dbo.AdminAuditLog',N'U') IS NULL BEGIN CREATE TABLE dbo.AdminAuditLog(id BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,adminUserId INT NULL,action NVARCHAR(100) NOT NULL,moduleKey NVARCHAR(50) NULL,targetId NVARCHAR(100) NULL,method NVARCHAR(10) NULL,path NVARCHAR(500) NULL,statusCode INT NULL,ipAddress NVARCHAR(100) NULL,userAgent NVARCHAR(500) NULL,detailsJson NVARCHAR(MAX) NULL,createdAt DATETIME2 NOT NULL CONSTRAINT DF_AdminAuditLog_createdAt DEFAULT SYSDATETIME()); CREATE INDEX IX_AdminAuditLog_createdAt ON dbo.AdminAuditLog(createdAt); CREATE INDEX IX_AdminAuditLog_moduleKey ON dbo.AdminAuditLog(moduleKey); END;`);
 for(const key of MODULES) await prisma.$executeRawUnsafe(`IF NOT EXISTS(SELECT 1 FROM dbo.AdminControlRecord WHERE moduleKey=@p1) INSERT INTO dbo.AdminControlRecord(moduleKey,title,enabled,configJson,version) VALUES(@p1,@p2,1,@p3,1);`,key,MODULE_TITLES[key],JSON.stringify({description:MODULE_TITLES[key],updatedFrom:'admin-control'}));
}
async function writeAudit(req,action,moduleKey,targetId,statusCode,details){try{await ensureTables();await prisma.$executeRawUnsafe(`INSERT INTO dbo.AdminAuditLog(adminUserId,action,moduleKey,targetId,method,path,statusCode,ipAddress,userAgent,detailsJson) VALUES(@p1,@p2,@p3,@p4,@p5,@p6,@p7,@p8,@p9,@p10)`,uid(req)||null,action,moduleKey||null,targetId==null?null:String(targetId),req.method,req.originalUrl,statusCode||null,req.ip||null,String(req.get('user-agent')||'').slice(0,500),details?JSON.stringify(details):null);}catch(e){console.error('[ADMIN-AUDIT]',e.message);}}
async function requireAdmin(req,res,next){const id=uid(req);if(!id)return fail(res,401,'احراز هویت الزامی است.');try{const user=await prisma.user.findUnique({where:{id},include:{Role:{include:{permissions:{include:{permission:true}}}}}});if(!user||!user.Role)return fail(res,403,'دسترسی مدیریت مجاز نیست.');const role=String(user.Role.name||'').toLowerCase();if(role!=='admin'&&role!=='superadmin'&&user.roleId!==1)return fail(res,403,'این عملیات فقط برای ادمین مجاز است.');req.adminUser=user;req.adminPermissions=(user.Role.permissions||[]).map(x=>x.permission&&x.permission.key).filter(Boolean);next();}catch(e){console.error('[ADMIN-CONTROL] auth:',e.message);return fail(res,500,'خطا در بررسی دسترسی ادمین.');}}
router.use(authMiddleware,requireAdmin);
router.get('/modules',async(req,res)=>{try{await ensureTables();const rows=await prisma.$queryRawUnsafe(`SELECT id,moduleKey,title,enabled,configJson,version,updatedBy,createdAt,updatedAt FROM dbo.AdminControlRecord ORDER BY id`);return res.json({success:true,data:rows.map(r=>({...r,config:r.configJson?JSON.parse(r.configJson):{}}))});}catch(e){console.error('[ADMIN-CONTROL] modules:',e.message);return fail(res,500,'خطا در دریافت تنظیمات پنل مدیریت.');}});
router.get('/modules/:moduleKey',async(req,res)=>{const key=req.params.moduleKey;if(!validateModule(key))return fail(res,400,'ماژول مدیریت نامعتبر است.');try{await ensureTables();const rows=await prisma.$queryRawUnsafe(`SELECT TOP 1 id,moduleKey,title,enabled,configJson,version,updatedBy,createdAt,updatedAt FROM dbo.AdminControlRecord WHERE moduleKey=@p1`,key);if(!rows.length)return fail(res,404,'ماژول یافت نشد.');const r=rows[0];return res.json({success:true,data:{...r,config:r.configJson?JSON.parse(r.configJson):{}}});}catch(e){console.error('[ADMIN-CONTROL] get:',e.message);return fail(res,500,'خطا در دریافت ماژول.');}});
router.put('/modules/:moduleKey',async(req,res)=>{const key=req.params.moduleKey,body=req.body||{};if(!validateModule(key))return fail(res,400,'ماژول مدیریت نامعتبر است.');if(typeof body.enabled!=='boolean')return fail(res,400,'فیلد فعال/غیرفعال باید از نوع boolean باشد.');if(body.config!==undefined&&(body.config===null||typeof body.config!=='object'||Array.isArray(body.config)))return fail(res,400,'تنظیمات ماژول باید یک شیء JSON معتبر باشد.');try{await ensureTables();const old=await prisma.$queryRawUnsafe(`SELECT TOP 1 enabled,configJson,version FROM dbo.AdminControlRecord WHERE moduleKey=@p1`,key);if(!old.length)return fail(res,404,'ماژول یافت نشد.');const config=body.config===undefined?(old[0].configJson?JSON.parse(old[0].configJson):{}):body.config;await prisma.$executeRawUnsafe(`UPDATE dbo.AdminControlRecord SET enabled=@p1,configJson=@p2,version=version+1,updatedBy=@p3,updatedAt=SYSDATETIME() WHERE moduleKey=@p4`,body.enabled,JSON.stringify(config),uid(req),key);await writeAudit(req,'UPDATE_MODULE',key,null,200,{enabled:body.enabled,config});return res.json({success:true,message:'تنظیمات ماژول با موفقیت ذخیره شد.',data:{moduleKey:key,enabled:body.enabled,config}});}catch(e){console.error('[ADMIN-CONTROL] update:',e.message);await writeAudit(req,'UPDATE_MODULE',key,null,500,{error:e.message});return fail(res,500,'ذخیره تنظیمات ماژول ناموفق بود.');}});
router.get('/audit',async(req,res)=>{try{await ensureTables();const limit=Math.min(Math.max(Number(req.query.limit)||50,1),200);const offset=Math.max(Number(req.query.offset)||0,0);const moduleKey=String(req.query.moduleKey||'').trim();const action=String(req.query.action||'').trim();const status=String(req.query.status||'').trim();const adminUserId=Number(req.query.adminUserId)||0;const from=req.query.from?new Date(String(req.query.from)):null;const to=req.query.to?new Date(String(req.query.to)):null;const params=[];const where=[];if(moduleKey){params.push(moduleKey);where.push(`a.moduleKey=@p${params.length}`);}if(action){params.push(`%${action}%`);where.push(`a.action LIKE @p${params.length}`);}if(status){const n=Number(status);if(Number.isFinite(n)){params.push(n);where.push(`a.statusCode=@p${params.length}`);}}if(adminUserId){params.push(adminUserId);where.push(`a.adminUserId=@p${params.length}`);}if(from&&!Number.isNaN(from.getTime())){params.push(from);where.push(`a.createdAt>=@p${params.length}`);}if(to&&!Number.isNaN(to.getTime())){params.push(to);where.push(`a.createdAt<=@p${params.length}`);}params.push(offset,limit);const oidx=params.length-1,lidx=params.length;const sql=`SELECT a.id,a.adminUserId,u.username,u.email,a.action,a.moduleKey,a.targetId,a.method,a.path,a.statusCode,a.ipAddress,a.detailsJson,a.createdAt FROM dbo.AdminAuditLog a LEFT JOIN dbo.[User] u ON u.id=a.adminUserId ${where.length?`WHERE ${where.join(' AND ')}`:''} ORDER BY a.id DESC OFFSET @p${oidx} ROWS FETCH NEXT @p${lidx} ROWS ONLY`;const rows=await prisma.$queryRawUnsafe(sql,...params);const countParams=params.slice(0,-2);const countSql=`SELECT COUNT_BIG(*) AS total FROM dbo.AdminAuditLog a ${where.length?`WHERE ${where.join(' AND ')}`:''}`;const countRows=await prisma.$queryRawUnsafe(countSql,...countParams);return res.json({success:true,data:rows.map(r=>({...r,details:r.detailsJson?JSON.parse(r.detailsJson):null})),pagination:{limit,offset,total:Number(countRows[0]?.total||0)}});}catch(e){console.error('[ADMIN-CONTROL] audit:',e.message);return fail(res,500,'خطا در دریافت Audit Log.');}});
router.get('/summary',async(req,res)=>{try{await ensureTables();const [users,active,analyses,apiKeys,notifications,sessions,audits]=await Promise.all([prisma.user.count({where:{isDeleted:false}}),prisma.user.count({where:{isDeleted:false,isActive:true}}),prisma.analysisHistory.count(),prisma.apiKey.count({where:{isRevoked:false}}),prisma.notification.count(),prisma.session.count(),prisma.$queryRawUnsafe(`SELECT COUNT_BIG(*) AS total FROM dbo.AdminAuditLog`)]);return res.json({success:true,data:{users,activeUsers:active,analyses,apiKeys,notifications,sessions,auditEvents:Number(audits[0].total||0),moduleCount:MODULES.length}});}catch(e){console.error('[ADMIN-CONTROL] summary:',e.message);return fail(res,500,'خطا در دریافت آمار مدیریتی.');}});
router.get('/reports/summary',async(req,res)=>{try{await ensureTables();const [users,activeUsers,analyses,notifications,sessions,apiKeys,marketHistory,marketDaily,marketSummary,auditEvents]=await Promise.all([prisma.user.count({where:{isDeleted:false}}),prisma.user.count({where:{isDeleted:false,isActive:true}}),prisma.analysisHistory.count(),prisma.notification.count(),prisma.session.count(),prisma.apiKey.count({where:{isRevoked:false}}),prisma.marketHistory.count(),prisma.marketDaily.count(),prisma.marketSummary.count(),prisma.$queryRawUnsafe(`SELECT COUNT_BIG(*) AS total FROM dbo.AdminAuditLog`)]);let payments={transactionCount:0,paidCount:0,pendingCount:0,paidIrr:0,paidIrt:0};try{const rows=await prisma.$queryRawUnsafe(`SELECT COUNT_BIG(*) AS transactionCount,SUM(CASE WHEN status='paid' THEN 1 ELSE 0 END) AS paidCount,SUM(CASE WHEN status='pending' THEN 1 ELSE 0 END) AS pendingCount,SUM(CASE WHEN status='paid' AND currency='IRR' THEN amount ELSE 0 END) AS paidIrr,SUM(CASE WHEN status='paid' AND currency='IRT' THEN amount ELSE 0 END) AS paidIrt FROM dbo.AdminPaymentTransaction`);const r=rows[0]||{};payments={transactionCount:Number(r.transactionCount||0),paidCount:Number(r.paidCount||0),pendingCount:Number(r.pendingCount||0),paidIrr:Number(r.paidIrr||0),paidIrt:Number(r.paidIrt||0)};}catch(_){ }return res.json({success:true,data:{generatedAt:new Date().toISOString(),users:{total:users,active:activeUsers,inactive:Math.max(0,users-activeUsers)},analyses:{total:analyses},notifications:{total:notifications},sessions:{total:sessions},apiKeys:{active:apiKeys},market:{history:marketHistory,daily:marketDaily,summaries:marketSummary},audit:{events:Number(auditEvents[0]?.total||0)},payments}});}catch(e){console.error('[ADMIN-CONTROL] reports:',e.message);return fail(res,500,'خطا در تولید گزارش مدیریتی.');}});
router.get('/reports/trends',async(req,res)=>{try{const rawDays=Number(req.query.days);const days=rawDays===30?30:7;const start=new Date();start.setHours(0,0,0,0);start.setDate(start.getDate()-(days-1));const end=new Date(start);end.setDate(end.getDate()+days);const [users,analyses,sessions]=await Promise.all([
 prisma.$queryRawUnsafe(`SELECT CAST(createdAt AS date) AS day,COUNT_BIG(*) AS value FROM dbo.[User] WHERE isDeleted=0 AND createdAt>=@p1 AND createdAt<@p2 GROUP BY CAST(createdAt AS date) ORDER BY day`,start,end),
 prisma.$queryRawUnsafe(`SELECT CAST(createdAt AS date) AS day,COUNT_BIG(*) AS value FROM dbo.AnalysisHistory WHERE createdAt>=@p1 AND createdAt<@p2 GROUP BY CAST(createdAt AS date) ORDER BY day`,start,end),
 prisma.$queryRawUnsafe(`SELECT CAST(createdAt AS date) AS day,COUNT_BIG(*) AS value FROM dbo.Session WHERE createdAt>=@p1 AND createdAt<@p2 GROUP BY CAST(createdAt AS date) ORDER BY day`,start,end)
 ]);let payments=[];try{payments=await prisma.$queryRawUnsafe(`SELECT CAST(COALESCE(paidAt,createdAt) AS date) AS day,currency,SUM(CASE WHEN status='paid' THEN amount ELSE 0 END) AS amount,COUNT_BIG(CASE WHEN status='paid' THEN 1 END) AS count FROM dbo.AdminPaymentTransaction WHERE status='paid' AND COALESCE(paidAt,createdAt)>=@p1 AND COALESCE(paidAt,createdAt)<@p2 GROUP BY CAST(COALESCE(paidAt,createdAt) AS date),currency ORDER BY day`,start,end);}catch(_){ }
 const key=d=>{const x=new Date(d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`;};const empty=Array.from({length:days},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);return {day:key(d),label:d.toLocaleDateString('fa-IR',{month:'2-digit',day:'2-digit'}),users:0,analyses:0,sessions:0,paidIrr:0,paidIrt:0,paidIrrCount:0,paidIrtCount:0};});const map=new Map(empty.map(x=>[x.day,x]));for(const row of users){const x=map.get(key(row.day));if(x)x.users=Number(row.value||0);}for(const row of analyses){const x=map.get(key(row.day));if(x)x.analyses=Number(row.value||0);}for(const row of sessions){const x=map.get(key(row.day));if(x)x.sessions=Number(row.value||0);}for(const row of payments){const x=map.get(key(row.day));if(!x)continue;const amount=Number(row.amount||0),count=Number(row.count||0);if(String(row.currency||'').toUpperCase()==='IRT'){x.paidIrt=amount;x.paidIrtCount=count;}else if(String(row.currency||'').toUpperCase()==='IRR'){x.paidIrr=amount;x.paidIrrCount=count;}}
 return res.json({success:true,data:{days,start:start.toISOString(),end:end.toISOString(),series:empty}});}catch(e){console.error('[ADMIN-CONTROL] report trends:',e.message);return fail(res,500,'خطا در تولید روند گزارش مدیریتی.');}});
module.exports=router;
