'use strict';
const express=require('express');
const {prisma}=require('../config/prisma.cjs');
const authMiddleware=require('../middlewares/auth.middleware.cjs');
const {hasPermission}=require('../services/rbac.service.cjs');
const router=express.Router();
const uid=req=>Number(req.user?.id??req.user?.userId??0)||null;
async function admin(req,res,next){const id=uid(req);if(!id)return res.status(401).json({success:false,message:'احراز هویت الزامی است.'});try{if(!(await hasPermission(id,'admin.analysis.manage')))return res.status(403).json({success:false,message:'دسترسی مدیریت تحلیل‌ها مجاز نیست.'});next();}catch(e){console.error('[AdminAnalyses] permission:',e.message);res.status(500).json({success:false,message:'بررسی دسترسی ناموفق بود.'});}}
function parseResult(raw){if(!raw)return {};try{const x=JSON.parse(raw);return x&&typeof x==='object'&&!Array.isArray(x)?x:{}}catch{return {}}}
function first(o,keys){for(const k of keys)if(o[k]!==undefined&&o[k]!==null&&o[k]!=='')return o[k];return undefined}
router.use(authMiddleware,admin);
router.get('/',async(req,res)=>{try{const page=Math.max(1,Number(req.query.page)||1),limit=Math.min(100,Math.max(1,Number(req.query.limit)||20)),search=String(req.query.search||'').trim(),symbol=String(req.query.symbol||'').trim(),status=String(req.query.status||'').trim(),from=String(req.query.from||'').trim(),to=String(req.query.to||'').trim();const where={};if(symbol)where.stock={contains:symbol};if(from){const d=new Date(from);if(!Number.isNaN(d.getTime()))where.createdAt={...(where.createdAt||{}),gte:d}}if(to){const d=new Date(to);if(!Number.isNaN(d.getTime())){d.setHours(23,59,59,999);where.createdAt={...(where.createdAt||{}),lte:d}}}if(search)where.user={OR:[{username:{contains:search}},{email:{contains:search}}]};const [rows,total,all]=await Promise.all([prisma.analysisHistory.findMany({where,orderBy:{createdAt:'desc'},skip:(page-1)*limit,take:limit,select:{id:true,userId:true,stock:true,resultJson:true,createdAt:true,user:{select:{username:true,email:true,name:true}}}}),prisma.analysisHistory.count({where}),prisma.analysisHistory.count()]);let items=rows.map(r=>{const x=parseResult(r.resultJson),s=String(first(x,['status','analysisStatus','state'])??'completed').toLowerCase(),c=Number(first(x,['credits','creditCost','consumedCredits','analysisCost'])??1);return {id:r.id,userId:r.userId,username:r.user?.username||'—',email:r.user?.email||null,name:r.user?.name||null,symbol:r.stock||'—',createdAt:r.createdAt,status:s==='failed'?'failed':s==='pending'?'pending':'completed',statusLabel:s==='failed'?'ناموفق':s==='pending'?'در انتظار':'تکمیل‌شده',analysisType:String(first(x,['analysisType','type','featureKey'])??'تحلیل'),credits:Number.isFinite(c)&&c>=0?c:1,hasResult:!!r.resultJson,result:r.resultJson||null}});if(status)items=items.filter(x=>x.status===status);return res.json({success:true,data:{items,pagination:{page,limit,total,totalPages:Math.ceil(total/limit)},summary:{total:all,shown:items.length,completed:items.filter(x=>x.status==='completed').length,failed:items.filter(x=>x.status==='failed').length,credits:items.reduce((n,x)=>n+x.credits,0)}}});}catch(e){console.error('[AdminAnalyses] list:',e);res.status(500).json({success:false,message:'دریافت فهرست تحلیل‌ها ناموفق بود.'});}});
module.exports=router;
