'use strict';
const express=require('express');const router=express.Router();const auth=require('../middlewares/auth.middleware.cjs');const pm=require('../config/prisma.cjs');const prisma=pm.prisma||pm;const brs=require('../services/brs.service.cjs');
function uid(req){const n=Number(req.user&&(req.user.id??req.user.userId));return Number.isInteger(n)&&n>0?n:null}
async function read(id){const u=await prisma.user.findUnique({where:{id},select:{marketSummary:true}});let root={};try{root=JSON.parse(u?.marketSummary||'{}')}catch(e){}return {root,paper:Array.isArray(root.paperTrading)?root.paperTrading:[]}}
async function write(id,s){s.root.paperTrading=s.paper;await prisma.user.update({where:{id},data:{marketSummary:JSON.stringify(s.root)}})}
function pos(v){const n=Number(v);return Number.isFinite(n)&&n>0?n:null}
async function quote(symbol){try{const r=await brs.getSymbolData(symbol),d=r?.data||{},m=r?._meta||{},p=pos(d.lastPrice??d.pl??d.pDrCotVal??d.closingPrice??d.pc);return {price:p,status:String(m.source||'').toLowerCase()==='live'?'LIVE':m.source?'CACHED':'UNAVAILABLE',source:m.source||null,fetchedAt:m.fetchedAt||null}}catch(e){return {price:null,status:'UNAVAILABLE',source:null,fetchedAt:null}}}
router.get('/',auth,async(req,res)=>{try{const id=uid(req);if(!id)return res.status(401).json({success:false,message:'احراز هویت الزامی است.'});const s=await read(id);const orders=await Promise.all(s.paper.map(async o=>({...o,quote:await quote(o.symbol)})));return res.json({success:true,data:{orders},meta:{status:orders.some(o=>o.quote.status==='LIVE')?'LIVE':orders.some(o=>o.quote.status==='CACHED')?'CACHED':'UNAVAILABLE',source:'BRS Market API',fetchedAt:new Date().toISOString(),stale:orders.every(o=>o.quote.status!=='LIVE')}})}catch(e){res.status(500).json({success:false,message:e.message})}});
router.post('/orders',auth,async(req,res)=>{try{const id=uid(req);if(!id)return res.status(401).json({success:false,message:'احراز هویت الزامی است.'});const symbol=String(req.body?.symbol||'').trim().toUpperCase(),side=String(req.body?.side||'').toUpperCase(),quantity=pos(req.body?.quantity),price=pos(req.body?.price);if(!symbol||!['BUY','SELL'].includes(side)||!quantity||!price)return res.status(400).json({success:false,message:'نماد، جهت، تعداد و قیمت معتبر الزامی است.'});const s=await read(id);const order={id:'paper-'+Date.now()+'-'+Math.random().toString(36).slice(2,7),symbol,side,quantity,price,status:'FILLED',executedAt:new Date().toISOString(),source:'PAPER'};s.paper.push(order);await write(id,s);res.status(201).json({success:true,data:order,deterministic:true})}catch(e){res.status(500).json({success:false,message:e.message})}});
router.delete('/orders/:id',auth,async(req,res)=>{try{const id=uid(req);if(!id)return res.status(401).json({success:false});const s=await read(id),before=s.paper.length;s.paper=s.paper.filter(o=>o.id!==req.params.id);if(s.paper.length===before)return res.status(404).json({success:false,message:'سفارش پیدا نشد.'});await write(id,s);res.json({success:true})}catch(e){res.status(500).json({success:false,message:e.message})}});module.exports=router;