'use strict';

const express = require('express');
const fs = require('fs');
const path = require('path');
const os = require('os');
const crypto = require('crypto');
const { spawnSync } = require('child_process');
const authMiddleware = require('../middlewares/auth.middleware.cjs');
const { hasPermission } = require('../services/rbac.service.cjs');

const router = express.Router();
const MAX_UPLOAD = 25 * 1024 * 1024;
const PLUGIN_ROOT = path.resolve(process.env.ADMIN_PLUGIN_DIR || path.join(__dirname, '..', 'plugins'));
const ID_RE = /^[a-z0-9][a-z0-9._-]{1,63}$/i;
const ALLOWED_SINGLE = new Set(['.js', '.cjs', '.json']);

function uid(req){return Number(req.user?.id ?? req.user?.userId ?? 0)||null;}
function fail(res,status,message){return res.status(status).json({success:false,message});}
function inside(root,target){const r=path.resolve(root),t=path.resolve(target);return t===r||t.startsWith(r+path.sep);}
function cleanName(name){return path.basename(String(name||'upload.bin')).replace(/[^a-zA-Z0-9._-]/g,'_');}
function audit(req,action,statusCode,details){return Promise.resolve().then(async()=>{try{const {prisma}=require('../config/prisma.cjs');await prisma.$executeRawUnsafe(`IF OBJECT_ID(N'dbo.AdminAuditLog',N'U') IS NOT NULL INSERT INTO dbo.AdminAuditLog(adminUserId,action,moduleKey,targetId,method,path,statusCode,ipAddress,userAgent,detailsJson) VALUES(@p1,@p2,N'plugins',@p3,@p4,@p5,@p6,@p7,@p8,@p9)`,uid(req),action,details?.id||null,req.method,req.originalUrl,statusCode,req.ip||null,String(req.get('user-agent')||'').slice(0,500),JSON.stringify(details||{}));}catch(_){}});}
async function allowed(req){return !!(uid(req)&&await hasPermission(uid(req),'admin.plugins.manage'));}
function parseMultipart(req){return new Promise((resolve,reject)=>{const type=String(req.headers['content-type']||'');const m=type.match(/boundary=(?:"([^"]+)"|([^;]+))/i);if(!m)return reject(new Error('درخواست multipart معتبر نیست.'));const boundary=Buffer.from('--'+(m[1]||m[2]));const chunks=[];let size=0;req.on('data',chunk=>{size+=chunk.length;if(size>MAX_UPLOAD+1024*1024){reject(new Error('حجم فایل بیش از حد مجاز است.'));req.destroy();return;}chunks.push(chunk);});req.on('error',reject);req.on('end',()=>{try{const body=Buffer.concat(chunks);const parts=[];let pos=0;while(true){const start=body.indexOf(boundary,pos);if(start<0)break;const next=body.indexOf(boundary,start+boundary.length);if(next<0)break;let part=body.slice(start+boundary.length,next);if(part.subarray(0,2).toString()==='--')break;if(part.subarray(0,2).toString()==='\r\n')part=part.subarray(2);const sep=part.indexOf(Buffer.from('\r\n\r\n'));if(sep<0){pos=next;continue;}const headers=part.subarray(0,sep).toString('utf8');let data=part.subarray(sep+4);if(data.subarray(-2).toString()==='\r\n')data=data.subarray(0,-2);const cd=headers.match(/Content-Disposition:[^\r\n]*name="([^"]+)"(?:;\s*filename="([^"]*)")?/i);if(cd)parts.push({name:cd[1],filename:cd[2]||'',data});pos=next;}const file=parts.find(x=>x.name==='file'&&x.filename);if(!file)throw new Error('فایل افزونه انتخاب نشده است.');if(file.data.length>MAX_UPLOAD)throw new Error('حجم فایل بیش از ۲۵ مگابایت مجاز نیست.');resolve(file);}catch(e){reject(e);}});});}
function readManifest(dir){const p=path.join(dir,'manifest.json');if(!inside(dir,p)||!fs.existsSync(p))throw new Error('فایل manifest.json افزونه یافت نشد.');let m;try{m=JSON.parse(fs.readFileSync(p,'utf8'));}catch(_){throw new Error('manifest.json معتبر نیست.');}if(!m||typeof m!=='object'||!ID_RE.test(String(m.id||'')))throw new Error('شناسه افزونه نامعتبر است.');if(!/^\d+\.\d+\.\d+(?:[-+].*)?$/.test(String(m.version||'')))throw new Error('نسخه افزونه باید مانند 1.0.0 باشد.');return {id:String(m.id),name:String(m.name||m.id).slice(0,120),version:String(m.version),description:String(m.description||'').slice(0,500),main:m.main?String(m.main).slice(0,200):null};}
function validateTree(root){const walk=(dir)=>{for(const e of fs.readdirSync(dir,{withFileTypes:true})){const p=path.join(dir,e.name);if(!inside(root,p))throw new Error('مسیر غیرمجاز داخل افزونه شناسایی شد.');if(e.isSymbolicLink())throw new Error('لینک نمادین داخل افزونه مجاز نیست.');if(e.isDirectory())walk(p);}};walk(root);}
function extractZip(zipPath,stage){if(process.platform==='win32'){const esc=s=>String(s).replace(/'/g,"''");const r=spawnSync('powershell.exe',['-NoProfile','-NonInteractive','-Command',`Expand-Archive -LiteralPath '${esc(zipPath)}' -DestinationPath '${esc(stage)}' -Force`],{encoding:'utf8',timeout:60000});if(r.status!==0)throw new Error(String(r.stderr||r.stdout||'استخراج ZIP ناموفق بود.').trim().slice(0,500));}else{const r=spawnSync('unzip',['-q','-o',zipPath,'-d',stage],{encoding:'utf8',timeout:60000});if(r.status!==0)throw new Error(String(r.stderr||'استخراج ZIP ناموفق بود.').trim().slice(0,500));}}

router.use(authMiddleware,async(req,res,next)=>{if(!(await allowed(req)))return fail(res,403,'مجوز مدیریت افزونه‌ها را ندارید.');next();});

router.get('/',async(_req,res)=>{try{fs.mkdirSync(PLUGIN_ROOT,{recursive:true});const items=[];for(const name of fs.readdirSync(PLUGIN_ROOT,{withFileTypes:true})){if(!name.isDirectory())continue;const dir=path.join(PLUGIN_ROOT,name.name);try{const manifest=readManifest(dir);const stat=fs.statSync(dir);items.push({...manifest,installedAt:stat.birthtime.toISOString(),updatedAt:stat.mtime.toISOString(),status:'installed'});}catch(_){items.push({id:name.name,name:name.name,version:'نامعتبر',description:'manifest.json قابل خواندن نیست.',installedAt:fs.statSync(dir).birthtime.toISOString(),updatedAt:fs.statSync(dir).mtime.toISOString(),status:'invalid'});}}items.sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt)));return res.json({success:true,data:items});}catch(e){return fail(res,500,'دریافت فهرست افزونه‌ها ناموفق بود.');}});

router.post('/install',async(req,res)=>{let temp='';try{const file=await parseMultipart(req);const ext=path.extname(file.filename).toLowerCase();if(ext!=='.zip'&&!ALLOWED_SINGLE.has(ext))return fail(res,400,'فرمت افزونه مجاز نیست. فقط ZIP، JS، CJS یا JSON قابل نصب است.');fs.mkdirSync(PLUGIN_ROOT,{recursive:true});temp=fs.mkdtempSync(path.join(os.tmpdir(),'roniya-plugin-'));const source=path.join(temp,cleanName(file.filename));fs.writeFileSync(source,file.data,{flag:'wx'});const stage=path.join(temp,'stage');fs.mkdirSync(stage);if(ext==='.zip'){extractZip(source,stage);}else{if(ext==='.json'){fs.copyFileSync(source,path.join(stage,'manifest.json'));}else{fs.copyFileSync(source,path.join(stage,path.basename(source)));fs.writeFileSync(path.join(stage,'manifest.json'),JSON.stringify({id:path.basename(source,ext).toLowerCase().replace(/[^a-z0-9._-]/g,'-'),name:path.basename(source,ext),version:'1.0.0',description:'افزونه تک‌فایلی',main:path.basename(source)},null,2));}}validateTree(stage);let root=stage;const entries=fs.readdirSync(stage,{withFileTypes:true});if(!fs.existsSync(path.join(stage,'manifest.json'))&&entries.length===1&&entries[0].isDirectory()&&fs.existsSync(path.join(stage,entries[0].name,'manifest.json')))root=path.join(stage,entries[0].name);const manifest=readManifest(root);const destination=path.join(PLUGIN_ROOT,manifest.id);if(!inside(PLUGIN_ROOT,destination))throw new Error('مسیر مقصد افزونه نامعتبر است.');if(fs.existsSync(destination))fs.rmSync(destination,{recursive:true,force:true});fs.cpSync(root,destination,{recursive:true});return res.status(201).json({success:true,message:`افزونه «${manifest.name}» با موفقیت نصب شد.`,data:manifest});}catch(e){await audit(req,'INSTALL_PLUGIN',400,{error:e.message});return fail(res,400,e.message||'نصب افزونه ناموفق بود.');}finally{if(temp){try{fs.rmSync(temp,{recursive:true,force:true});}catch(_){}}}});

module.exports=router;
