'use strict';
const express=require('express');const router=express.Router();const authMiddleware=require('../middlewares/auth.middleware.cjs');const prismaModule=require('../config/prisma.cjs');const prisma=prismaModule.prisma||prismaModule;
const uid=req=>{const n=Number(req.user&&(req.user.id??req.user.userId));return Number.isInteger(n)&&n>0?n:null};
function clean(x){if(!x||typeof x!=='object')return null;const id=String(x.id??''),symbol=String(x.symbol??'').trim().toUpperCase(),side=String(x.side??'BUY').toUpperCase(),tradeDate=String(x.tradeDate??'').trim(),quantity=Number(x.quantity),entryPrice=Number(x.entryPrice),exitPrice=x.exitPrice==null||x.exitPrice===''?null:Number(x.exitPrice);if(!id||!symbol||!tradeDate||!['BUY','SELL'].includes(side)||!Number.isFinite(quantity)||quantity<=0||!Number.isFinite(entryPrice)||entryPrice<=0)return null;const pnl=exitPrice!=null&&Number.isFinite(exitPrice)?(exitPrice-entryPrice)*quantity*(side==='BUY'?1:-1):null;return{id,symbol,side,tradeDate,quantity,entryPrice,exitPrice:Number.isFinite(exitPrice)?exitPrice:null,pnl,setup:String(x.setup??'').trim(),emotion:String(x.emotion??'').trim(),thesis:String(x.thesis??'').trim(),lesson:String(x.lesson??'').trim(),notes:String(x.notes??'').trim(),createdAt:String(x.createdAt??new Date().toISOString()),updatedAt:String(x.updatedAt??new Date().toISOString())}}
async function read(id){const u=await prisma.user.findUnique({where:{id},select:{marketSummary:true}});let root={};try{root=u?.marketSummary?JSON.parse(u.marketSummary):{}}catch(_){root={}}return{root:root&&typeof root==='object'&&!Array.isArray(root)?root:{},entries:Array.isArray(root?.traderJournal)?root.traderJournal.map(clean).filter(Boolean):[]}}
async function write(id,s){s.root.traderJournal=s.entries;await prisma.user.update({where:{id},data:{marketSummary:JSON.stringify(s.root)}})}
router.get('/',authMiddleware,async(req,res)=>{try{const id=uid(req);if(!id)return res.status(401).json({success:false,message:'کاربر احراز هویت نشده است.'});const s=await read(id);res.json({success:true,data:s.entries,total:s.entries.length})}catch(e){res.status(500).json({success:false,message:'خطا در دریافت دفترچه معاملات.',error:e.message})}});
router.post('/',authMiddleware,async(req,res)=>{try{const id=uid(req);if(!id)return res.status(401).json({success:false,message:'کاربر احراز هویت نشده است.'});const now=new Date().toISOString();const e=clean({...req.body,id:`${Date.now()}-${Math.random().toString(36).slice(2,8)}`,createdAt:now,updatedAt:now});if(!e)return res.status(400).json({success:false,message:'اطلاعات معامله نامعتبر است.'});const s=await read(id);s.entries.unshift(e);await write(id,s);res.status(201).json({success:true,data:e})}catch(e){res.status(500).json({success:false,message:'ثبت رکورد ناموفق بود.',error:e.message})}});
router.put('/:entryId',authMiddleware,async(req,res)=>{try{const id=uid(req);if(!id)return res.status(401).json({success:false,message:'کاربر احراز هویت نشده است.'});const s=await read(id),i=s.entries.findIndex(x=>x.id===String(req.params.entryId));if(i<0)return res.status(404).json({success:false,message:'رکورد یافت نشد.'});const e=clean({...s.entries[i],...req.body,id:s.entries[i].id,updatedAt:new Date().toISOString()});if(!e)return res.status(400).json({success:false,message:'اطلاعات نامعتبر است.'});s.entries[i]=e;await write(id,s);res.json({success:true,data:e})}catch(e){res.status(500).json({success:false,message:'ویرایش ناموفق بود.',error:e.message})}});
router.delete('/:entryId',authMiddleware,async(req,res)=>{try{const id=uid(req);if(!id)return res.status(401).json({success:false,message:'کاربر احراز هویت نشده است.'});const s=await read(id),before=s.entries.length;s.entries=s.entries.filter(x=>x.id!==String(req.params.entryId));if(before===s.entries.length)return res.status(404).json({success:false,message:'رکورد یافت نشد.'});await write(id,s);res.json({success:true,data:{id:String(req.params.entryId)}})}catch(e){res.status(500).json({success:false,message:'حذف ناموفق بود.',error:e.message})}});
module.exports=router;