module.exports.PERMISSIONS = {
  USER_READ: "USER_READ",
  USER_CREATE: "USER_CREATE",
  USER_UPDATE: "USER_UPDATE",
  USER_DELETE: "USER_DELETE",

  APIKEY_MANAGE: "APIKEY_MANAGE",
  CONFIG_EDIT: "CONFIG_EDIT",
};
