import React, { useCallback, useEffect, useMemo, useState } from 'react';
import * as adminDashboardService from '../services/adminDashboardService';
import * as adminControlService from '../services/adminControlService';
import * as adminOperationsService from '../services/adminOperationsService';
import * as adminActionsService from '../services/adminActionsService';
import type { AdminDashboardData } from '../services/adminDashboardService';
import UserManagementLegacy from './UserManagementRBAC';
import AdminSubscriptionsPanel from './AdminSubscriptionsPanel';
import AdminAnalysesPanel from './AdminAnalysesPanel';
import AdminNotificationsPanel from './AdminNotificationsPanel';
import OperationalPanels from './AdminOperationalPanels';
import AdminAuditPanel from './AdminAuditPanel';
import AdminApiKeysPanel from './AdminApiKeysPanel';
import AdminMonitoringPanel from './AdminMonitoringPanel';
import AdminReportsPanel from './AdminReportsPanel';
import AdminInfrastructurePanel from './AdminInfrastructurePanel';
import AdminMarketPanel from './AdminMarketPanel';
import { ChartBarIcon, UserGroupIcon, BriefcaseIcon, Cog6ToothIcon, BellIcon, ShieldCheckIcon, PresentationChartLineIcon, ClipboardDocumentIcon, GlobeAltIcon, MagnifyingGlassIcon, LockClosedIcon } from './Icons';
interface AdminPanelProps { isOnline: boolean; onMessageUpdate: () => void; onlineCount: number; }
type AdminSection = adminControlService.AdminModuleKey;
interface ModuleItem { id: AdminSection; title: string; description: string; icon: React.ReactNode; }
const modules: ModuleItem[] = [
 {id:'dashboard',title:'داشبورد مدیریتی',description:'شاخص‌ها و وضعیت کلی سامانه',icon:<ChartBarIcon/>},{id:'users',title:'مدیریت کاربران',description:'کاربران، حساب‌ها و دسترسی‌ها',icon:<UserGroupIcon/>},{id:'subscriptions',title:'اشتراک‌ها و اعتبار',description:'اعتبار، سقف تحلیل و تمدید',icon:<BriefcaseIcon/>},{id:'analysis',title:'مدیریت تحلیل‌ها',description:'کنترل تحلیل و مصرف منابع',icon:<MagnifyingGlassIcon/>},{id:'market',title:'مدیریت بازار',description:'داده‌ها و خلاصه بازار',icon:<GlobeAltIcon/>},{id:'scalping',title:'نوسان‌گیری',description:'کنترل موتور فرصت‌های نوسان‌گیری',icon:<ChartBarIcon/>},{id:'ai',title:'هوش مصنوعی',description:'مدل‌ها و تنظیمات سرویس AI',icon:<PresentationChartLineIcon/>},{id:'prompts',title:'مدیریت پرامپت‌ها',description:'پرامپت‌ها و نسخه‌بندی',icon:<ClipboardDocumentIcon/>},{id:'history',title:'تاریخچه تحلیل‌ها',description:'سوابق و سیاست نگهداری',icon:<ClipboardDocumentIcon/>},{id:'notifications',title:'اطلاع‌رسانی',description:'اعلان‌ها و پیام‌های سیستمی',icon:<BellIcon/>},{id:'monitoring',title:'مانیتورینگ سیستم',description:'پایش سرویس و API',icon:<PresentationChartLineIcon/>},{id:'reports',title:'گزارش‌ها',description:'گزارش‌های مدیریتی و آماری',icon:<ChartBarIcon/>},{id:'security',title:'امنیت و دسترسی',description:'سیاست‌های امنیتی و کنترل دسترسی',icon:<ShieldCheckIcon/>},{id:'settings',title:'تنظیمات سامانه',description:'پیکربندی عمومی نرم‌افزار',icon:<Cog6ToothIcon/>},{id:'maintenance',title:'حالت تعمیرات',description:'قفل دسترسی کاربران هنگام نگهداری',icon:<LockClosedIcon/>},{id:'updates',title:'بروزرسانی و استقرار',description:'نسخه و وضعیت انتشار',icon:<PresentationChartLineIcon/>},{id:'backup',title:'پشتیبان‌گیری و بازیابی',description:'سیاست و سوابق Backup',icon:<BriefcaseIcon/>},{id:'payments',title:'پرداخت‌ها و تراکنش‌ها',description:'پرداخت و سوابق مالی',icon:<BriefcaseIcon/>},{id:'roles',title:'نقش‌ها و مجوزها',description:'نقش و Permission',icon:<ShieldCheckIcon/>},{id:'audit',title:'گزارش Audit Log',description:'ردیابی عملیات مدیریتی',icon:<ClipboardDocumentIcon/>},{id:'sessions',title:'مدیریت نشست‌ها',description:'کنترل نشست‌های کاربران',icon:<LockClosedIcon/>},{id:'api',title:'سرویس‌ها و APIها',description:'پیکربندی و سلامت سرویس‌ها',icon:<GlobeAltIcon/>},{id:'infrastructure',title:'سلامت زیرساخت',description:'دیتابیس، سرور و سرویس‌ها',icon:<PresentationChartLineIcon/>}
];
const VIEW_ONLY_MODULES: AdminSection[] = ['dashboard','monitoring','reports','audit'];
const fmt=(v:number|undefined|null)=>Number(v||0).toLocaleString('fa-IR');
const StatCard:React.FC<{title:string;value:number;hint:string}>=({title,value,hint})=><div className="rounded-2xl border border-[var(--card-border-color)] bg-[var(--card-bg)] p-5 shadow-sm"><div className="text-sm text-gray-500">{title}</div><div className="mt-2 text-3xl font-extrabold">{fmt(value)}</div><div className="mt-2 text-xs text-gray-500">{hint}</div></div>;
const ACTION_LABELS: Record<string,string> = {'activate-user':'فعال‌سازی کاربر','deactivate-user':'غیرفعال‌سازی کاربر','set-subscription':'ثبت اشتراک','delete-analysis':'حذف تحلیل','delete-history-item':'حذف سابقه','broadcast':'ارسال اعلان همگانی','revoke-session':'لغو نشست','revoke-all-user-sessions':'لغو همه نشست‌های کاربر','revoke-api-key':'لغو کلید API','assign-role':'تخصیص نقش','set-policy':'ثبت سیاست','set-setting':'ثبت تنظیم','enable':'فعال‌سازی تعمیرات','disable':'غیرفعال‌سازی تعمیرات','set-config':'ثبت تنظیمات AI','set-prompt':'ثبت پرامپت','health-check':'بررسی سلامت','snapshot':'ساخت گزارش Snapshot','set-channel':'تغییر کانال انتشار','create-transaction':'ایجاد تراکنش','set-status':'تغییر وضعیت تراکنش','create-backup':'ایجاد پشتیبان','get-status':'مشاهده وضعیت پشتیبان‌ها','record-deployment':'ثبت استقرار','get-deployments':'مشاهده استقرارها','list-roles':'مشاهده نقش‌ها','list-sessions':'مشاهده نشست‌ها','list-api-keys':'مشاهده کلیدهای API'};
const AdminPanel:React.FC<AdminPanelProps>=({isOnline,onMessageUpdate,onlineCount})=>{
 const [section,setSection]=useState<AdminSection>('dashboard');
 const [dashboard,setDashboard]=useState<AdminDashboardData|null>(null); const [modulesState,setModulesState]=useState<adminControlService.AdminModuleRecord[]>([]); const [overview,setOverview]=useState<adminOperationsService.AdminModuleOverview|null>(null); const [capabilities,setCapabilities]=useState<adminActionsService.AdminCapability|null>(null);
 const [permissions,setPermissions]=useState<Set<string>|null>(null); const [config,setConfig]=useState('{}'); const [enabled,setEnabled]=useState(true); const [actionPayload,setActionPayload]=useState('{}');
 const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [actionBusy,setActionBusy]=useState(false); const [error,setError]=useState<string|null>(null); const [saved,setSaved]=useState(false); const [actionMessage,setActionMessage]=useState<string|null>(null);
 const canAccess=(moduleKey:AdminSection,action:'view'|'manage'='view')=>permissions===null||permissions.has(`admin.${moduleKey}.${action}`);
 const canManage=canAccess(section,'manage'); const visibleModules=useMemo(()=>modules.filter(m=>canAccess(m.id,VIEW_ONLY_MODULES.includes(m.id)?'view':'manage')),[permissions]);
 const active=useMemo(()=>visibleModules.find(x=>x.id===section)||visibleModules[0]||modules[0],[section,visibleModules]);
 useEffect(()=>{let cancelled=false;void adminActionsService.getMyPermissions().then(keys=>{if(!cancelled)setPermissions(new Set(keys));}).catch(e=>{if(!cancelled){setPermissions(new Set());setError(e instanceof Error?e.message:'دریافت سطح دسترسی کاربر ناموفق بود.');}});return()=>{cancelled=true;}},[]);
 useEffect(()=>{if(permissions!==null&&!visibleModules.some(m=>m.id===section)){setSection(visibleModules[0]?.id||'dashboard');}},[permissions,section,visibleModules]);
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const [d,m,o,c]=await Promise.all([adminDashboardService.getAdminDashboard(),adminControlService.getModules(),adminOperationsService.getOverview(section),adminActionsService.getCapabilities(section)]);setDashboard(d);setModulesState(m);setOverview(o);setCapabilities(c);setEnabled(o.enabled);setConfig(JSON.stringify(o.config||{},null,2));setActionMessage(null);}catch(e){setError(e instanceof Error?e.message:'خطا در دریافت اطلاعات پنل مدیریت.');}finally{setLoading(false);}},[section]);
 useEffect(()=>{void load();},[load]);
 const save=async()=>{if(!canManage){setError('برای تغییر این بخش دسترسی مدیریتی ندارید.');return;}setSaved(false);setError(null);let parsed:Record<string,unknown>;try{parsed=JSON.parse(config);if(!parsed||Array.isArray(parsed)||typeof parsed!=='object')throw new Error();}catch{setError('تنظیمات باید JSON معتبر و به‌صورت یک شیء باشد.');return;}setSaving(true);try{const o=await adminOperationsService.saveConfig(section,enabled,parsed);setOverview(o);setSaved(true);await load();}catch(e){setError(e instanceof Error?e.message:'ذخیره تنظیمات ناموفق بود.');}finally{setSaving(false);}};
 const execute=async(action:string)=>{if(!canManage){setError('برای اجرای عملیات این بخش دسترسی مدیریتی ندارید.');return;}setActionBusy(true);setActionMessage(null);setError(null);try{let payload:Record<string,unknown>={};try{const p=JSON.parse(actionPayload);if(!p||Array.isArray(p)||typeof p!=='object')throw new Error();payload=p;}catch{setError('پارامتر عملیات باید JSON معتبر باشد.');setActionBusy(false);return;}const result=await adminActionsService.executeAction(section,action,payload);setActionMessage(`عملیات «${ACTION_LABELS[action]||action}» با موفقیت انجام شد.`);setActionPayload(JSON.stringify(result||{},null,2));await load();}catch(e){setError(e instanceof Error?e.message:'اجرای عملیات ناموفق بود.');}finally{setActionBusy(false);}};
 const renderDashboard=()=> <div className="space-y-6"><div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-4"><StatCard title="کل کاربران" value={dashboard?.totalUsers||0} hint="کاربران ثبت‌شده"/><StatCard title="اشتراک فعال" value={dashboard?.activeSubscriptions||0} hint="اعتبار جاری"/><StatCard title="کل تحلیل‌ها" value={dashboard?.totalAnalyses||0} hint="سوابق تحلیل"/><StatCard title="کل API Key" value={dashboard?.totalApiKeys||0} hint="کلیدهای فعال"/></div><div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-4"><StatCard title="رویدادهای Audit" value={overview?.counts?.total||0} hint="رویدادهای ثبت‌شده"/><StatCard title="نشست‌ها" value={overview?.counts?.sessions||0} hint="نشست‌های ثبت‌شده"/><StatCard title="اعلان‌ها" value={dashboard?.totalNotifications||0} hint="سوابق اعلان"/><StatCard title="ماژول‌ها" value={modules.length} hint="۲۳ بخش مدیریتی"/></div><div className="rounded-2xl border border-[var(--card-border-color)] bg-[var(--card-bg)] p-5"><h3 className="font-bold mb-3">وضعیت سامانه</h3><div className="grid md:grid-cols-3 gap-3"><div className="rounded-xl bg-gray-50 dark:bg-gray-800/60 p-4">اتصال: <b>{isOnline?'آنلاین':'قطع'}</b></div><div className="rounded-xl bg-gray-50 dark:bg-gray-800/60 p-4">کاربران آنلاین: <b>{fmt(onlineCount)}</b></div><div className="rounded-xl bg-gray-50 dark:bg-gray-800/60 p-4">ماژول فعال: <b>{modulesState.filter(x=>x.enabled).length} / ۲۳</b></div></div></div></div>;
 const renderActions=()=> canManage&&capabilities&&capabilities.actions.length>0 ? <div className="rounded-2xl border border-[var(--card-border-color)] bg-[var(--card-bg)] p-5"><div className="flex items-center justify-between gap-3"><div><h3 className="font-bold">عملیات واقعی {active.title}</h3><p className="text-xs text-gray-500 mt-1">این عملیات مستقیماً روی داده‌های سامانه اجرا و در Audit Log ثبت می‌شود.</p></div><span className="rounded-full bg-cyan-50 px-3 py-1 text-xs text-cyan-700">{capabilities.actions.length} عملیات</span></div><textarea value={actionPayload} onChange={e=>setActionPayload(e.target.value)} className="mt-4 min-h-[120px] w-full rounded-xl border border-[var(--card-border-color)] bg-transparent p-4 font-mono text-sm ltr" dir="ltr" spellCheck={false} placeholder="پارامتر عملیات به صورت JSON"/><div className="mt-3 flex flex-wrap gap-2">{capabilities.actions.map(action=><button key={action} disabled={actionBusy} onClick={()=>void execute(action)} className="rounded-xl border border-cyan-500/40 px-4 py-2 text-sm font-semibold hover:bg-cyan-50 dark:hover:bg-cyan-950/30 disabled:opacity-50">{ACTION_LABELS[action]||action}</button>)}</div>{actionMessage&&<div className="mt-3 text-sm text-green-600">{actionMessage}</div>}</div> : null;
 const renderModule=()=> {if(section==='subscriptions')return <AdminSubscriptionsPanel/>;if(section==='analysis')return <AdminAnalysesPanel/>;if(section==='market')return <AdminMarketPanel onComplete={onMessageUpdate}/>;if(section==='reports')return <AdminReportsPanel/>; const dedicated=section==='payments'||section==='backup'||section==='updates'||section==='security'||section==='settings'||section==='maintenance'||section==='roles'||section==='sessions'||section==='api'; return <div className="space-y-5"><div className="grid grid-cols-1 md:grid-cols-2 gap-4"><div className="rounded-2xl border border-[var(--card-border-color)] bg-[var(--card-bg)] p-5"><div className="flex items-center justify-between"><h3 className="font-bold">{active.title}</h3><span className={`rounded-full px-3 py-1 text-xs ${enabled?'bg-green-100 text-green-700':'bg-red-100 text-red-700'}`}>{enabled?'فعال':'غیرفعال'}</span></div><p className="mt-2 text-sm text-gray-500">{active.description}</p><label className="mt-4 flex items-center gap-3"><input type="checkbox" checked={enabled} disabled={!canManage||dedicated} onChange={e=>setEnabled(e.target.checked)}/><span>فعال بودن ماژول</span></label><textarea value={config} onChange={e=>setConfig(e.target.value)} disabled={!canManage||dedicated} className="mt-4 min-h-[220px] w-full rounded-xl border border-[var(--card-border-color)] bg-transparent p-4 font-mono text-sm ltr" dir="ltr" spellCheck={false}/><div className="mt-3 flex justify-end"><button disabled={!canManage||dedicated||saving} onClick={()=>void save()} className="rounded-xl bg-cyan-600 px-5 py-2.5 font-semibold text-white disabled:opacity-50">{saving?'در حال ذخیره…':'ذخیره تنظیمات'}</button></div>{saved&&<div className="mt-3 text-sm text-green-600">تنظیمات ذخیره شد.</div>}</div><div>{dedicated?<OperationalPanels section={section} onComplete={onMessageUpdate}/>:renderActions()}</div></div></div>};
 if(loading)return <div className="p-8 text-center text-gray-500">در حال بارگذاری پنل مدیریت…</div>;
 return <div className="flex h-full min-h-0 flex-col gap-5"><div className="flex flex-col gap-4 lg:flex-row"><aside className="w-full lg:w-72 shrink-0 rounded-2xl border border-[var(--card-border-color)] bg-[var(--card-bg)] p-3"><div className="mb-3 px-2 text-xs font-semibold text-gray-500">ماژول‌های مدیریت</div><div className="grid grid-cols-2 gap-2 lg:grid-cols-1">{visibleModules.map(m=><button key={m.id} onClick={()=>setSection(m.id)} className={`flex items-center gap-3 rounded-xl p-3 text-right transition ${section===m.id?'bg-cyan-50 text-cyan-700 dark:bg-cyan-950/30':'hover:bg-gray-50 dark:hover:bg-gray-800/60'}`}><span className="shrink-0">{m.icon}</span><span><span className="block text-sm font-semibold">{m.title}</span><span className="hidden text-xs text-gray-500 lg:block">{m.description}</span></span></button>)}</div></aside><main className="min-w-0 flex-1">{error&&<div className="mb-4 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}{section==='dashboard'?renderDashboard():section==='monitoring'?<AdminMonitoringPanel onComplete={onMessageUpdate}/>:section==='notifications'?<AdminNotificationsPanel onComplete={onMessageUpdate}/>:section==='audit'?<AdminAuditPanel/>:section==='api'?<AdminApiKeysPanel/>:section==='infrastructure'?<AdminInfrastructurePanel onComplete={onMessageUpdate}/>:renderModule()}</main></div></div>;
};
export default AdminPanel;