import React,{useCallback,useEffect,useMemo,useState}from'react';
import * as adminActionsService from'../services/adminActionsService';
interface Props{onComplete?:()=>Promise<void>|void}
interface Check{name:string;status:string;httpStatus?:number;latencyMs?:number|null;error?:string;message?:string;uptimeSeconds?:number}
interface Health{status?:string;overall?:string;checkedAt?:string;services?:Check[];checks?:Check[];node?:Check;memory?:{rss:number;heapUsed:number;heapTotal:number};[key:string]:unknown}
const labels:Record<string,string>={healthy:'سالم',degraded:'ناپایدار',down:'قطع',unknown:'نامشخص'};
const title:Record<string,string>={database:'پایگاه داده',node:'Node.js',backend:'بک‌اند',frontend:'فرانت‌اند',api:'API',tsetmc:'TSETMC',codal:'کدال',ai:'هوش مصنوعی'};
const statusClass=(s:string)=>s==='healthy'?'bg-green-100 text-green-700 dark:bg-green-950/30 dark:text-green-300':s==='degraded'?'bg-amber-100 text-amber-700 dark:bg-amber-950/30 dark:text-amber-300':s==='down'?'bg-red-100 text-red-700 dark:bg-red-950/30 dark:text-red-300':'bg-gray-100 text-gray-700 dark:bg-gray-800 dark:text-gray-300';
const csvCell=(v:unknown)=>`"${String(v??'').replace(/"/g,'""').replace(/\r?\n/g,' ')}"`;
const fmtBytes=(v?:number)=>typeof v==='number'&&Number.isFinite(v)?`${(v/1024/1024).toLocaleString('fa-IR',{maximumFractionDigits:1})} مگابایت`:'—';
const fmtUptime=(v?:number)=>{if(typeof v!=='number'||!Number.isFinite(v))return'—';const d=Math.floor(v/86400),h=Math.floor(v%86400/3600),m=Math.floor(v%3600/60);return`${d.toLocaleString('fa-IR')} روز، ${h.toLocaleString('fa-IR')} ساعت، ${m.toLocaleString('fa-IR')} دقیقه`};
const AdminInfrastructurePanel:React.FC<Props>=({onComplete=()=>undefined})=>{
 const[health,setHealth]=useState<Health|null>(null),[busy,setBusy]=useState(true),[error,setError]=useState<string|null>(null),[lastCheck,setLastCheck]=useState<string|null>(null),[autoRefresh,setAutoRefresh]=useState(true);
 const check=useCallback(async(silent=false)=>{if(!silent)setBusy(true);setError(null);try{const result=await adminActionsService.executeAction<Health>('infrastructure','health-check',{});setHealth(result);setLastCheck(result?.checkedAt||new Date().toISOString());await onComplete();}catch(e){setError(e instanceof Error?e.message:'بررسی سلامت زیرساخت ناموفق بود.')}finally{if(!silent)setBusy(false)}},[onComplete]);
 useEffect(()=>{void check()},[check]);
 useEffect(()=>{if(!autoRefresh)return;const id=window.setInterval(()=>void check(true),30000);return()=>window.clearInterval(id)},[autoRefresh,check]);
 const checks=useMemo(()=>{const list=Array.isArray(health?.services)?health.services:Array.isArray(health?.checks)?health.checks:[];return health?.node&&!list.some(x=>x.name==='node')?[health.node,...list]:list},[health]);
 const healthy=checks.filter(x=>x.status==='healthy').length,degraded=checks.filter(x=>x.status==='degraded').length,down=checks.filter(x=>!['healthy','degraded'].includes(x.status)).length;
 const exportCsv=()=>{const rows=[['نام سرویس','وضعیت','زمان پاسخ (ms)','HTTP','پیام'],...checks.map(x=>[title[x.name]||x.name,x.status,x.latencyMs??'',x.httpStatus??'',x.error||x.message||''])];const content=['\uFEFF',rows.map(r=>r.map(csvCell).join(',')).join('\r\n')].join('');const blob=new Blob([content],{type:'text/csv;charset=utf-8;'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`infrastructure-health-${new Date().toISOString().slice(0,19).replace(/[:T]/g,'-')}.csv`;a.click();URL.revokeObjectURL(url)};
 const memory=health?.memory;
 return <div className="space-y-5" dir="rtl">
  <div className="rounded-2xl border border-[var(--card-border-color)] bg-[var(--card-bg)] p-5"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><div className="flex items-center gap-2"><span className={`h-2.5 w-2.5 rounded-full ${health?.status==='healthy'?'bg-green-500':health?.status==='degraded'?'bg-amber-500':'bg-red-500'}`}/><h3 className="text-xl font-bold">سلامت زیرساخت</h3></div><p className="mt-1 text-sm text-gray-500">پایش زنده سرویس‌ها، حافظه و زمان فعالیت Node.js.</p></div><div className="flex flex-wrap items-center gap-2"><label className="flex items-center gap-2 rounded-xl border px-3 py-2 text-xs cursor-pointer"><input type="checkbox" checked={autoRefresh} onChange={e=>setAutoRefresh(e.target.checked)}/><span>به‌روزرسانی خودکار</span></label><button onClick={exportCsv} disabled={!checks.length} className="rounded-xl border px-4 py-2 text-sm disabled:opacity-50">خروجی CSV</button><button onClick={()=>void check()} disabled={busy} className="rounded-xl bg-cyan-600 px-5 py-2.5 font-semibold text-white disabled:opacity-50">{busy?'در حال بررسی…':'بررسی مجدد'}</button></div></div>
   {error&&<div className="mt-4 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700 dark:border-red-900/50 dark:bg-red-950/20 dark:text-red-300">{error}</div>}
   <div className="mt-5 grid grid-cols-2 lg:grid-cols-4 gap-3"><div className="rounded-xl bg-slate-50 p-4 dark:bg-slate-900/50"><div className="text-xs text-gray-500">کل سرویس‌ها</div><div className="mt-2 text-2xl font-extrabold">{checks.length.toLocaleString('fa-IR')}</div></div><div className="rounded-xl bg-green-50 p-4 dark:bg-green-950/20"><div className="text-xs text-green-700 dark:text-green-300">سالم</div><div className="mt-2 text-2xl font-extrabold">{healthy.toLocaleString('fa-IR')}</div></div><div className="rounded-xl bg-amber-50 p-4 dark:bg-amber-950/20"><div className="text-xs text-amber-700 dark:text-amber-300">ناپایدار</div><div className="mt-2 text-2xl font-extrabold">{degraded.toLocaleString('fa-IR')}</div></div><div className="rounded-xl bg-red-50 p-4 dark:bg-red-950/20"><div className="text-xs text-red-700 dark:text-red-300">قطع/نامشخص</div><div className="mt-2 text-2xl font-extrabold">{down.toLocaleString('fa-IR')}</div></div></div>
  </div>
  <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
   <div className="rounded-2xl border border-[var(--card-border-color)] bg-[var(--card-bg)] p-5"><div className="text-xs text-gray-500">RSS حافظه</div><div className="mt-2 text-2xl font-extrabold">{fmtBytes(memory?.rss)}</div><div className="mt-1 text-xs text-gray-500">مصرف کل پردازش Node.js</div></div>
   <div className="rounded-2xl border border-[var(--card-border-color)] bg-[var(--card-bg)] p-5"><div className="text-xs text-gray-500">Heap مصرف‌شده</div><div className="mt-2 text-2xl font-extrabold">{fmtBytes(memory?.heapUsed)}</div><div className="mt-1 text-xs text-gray-500">از Heap تخصیص‌یافته: {fmtBytes(memory?.heapTotal)}</div></div>
   <div className="rounded-2xl border border-[var(--card-border-color)] bg-[var(--card-bg)] p-5"><div className="text-xs text-gray-500">زمان فعالیت Node.js</div><div className="mt-2 text-lg font-extrabold">{fmtUptime(health?.node?.uptimeSeconds)}</div><div className="mt-1 text-xs text-gray-500">بدون وقفه از آخرین راه‌اندازی</div></div>
  </div>
  <div className="rounded-2xl border border-[var(--card-border-color)] bg-[var(--card-bg)] p-5"><div className="mb-4 flex items-center justify-between"><div><h4 className="font-bold">وضعیت سرویس‌ها</h4><p className="mt-1 text-xs text-gray-500">آخرین Health Check واقعی Backend</p></div><span className="text-xs text-gray-500">{lastCheck?new Date(lastCheck).toLocaleString('fa-IR'):'—'}</span></div><div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-3">{checks.map((item,i)=><div key={`${item.name}-${i}`} className="rounded-xl border border-[var(--card-border-color)] p-4"><div className="flex items-center justify-between gap-2"><span className="font-semibold">{title[item.name]||item.name||'سرویس'}</span><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${statusClass(item.status)}`}>{labels[item.status]||'نامشخص'}</span></div><div className="mt-3 grid grid-cols-2 gap-2 text-xs text-gray-500"><span>تأخیر: <b className="text-gray-800 dark:text-gray-200">{item.latencyMs!=null?`${item.latencyMs.toLocaleString('fa-IR')} ms`:'—'}</b></span><span>HTTP: <b className="text-gray-800 dark:text-gray-200">{item.httpStatus??'—'}</b></span></div>{(item.error||item.message)&&<div className="mt-3 rounded-lg bg-red-50 p-2 text-xs text-red-700 dark:bg-red-950/20 dark:text-red-300">{item.error||item.message}</div>}</div>)}{!checks.length&&!busy&&<div className="col-span-full py-8 text-center text-gray-500">داده‌ای برای نمایش دریافت نشد.</div>}</div></div>
  <div className="rounded-xl border border-cyan-500/20 bg-cyan-50 p-4 text-sm text-cyan-900 dark:bg-cyan-950/20 dark:text-cyan-100">این بخش فقط وضعیت واقعی سرویس‌ها و منابع پردازشی را نمایش می‌دهد و هیچ تغییری در تنظیمات یا داده‌های عملیاتی ایجاد نمی‌کند. به‌روزرسانی خودکار هر ۳۰ ثانیه انجام می‌شود.</div>
 </div>;
};
export default AdminInfrastructurePanel;
