import React,{useCallback,useEffect,useState}from'react';
import * as adminActionsService from'../services/adminActionsService';
import * as apiClient from'../services/apiClient';
interface Props{onComplete?:()=>Promise<void>|void}
type NotificationType='INFO'|'SUCCESS'|'WARNING'|'ERROR';
interface Row{id:number;userId:number;title:string;message:string;type:string;isRead:boolean;createdAt:string}
interface Overview{counts:{total:number;unread:number;last24h:number;last7d:number;last30d:number;activeUsers:number};byType:{type:string;count:number}[]}
interface History{items:Row[];pagination:{page:number;limit:number;total:number;totalPages:number}}
const card='rounded-2xl border border-[var(--card-border-color)] bg-[var(--card-bg)] p-5 shadow-sm';
const input='w-full rounded-xl border border-[var(--card-border-color)] bg-transparent px-3 py-2.5 text-sm outline-none focus:ring-2 focus:ring-cyan-500/30';
const labels:Record<string,string>={INFO:'اطلاع‌رسانی',info:'اطلاع‌رسانی',SUCCESS:'موفقیت',success:'موفقیت',WARNING:'هشدار',warning:'هشدار',ERROR:'خطا',error:'خطا'};
const fmt=(v:number)=>Number(v||0).toLocaleString('fa-IR');const dateFmt=(v?:string)=>v?new Date(v).toLocaleString('fa-IR'):'—';
const AdminNotificationsPanel:React.FC<Props>=({onComplete=()=>undefined})=>{
 const[overview,setOverview]=useState<Overview|null>(null),[history,setHistory]=useState<History|null>(null),[loading,setLoading]=useState(true),[historyLoading,setHistoryLoading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[message,setMessage]=useState(''),[recipients,setRecipients]=useState<number|null>(null);
 const[title,setTitle]=useState('اطلاعیه سامانه'),[body,setBody]=useState(''),[type,setType]=useState<NotificationType>('INFO');
 const[search,setSearch]=useState(''),[filterType,setFilterType]=useState(''),[read,setRead]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[page,setPage]=useState(1);const limit=20;
 const load=useCallback(async()=>{setLoading(true);try{const r=await apiClient.get<Overview>('/admin-notifications/overview');if(!r.success||!r.data)throw new Error(r.message||'دریافت اطلاعات ناموفق بود.');setOverview(r.data);setError(null)}catch(e){setError(e instanceof Error?e.message:'خطا در دریافت اطلاعات.')}finally{setLoading(false)}},[]);
 const loadHistory=useCallback(async()=>{setHistoryLoading(true);try{const q=new URLSearchParams({page:String(page),limit:String(limit)});if(search.trim())q.set('search',search.trim());if(filterType)q.set('type',filterType);if(read)q.set('read',read);if(from)q.set('from',from);if(to)q.set('to',to);const r=await apiClient.get<History>('/admin-notifications/history?'+q.toString());if(!r.success||!r.data)throw new Error(r.message||'دریافت تاریخچه ناموفق بود.');setHistory(r.data)}catch(e){setError(e instanceof Error?e.message:'خطا در دریافت تاریخچه.')}finally{setHistoryLoading(false)}},[page,search,filterType,read,from,to]);
 useEffect(()=>{void load()},[load]);useEffect(()=>{void loadHistory()},[loadHistory]);
 const send=async()=>{if(!title.trim()||!body.trim()){setError('عنوان و متن اعلان الزامی است.');return}if(!window.confirm('این اعلان برای همه کاربران فعال ارسال می‌شود. تأیید می‌کنید؟'))return;setBusy(true);setError(null);setMessage('');try{const r=await adminActionsService.executeAction<{recipients?:number}>('notifications','broadcast',{title:title.trim(),message:body.trim(),type:type.toLowerCase()});setRecipients(r?.recipients??0);setMessage('اعلان با موفقیت ارسال شد.');setBody('');await Promise.all([load(),loadHistory()]);await onComplete()}catch(e){setError(e instanceof Error?e.message:'ارسال اعلان ناموفق بود.')}finally{setBusy(false)}};
 const clear=()=>{setSearch('');setFilterType('');setRead('');setFrom('');setTo('');setPage(1)};
 return <div className="space-y-6" dir="rtl">
  <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold">مرکز اطلاع‌رسانی</h2><p className="mt-1 text-sm text-gray-500">ارسال اعلان، آمار واقعی و مدیریت تاریخچه اطلاع‌رسانی کاربران.</p></div><button onClick={()=>{void load();void loadHistory()}} disabled={loading||historyLoading} className="rounded-xl border px-4 py-2 text-sm font-semibold">{loading||historyLoading?'در حال بررسی...':'به‌روزرسانی'}</button></div>
  {error&&<div className="rounded-xl border border-red-300 bg-red-50 p-4 text-sm text-red-700 dark:bg-red-950/20">{error}</div>}
  <div className="grid grid-cols-2 lg:grid-cols-6 gap-3">{[["کل اعلان‌ها",overview?.counts.total||0],["خوانده‌نشده",overview?.counts.unread||0],["۲۴ ساعت اخیر",overview?.counts.last24h||0],["۷ روز اخیر",overview?.counts.last7d||0],["۳۰ روز اخیر",overview?.counts.last30d||0],["کاربران فعال",overview?.counts.activeUsers||0]].map(([t,v])=><div className={card} key={String(t)}><div className="text-xs text-gray-500">{t}</div><div className="mt-2 text-2xl font-extrabold">{fmt(Number(v))}</div></div>)}</div>
  <div className="grid grid-cols-1 xl:grid-cols-5 gap-5"><div className={`${card} xl:col-span-2`}><h3 className="font-bold mb-4">ارسال اعلان همگانی</h3><div className="grid grid-cols-1 sm:grid-cols-3 gap-3"><label className="space-y-1.5 sm:col-span-2"><span className="text-sm">عنوان</span><input value={title} onChange={e=>setTitle(e.target.value)} maxLength={200} className={input}/></label><label className="space-y-1.5"><span className="text-sm">نوع</span><select value={type} onChange={e=>setType(e.target.value as NotificationType)} className={input}>{(['INFO','SUCCESS','WARNING','ERROR']as NotificationType[]).map(k=><option key={k} value={k}>{labels[k]}</option>)}</select></label></div><label className="mt-4 block space-y-1.5"><span className="text-sm">متن اعلان</span><textarea value={body} onChange={e=>setBody(e.target.value)} maxLength={5000} rows={8} className={input}/><span className="text-xs text-gray-500">{fmt(body.length)} / ۵۰۰۰ نویسه</span></label><div className="mt-4 rounded-xl border p-3 text-sm">گیرندگان: <b>{fmt(overview?.counts.activeUsers||0)} کاربر فعال</b></div><button disabled={busy||!title.trim()||!body.trim()} onClick={()=>void send()} className="mt-4 rounded-xl bg-cyan-600 px-6 py-2.5 font-semibold text-white disabled:opacity-50">{busy?'در حال ارسال...':'ارسال اعلان به همه کاربران'}</button>{message&&<p className="mt-3 text-sm text-green-600">{message}{recipients!==null?` تعداد گیرندگان: ${fmt(recipients)}`:''}</p>}</div>
  <div className={`${card} xl:col-span-3`}><h3 className="font-bold">توزیع بر اساس نوع</h3><div className="mt-5 space-y-3">{(overview?.byType||[]).map(x=><div key={x.type} className="flex items-center gap-3"><div className="w-28 text-sm">{labels[x.type]||x.type}</div><div className="h-3 flex-1 rounded-full bg-slate-100 dark:bg-slate-800"><div className="h-full rounded-full bg-cyan-500" style={{width:`${Math.min(100,x.count/Math.max(1,overview?.counts.total||1)*100)}%`}}/></div><div className="w-16 text-left text-sm font-bold">{fmt(x.count)}</div></div>)}</div></div></div>
  <div className={card}><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-bold">تاریخچه اعلان‌ها</h3><p className="mt-1 text-xs text-gray-500">جست‌وجو، فیلتر وضعیت و صفحه‌بندی از دیتابیس</p></div></div><div className="mt-4 grid grid-cols-1 md:grid-cols-2 xl:grid-cols-5 gap-3"><input className={input} value={search} onChange={e=>setSearch(e.target.value)} placeholder="جست‌وجو در عنوان یا متن"/><select className={input} value={filterType} onChange={e=>setFilterType(e.target.value)}><option value="">همه انواع</option><option value="info">اطلاع‌رسانی</option><option value="success">موفقیت</option><option value="warning">هشدار</option><option value="error">خطا</option></select><select className={input} value={read} onChange={e=>setRead(e.target.value)}><option value="">همه وضعیت‌ها</option><option value="read">خوانده‌شده</option><option value="unread">خوانده‌نشده</option></select><input className={input} type="date" value={from} onChange={e=>setFrom(e.target.value)}/><input className={input} type="date" value={to} onChange={e=>setTo(e.target.value)}/></div><div className="mt-3 flex gap-2"><button onClick={()=>setPage(1)} className="rounded-xl bg-cyan-600 px-5 py-2.5 text-sm font-semibold text-white">اعمال فیلتر</button><button onClick={clear} className="rounded-xl border px-5 py-2.5 text-sm font-semibold">پاک‌کردن</button><span className="self-center text-xs text-gray-500">تعداد: {fmt(history?.pagination.total||0)}</span></div><div className="mt-4 overflow-auto"><table className="w-full min-w-[950px] text-sm"><thead><tr className="border-b"><th className="p-3 text-right">شناسه</th><th className="p-3 text-right">کاربر</th><th className="p-3 text-right">عنوان</th><th className="p-3 text-right">نوع</th><th className="p-3 text-right">وضعیت</th><th className="p-3 text-right">تاریخ</th></tr></thead><tbody>{(history?.items||[]).map(r=><tr key={r.id} className="border-b"><td className="p-3" dir="ltr">{r.id}</td><td className="p-3" dir="ltr">{r.userId}</td><td className="p-3 max-w-[360px] truncate">{r.title||'—'}</td><td className="p-3">{labels[r.type]||r.type}</td><td className="p-3">{r.isRead?'خوانده‌شده':'خوانده‌نشده'}</td><td className="p-3">{dateFmt(r.createdAt)}</td></tr>)}</tbody></table>{historyLoading&&<div className="py-6 text-center text-gray-500">در حال دریافت...</div>}{!historyLoading&&!history?.items.length&&<div className="py-8 text-center text-gray-500">رکوردی پیدا نشد.</div>}</div><div className="mt-4 flex items-center justify-between"><button disabled={historyLoading||page<=1} onClick={()=>setPage(p=>p-1)} className="rounded-xl border px-4 py-2 text-sm disabled:opacity-50">قبلی</button><span className="text-sm">صفحه {fmt(page)} از {fmt(history?.pagination.totalPages||1)}</span><button disabled={historyLoading||page>=(history?.pagination.totalPages||1)} onClick={()=>setPage(p=>p+1)} className="rounded-xl border px-4 py-2 text-sm disabled:opacity-50">بعدی</button></div></div>
 </div>;
};export default AdminNotificationsPanel;
