import React, { useCallback, useEffect, useMemo, useState } from 'react';
import * as adminDashboardService from '../services/adminDashboardService';
import * as adminControlService from '../services/adminControlService';
import * as adminOperationsService from '../services/adminOperationsService';
import * as adminActionsService from '../services/adminActionsService';
import type { AdminDashboardData } from '../services/adminDashboardService';
import { ChartBarIcon, UserGroupIcon, BriefcaseIcon, Cog6ToothIcon, BellIcon, ShieldCheckIcon, PresentationChartLineIcon, ClipboardDocumentIcon, GlobeAltIcon, MagnifyingGlassIcon, LockClosedIcon } from './Icons';

interface AdminPanelProps { isOnline: boolean; onMessageUpdate: () => void; onlineCount: number; }
type AdminSection = adminControlService.AdminModuleKey;
interface ModuleItem { id: AdminSection; title: string; description: string; icon: React.ReactNode; }

const modules: ModuleItem[] = [
 ['dashboard','داشبورد مدیریتی','شاخص‌ها و وضعیت کلی سامانه',<ChartBarIcon/>],['users','مدیریت کاربران','فعال‌سازی و کنترل حساب‌ها',<UserGroupIcon/>],['subscriptions','اشتراک‌ها و اعتبار','اشتراک، تمدید و سقف تحلیل',<BriefcaseIcon/>],['analysis','مدیریت تحلیل‌ها','کنترل و حذف تحلیل‌ها',<MagnifyingGlassIcon/>],['market','مدیریت بازار','سلامت و داده‌های بازار',<GlobeAltIcon/>],['scalping','نوسان‌گیری','سلامت موتور نوسان‌گیری',<ChartBarIcon/>],['ai','هوش مصنوعی','تنظیم مدل و سرویس AI',<PresentationChartLineIcon/>],['prompts','مدیریت پرامپت‌ها','مدیریت پرامپت‌های AI',<ClipboardDocumentIcon/>],['history','تاریخچه تحلیل‌ها','سوابق و نگهداری تحلیل',<ClipboardDocumentIcon/>],['notifications','اطلاع‌رسانی','ارسال اعلان همگانی',<BellIcon/>],['monitoring','مانیتورینگ سیستم','پایش سرویس‌ها',<PresentationChartLineIcon/>],['reports','گزارش‌ها','ساخت Snapshot مدیریتی',<ChartBarIcon/>],['security','امنیت و دسترسی','سیاست‌های امنیتی',<ShieldCheckIcon/>],['settings','تنظیمات سامانه','تنظیمات عمومی',<Cog6ToothIcon/>],['maintenance','حالت تعمیرات','فعال یا غیرفعال کردن تعمیرات',<LockClosedIcon/>],['updates','بروزرسانی و استقرار','کانال انتشار',<PresentationChartLineIcon/>],['backup','پشتیبان‌گیری و بازیابی','سیاست Backup',<BriefcaseIcon/>],['payments','پرداخت‌ها و تراکنش‌ها','وضعیت زیرساخت مالی',<BriefcaseIcon/>],['roles','نقش‌ها و مجوزها','تخصیص نقش کاربران',<ShieldCheckIcon/>],['audit','گزارش Audit Log','ردیابی عملیات مدیریتی',<ClipboardDocumentIcon/>],['sessions','مدیریت نشست‌ها','لغو نشست‌های کاربران',<LockClosedIcon/>],['api','سرویس‌ها و APIها','مدیریت API Key و سرویس‌ها',<GlobeAltIcon/>],['infrastructure','سلامت زیرساخت','سلامت پایگاه داده و سرویس',<PresentationChartLineIcon/>]
].map(([id,title,description,icon]) => ({ id:id as AdminSection, title:title as string, description:description as string, icon }));

const labels: Record<string,string> = {'activate-user':'فعال‌سازی کاربر','deactivate-user':'غیرفعال‌سازی کاربر','set-subscription':'ثبت اشتراک','delete-analysis':'حذف تحلیل','delete-history-item':'حذف سابقه','broadcast':'ارسال اعلان همگانی','revoke-session':'لغو نشست','revoke-all-user-sessions':'لغو همه نشست‌ها','revoke-api-key':'لغو API Key','assign-role':'تخصیص نقش','set-policy':'ثبت سیاست','set-setting':'ثبت تنظیم','enable':'فعال‌سازی تعمیرات','disable':'غیرفعال‌سازی تعمیرات','set-config':'ثبت تنظیمات AI','set-prompt':'ثبت پرامپت','health-check':'بررسی سلامت','snapshot':'ساخت Snapshot','set-channel':'تغییر کانال انتشار'};
const inputClass='w-full rounded-xl border border-[var(--card-border-color)] bg-transparent px-3 py-2.5 text-sm outline-none focus:ring-2 focus:ring-cyan-500/30';
const fmt=(v:number|undefined|null)=>Number(v||0).toLocaleString('fa-IR');

const AdminPanelV2: React.FC<AdminPanelProps> = ({isOnline,onMessageUpdate,onlineCount}) => {
 const [section,setSection]=useState<AdminSection>('dashboard');
 const [dashboard,setDashboard]=useState<AdminDashboardData|null>(null); const [overview,setOverview]=useState<adminOperationsService.AdminModuleOverview|null>(null); const [modulesState,setModulesState]=useState<adminControlService.AdminModuleRecord[]>([]); const [capabilities,setCapabilities]=useState<adminActionsService.AdminCapability|null>(null); const [audit,setAudit]=useState<adminControlService.AdminAuditRecord[]>([]);
 const [fields,setFields]=useState<Record<string,string>>({}); const [busy,setBusy]=useState(false); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [message,setMessage]=useState<string|null>(null);
 const active=useMemo(()=>modules.find(m=>m.id===section) || modules[0],[section]);
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const [d,o,m,c]=await Promise.all([adminDashboardService.getAdminDashboard(),adminOperationsService.getOverview(section),adminControlService.getModules(),adminActionsService.getCapabilities(section)]);setDashboard(d);setOverview(o);setModulesState(m);setCapabilities(c);if(section==='audit')setAudit(await adminControlService.getAudit(100));setFields({});setMessage(null);}catch(e){setError(e instanceof Error?e.message:'دریافت اطلاعات ناموفق بود.');}finally{setLoading(false);}},[section]);
 useEffect(()=>{void load();},[load]);
 const set=(key:string,value:string)=>setFields(prev=>({...prev,[key]:value}));
 const execute=async(action:string)=>{setBusy(true);setError(null);setMessage(null);try{const payload:Record<string,unknown>={};Object.entries(fields).forEach(([k,v])=>{if(v.trim())payload[k]=v.trim();});if(fields.value && ['set-policy','set-config','set-setting'].includes(action)){try{payload.value=JSON.parse(fields.value);}catch{payload.value=fields.value;}}await adminActionsService.executeAction(section,action,payload);setMessage(`«${labels[action]||action}» با موفقیت انجام شد.`);await load();}catch(e){setError(e instanceof Error?e.message:'اجرای عملیات ناموفق بود.');}finally{setBusy(false);}};
 const field=(key:string,label:string,type='text',placeholder='')=><label className="space-y-1.5"><span className="text-xs font-semibold text-gray-600 dark:text-gray-300">{label}</span><input className={inputClass} type={type} value={fields[key]||''} onChange={e=>set(key,e.target.value)} placeholder={placeholder} dir={type==='text'?'auto':undefined}/></label>;
 const renderActionForm=(action:string)=>{if(['health-check','snapshot','enable','disable'].includes(action))return <button disabled={busy} onClick={()=>void execute(action)} className="rounded-xl bg-cyan-600 px-5 py-2.5 font-semibold text-white disabled:opacity-50">{busy?'در حال اجرا...':labels[action]}</button>;
  if(action==='broadcast')return <div className="grid md:grid-cols-3 gap-3">{field('title','عنوان اعلان')}{field('message','متن اعلان')}{field('type','نوع اعلان','text','info')}<button disabled={busy} onClick={()=>void execute(action)} className="md:col-span-3 rounded-xl bg-cyan-600 px-5 py-2.5 font-semibold text-white disabled:opacity-50">ارسال به کاربران فعال</button></div>;
  if(action==='set-subscription')return <div className="grid md:grid-cols-2 gap-3">{field('userId','شناسه کاربر','number')}{field('subscriptionType','نوع اشتراک','text','premium')}{field('subscriptionMonths','مدت (ماه)','number')}{field('analysisLimit','سقف تحلیل','number')}{field('subscriptionStart','شروع اشتراک','datetime-local')}{field('subscriptionEnd','پایان اشتراک','datetime-local')}<button disabled={busy} onClick={()=>void execute(action)} className="md:col-span-2 rounded-xl bg-cyan-600 px-5 py-2.5 font-semibold text-white">ثبت اشتراک</button></div>;
  if(['activate-user','deactivate-user','revoke-all-user-sessions'].includes(action))return <div className="flex gap-3 items-end">{field('userId','شناسه کاربر','number')}<button disabled={busy} onClick={()=>void execute(action)} className="rounded-xl bg-cyan-600 px-5 py-2.5 font-semibold text-white whitespace-nowrap">{labels[action]}</button></div>;
  if(action==='assign-role')return <div className="grid md:grid-cols-3 gap-3">{field('userId','شناسه کاربر','number')}{field('roleId','شناسه نقش','number')}<button disabled={busy} onClick={()=>void execute(action)} className="rounded-xl bg-cyan-600 px-5 py-2.5 font-semibold text-white">تخصیص نقش</button></div>;
  if(action==='delete-analysis'||action==='delete-history-item'||action==='revoke-session'||action==='revoke-api-key')return <div className="flex gap-3 items-end">{field('id','شناسه','number')}<button disabled={busy} onClick={()=>void execute(action)} className="rounded-xl bg-red-600 px-5 py-2.5 font-semibold text-white">{labels[action]}</button></div>;
  return <div className="grid md:grid-cols-2 gap-3">{field('value','مقدار')}{field('reason','دلیل')}<button disabled={busy} onClick={()=>void execute(action)} className="md:col-span-2 rounded-xl bg-cyan-600 px-5 py-2.5 font-semibold text-white">اجرای عملیات</button></div>;
 };
 const renderAudit=()=> <div className="rounded-2xl border border-[var(--card-border-color)] bg-[var(--card-bg)] p-5"><h3 className="font-bold mb-4">Audit Log</h3><div className="overflow-auto"><table className="w-full text-sm"><thead><tr className="border-b border-[var(--card-border-color)]"><th className="p-3 text-right">زمان</th><th className="p-3 text-right">مدیر</th><th className="p-3 text-right">ماژول</th><th className="p-3 text-right">عملیات</th><th className="p-3 text-right">وضعیت</th></tr></thead><tbody>{audit.map(row=><tr key={String(row.id)} className="border-b border-[var(--card-border-color)]"><td className="p-3">{row.createdAt||'-'}</td><td className="p-3">{row.username||row.email||row.adminUserId||'-'}</td><td className="p-3">{row.moduleKey||'-'}</td><td className="p-3">{row.action||'-'}</td><td className="p-3">{row.statusCode||'-'}</td></tr>)}</tbody></table></div></div>;
 const render=()=> section==='dashboard'?<div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-4"><div className="rounded-2xl border p-5"><div className="text-sm text-gray-500">کل کاربران</div><div className="text-3xl font-extrabold mt-2">{fmt(dashboard?.totalUsers)}</div></div><div className="rounded-2xl border p-5"><div className="text-sm text-gray-500">تحلیل‌ها</div><div className="text-3xl font-extrabold mt-2">{fmt(dashboard?.totalAnalyses)}</div></div><div className="rounded-2xl border p-5"><div className="text-sm text-gray-500">کلیدهای API</div><div className="text-3xl font-extrabold mt-2">{fmt(dashboard?.totalApiKeys)}</div></div><div className="rounded-2xl border p-5"><div className="text-sm text-gray-500">نشست‌ها</div><div className="text-3xl font-extrabold mt-2">{fmt(dashboard?.activeSessions)}</div></div></div>:section==='audit'?renderAudit():<div className="space-y-5"><div className="rounded-2xl border border-[var(--card-border-color)] bg-[var(--card-bg)] p-5"><h3 className="font-bold">{active.title}</h3><p className="text-sm text-gray-500 mt-1">{active.description}</p><div className="grid md:grid-cols-2 gap-4 mt-5">{capabilities?.actions.map(action=><div key={action} className="rounded-xl border border-[var(--card-border-color)] p-4"><div className="font-semibold mb-3">{labels[action]||action}</div>{renderActionForm(action)}</div>)}</div></div><div className="rounded-2xl border border-[var(--card-border-color)] bg-[var(--card-bg)] p-5"><div className="grid md:grid-cols-4 gap-3"><div>وضعیت: <b>{overview?.enabled?'فعال':'غیرفعال'}</b></div><div>کاربران: <b>{fmt(overview?.counts?.users)}</b></div><div>تحلیل‌ها: <b>{fmt(overview?.counts?.analyses)}</b></div><div>نشست‌ها: <b>{fmt(overview?.counts?.sessions)}</b></div></div></div></div>;
 return <div className="space-y-6"><div className="flex flex-wrap gap-2">{modules.map(m=><button key={m.id} onClick={()=>setSection(m.id)} className={`rounded-xl px-3 py-2 text-sm ${section===m.id?'bg-cyan-600 text-white':'border border-[var(--card-border-color)]'}`}>{m.title}</button>)}</div>{loading?<div className="py-10 text-center text-gray-500">در حال بارگذاری...</div>:<>{error&&<div className="rounded-xl border border-red-300 bg-red-50 p-4 text-red-700">{error}</div>}{message&&<div className="rounded-xl border border-green-300 bg-green-50 p-4 text-green-700">{message}</div>}{render()}</>}</div>;
};

export default AdminPanelV2;
