import React, { useCallback, useEffect, useMemo, useState } from 'react';
import * as adminDashboardService from '../services/adminDashboardService';
import * as adminControlService from '../services/adminControlService';
import * as adminOperationsService from '../services/adminOperationsService';
import * as adminActionsService from '../services/adminActionsService';
import type { AdminDashboardData } from '../services/adminDashboardService';
import { ChartBarIcon, UserGroupIcon, BriefcaseIcon, Cog6ToothIcon, BellIcon, ShieldCheckIcon, PresentationChartLineIcon, ClipboardDocumentIcon, GlobeAltIcon, MagnifyingGlassIcon, LockClosedIcon } from './Icons';

interface AdminPanelProps { isOnline: boolean; onMessageUpdate: () => void; onlineCount: number; }
type AdminSection = adminControlService.AdminModuleKey;
interface ModuleItem { id: AdminSection; title: string; description: string; icon: React.ReactNode; }

const modules: ModuleItem[] = [
 ['dashboard','داشبورد مدیریتی','شاخص‌ها و وضعیت کلی سامانه',<ChartBarIcon/>],['users','مدیریت کاربران','فعال‌سازی و کنترل حساب‌ها',<UserGroupIcon/>],['subscriptions','اشتراک‌ها و اعتبار','اشتراک، تمدید و سقف تحلیل',<BriefcaseIcon/>],['analysis','مدیریت تحلیل‌ها','کنترل و حذف تحلیل‌ها',<MagnifyingGlassIcon/>],['market','مدیریت بازار','سلامت و داده‌های بازار',<GlobeAltIcon/>],['scalping','نوسان‌گیری','سلامت موتور نوسان‌گیری',<ChartBarIcon/>],['ai','هوش مصنوعی','تنظیم مدل و سرویس AI',<PresentationChartLineIcon/>],['prompts','مدیریت پرامپت‌ها','مدیریت پرامپت‌های AI',<ClipboardDocumentIcon/>],['history','تاریخچه تحلیل‌ها','سوابق و نگهداری تحلیل',<ClipboardDocumentIcon/>],['notifications','اطلاع‌رسانی','ارسال اعلان همگانی',<BellIcon/>],['monitoring','مانیتورینگ سیستم','پایش سرویس‌ها',<PresentationChartLineIcon/>],['reports','گزارش‌ها','ساخت Snapshot مدیریتی',<ChartBarIcon/>],['security','امنیت و دسترسی','سیاست‌های امنیتی',<ShieldCheckIcon/>],['settings','تنظیمات سامانه','تنظیمات عمومی',<Cog6ToothIcon/>],['maintenance','حالت تعمیرات','فعال یا غیرفعال کردن تعمیرات',<LockClosedIcon/>],['updates','بروزرسانی و استقرار','کانال انتشار',<PresentationChartLineIcon/>],['backup','پشتیبان‌گیری و بازیابی','سیاست Backup',<BriefcaseIcon/>],['payments','پرداخت‌ها و تراکنش‌ها','وضعیت زیرساخت مالی',<BriefcaseIcon/>],['roles','نقش‌ها و مجوزها','تخصیص نقش کاربران',<ShieldCheckIcon/>],['audit','گزارش Audit Log','ردیابی عملیات مدیریتی',<ClipboardDocumentIcon/>],['sessions','مدیریت نشست‌ها','لغو نشست‌های کاربران',<LockClosedIcon/>],['api','سرویس‌ها و APIها','مدیریت API Key و سرویس‌ها',<GlobeAltIcon/>],['infrastructure','سلامت زیرساخت','سلامت پایگاه داده و سرویس',<PresentationChartLineIcon/>]
].map(([id,title,description,icon]) => ({ id:id as AdminSection, title:title as string, description:description as string, icon }));

const labels: Record<string,string> = {'activate-user':'فعال‌سازی کاربر','deactivate-user':'غیرفعال‌سازی کاربر','set-subscription':'ثبت اشتراک','delete-analysis':'حذف تحلیل','delete-history-item':'حذف سابقه','broadcast':'ارسال اعلان همگانی','revoke-session':'لغو نشست','revoke-all-user-sessions':'لغو همه نشست‌ها','revoke-api-key':'لغو API Key','assign-role':'تخصیص نقش','set-policy':'ثبت سیاست','set-setting':'ثبت تنظیم','enable':'فعال‌سازی تعمیرات','disable':'غیرفعال‌سازی تعمیرات','set-config':'ثبت تنظیمات AI','set-prompt':'ثبت پرامپت','health-check':'بررسی سلامت','snapshot':'ساخت Snapshot','set-channel':'تغییر کانال انتشار'};
const inputClass='w-full rounded-xl border border-[var(--card-border-color)] bg-transparent px-3 py-2.5 text-sm outline-none focus:ring-2 focus:ring-cyan-500/30';
const fmt=(v:number|undefined|null)=>Number(v||0).toLocaleString('fa-IR');

const AdminPanelV2: React.FC<AdminPanelProps> = ({isOnline,onMessageUpdate,onlineCount}) => {
 const [section,setSection]=useState<AdminSection>('dashboard');
 const [dashboard,setDashboard]=useState<AdminDashboardData|null>(null); const [overview,setOverview]=useState<adminOperationsService.AdminModuleOverview|null>(null); const [modulesState,setModulesState]=useState<adminControlService.AdminModuleRecord[]>([]); const [capabilities,setCapabilities]=useState<adminActionsService.AdminCapability|null>(null); const [audit,setAudit]=useState<Record<string,unknown>[]>([]);
 const [fields,setFields]=useState<Record<string,string>>({}); const [busy,setBusy]=useState(false); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [message,setMessage]=useState<string|null>(null);
 const active=useMemo(()=>modules.find(m=>m.id===section) || modules[0],[section]);
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const [d,o,m,c]=await Promise.all([adminDashboardService.getAdminDashboard(),adminOperationsService.getOverview(section),adminControlService.getModules(),adminActionsService.getCapabilities(section)]);setDashboard(d);setOverview(o);setModulesState(m);setCapabilities(c);if(section==='audit')setAudit(await adminControlService.getAudit(100));setFields({});setMessage(null);}catch(e){setError(e instanceof Error?e.message:'دریافت اطلاعات ناموفق بود.');}finally{setLoading(false);}},[section]);
 useEffect(()=>{void load();},[load]);
 const set=(key:string,value:string)=>setFields(prev=>({...prev,[key]:value}));
 const execute=async(action:string)=>{setBusy(true);setError(null);setMessage(null);try{const payload:Record<string,unknown>={};Object.entries(fields).forEach(([k,v])=>{if(v.trim())payload[k]=v.trim();});if(fields.value && ['set-policy','set-config','set-setting'].includes(action)){try{payload.value=JSON.parse(fields.value);}catch{payload.value=fields.value;}}await adminActionsService.executeAction(section,action,payload);setMessage(`«${labels[action]||action}» با موفقیت انجام شد.`);await load();}catch(e){setError(e instanceof Error?e.message:'اجرای عملیات ناموفق بود.');}finally{setBusy(false);}};
 const field=(key:string,label:string,type='text',placeholder='')=><label className="space-y-1.5"><span className="text-xs font-semibold text-gray-600 dark:text-gray-300">{label}</span><input className={inputClass} type={type} value={fields[key]||''} onChange={e=>set(key,e.target.value)} placeholder={placeholder} dir={type==='text'?'auto':undefined}/></label>;
 const renderActionForm=(action:string)=>{if(['health-check','snapshot','enable','disable'].includes(action))return <button disabled={busy} onClick={()=>void execute(action)} className="rounded-xl bg-cyan-600 px-5 py-2.5 font-semibold text-white disabled:opacity-50">{busy?'در حال اجرا...':labels[action]}</button>;
  if(action==='broadcast')return <div className="grid md:grid-cols-3 gap-3">{field('title','عنوان اعلان')}{field('message','متن اعلان')}{field('type','نوع اعلان','text','info')}<button disabled={busy} onClick={()=>void execute(action)} className="md:col-span-3 rounded-xl bg-cyan-600 px-5 py-2.5 font-semibold text-white disabled:opacity-50">ارسال به کاربران فعال</button></div>;
  if(action==='set-subscription')return <div className="grid md:grid-cols-2 gap-3">{field('userId','شناسه کاربر','number')}{field('subscriptionType','نوع اشتراک','text','premium')}{field('subscriptionMonths','مدت (ماه)','number')}{field('analysisLimit','سقف تحلیل','number')}{field('subscriptionStart','شروع اشتراک','datetime-local')}{field('subscriptionEnd','پایان اشتراک','datetime-local')}<button disabled={busy} onClick={()=>void execute(action)} className="md:col-span-2 rounded-xl bg-cyan-600 px-5 py-2.5 font-semibold text-white">ثبت اشتراک</button></div>;
  if(['activate-user','deactivate-user','revoke-all-user-sessions'].includes(action))return <div className="flex gap-3 items-end">{field('userId','شناسه کاربر','number')}<button disabled={busy} onClick={()=>void execute(action)} className="rounded-xl bg-cyan-600 px-5 py-2.5 font-semibold text-white whitespace-nowrap">{labels[action]}</button></div>;
  if(action==='assign-role')return <div className="grid md:grid-cols-3 gap-3">{field('userId','شناسه کاربر','number')}{field('roleId','شناسه نقش','number')}<button disabled={busy} onClick={()=>void execute(action)} className="rounded-xl bg-cyan-600 px-5 py-2.5 font-semibold text-white">تخصیص نقش</button></div>;
  if(action==='revoke-session')return <div className="flex gap-3 items-end">{field('sessionId','شناسه نشست','number')}<button disabled={busy} onClick={()=>void execute(action)} className="rounded-xl bg-cyan-600 px-5 py-2.5 font-semibold text-white">لغو نشست</button></div>;
  if(action==='revoke-api-key')return <div className="flex gap-3 items-end">{field('apiKeyId','شناسه API Key','number')}<button disabled={busy} onClick={()=>void execute(action)} className="rounded-xl bg-cyan-600 px-5 py-2.5 font-semibold text-white">لغو API Key</button></div>;
  if(['delete-analysis','delete-history-item'].includes(action))return <div className="flex gap-3 items-end">{field('id','شناسه رکورد','number')}<button disabled={busy} onClick={()=>void execute(action)} className="rounded-xl bg-red-600 px-5 py-2.5 font-semibold text-white">{labels[action]}</button></div>;
  if(action==='set-prompt')return <div className="grid md:grid-cols-2 gap-3">{field('name','نام پرامپت')}{field('value','متن پرامپت')}<button disabled={busy} onClick={()=>void execute(action)} className="md:col-span-2 rounded-xl bg-cyan-600 px-5 py-2.5 font-semibold text-white">ثبت پرامپت</button></div>;
  if(action==='set-channel')return <div className="flex gap-3 items-end">{field('channel','کانال','text','stable')}<button disabled={busy} onClick={()=>void execute(action)} className="rounded-xl bg-cyan-600 px-5 py-2.5 font-semibold text-white">تغییر کانال</button></div>;
  return <div className="grid md:grid-cols-2 gap-3">{field('key','کلید')}{field('value','مقدار')}{field('id','شناسه هدف','number')}<button disabled={busy} onClick={()=>void execute(action)} className="md:col-span-2 rounded-xl bg-cyan-600 px-5 py-2.5 font-semibold text-white">{labels[action]||action}</button></div>;
 };
 const renderDashboard=()=> <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-4">{[['کل کاربران',dashboard?.totalUsers],['اشتراک فعال',dashboard?.activeSubscriptions],['کل تحلیل‌ها',dashboard?.totalAnalyses],['API Key',dashboard?.totalApiKeys],['اعلان‌ها',dashboard?.totalNotifications],['کاربران آنلاین',onlineCount],['ماژول‌های فعال',modulesState.filter(x=>x.enabled).length],['ماژول‌ها',23]].map(([t,v])=><div key={String(t)} className="rounded-2xl border border-[var(--card-border-color)] bg-[var(--card-bg)] p-5"><div className="text-sm text-gray-500">{t}</div><div className="mt-2 text-3xl font-extrabold">{fmt(Number(v)||0)}</div></div>)}</div>;
 const renderAudit=()=> <div className="overflow-auto rounded-2xl border border-[var(--card-border-color)] bg-[var(--card-bg)]"><table className="w-full text-sm"><thead><tr className="border-b"><th className="p-3 text-right">عملیات</th><th className="p-3 text-right">ماژول</th><th className="p-3 text-right">مسیر</th><th className="p-3 text-right">وضعیت</th><th className="p-3 text-right">زمان</th></tr></thead><tbody>{audit.map((r,i)=><tr key={String(r.id||i)} className="border-b"><td className="p-3">{String(r.action||'-')}</td><td className="p-3">{modules.find(m=>m.id===r.moduleKey)?.title||String(r.moduleKey||'-')}</td><td className="p-3 ltr">{String(r.path||'-')}</td><td className="p-3">{String(r.statusCode||'-')}</td><td className="p-3">{r.createdAt?new Date(String(r.createdAt)).toLocaleString('fa-IR'):'-'}</td></tr>)}</tbody></table>{!audit.length&&<div className="p-8 text-center text-gray-500">رویدادی ثبت نشده است.</div>}</div>;
 return <div dir="rtl" className="mx-auto max-w-[1600px] space-y-5"><div className="rounded-2xl border border-[var(--card-border-color)] bg-[var(--card-bg)] p-5"><h1 className="text-2xl font-extrabold">مرکز کنترل مدیریت رونیا</h1><p className="mt-2 text-sm text-gray-500">۲۳ ماژول مدیریتی با عملیات واقعی، API، احراز هویت و Audit Log</p></div><div className="grid grid-cols-1 lg:grid-cols-[270px_minmax(0,1fr)] gap-5"><aside className="rounded-2xl border border-[var(--card-border-color)] bg-[var(--card-bg)] p-3 lg:sticky lg:top-4"><div className="mb-2 px-3 py-2 text-xs font-bold text-gray-500">۲۳ بخش مدیریت</div><div className="grid grid-cols-2 lg:grid-cols-1 gap-1 max-h-[72vh] overflow-auto">{modules.map(m=><button key={m.id} onClick={()=>setSection(m.id)} className={`flex items-center gap-2 rounded-xl px-3 py-2.5 text-right text-sm ${section===m.id?'bg-cyan-600 text-white':'hover:bg-gray-100 dark:hover:bg-gray-800'}`}><span>{m.icon}</span><span className="truncate">{m.title}</span></button>)}</div></aside><main className="min-w-0 space-y-4"><div className="flex items-center justify-between"><div><h2 className="text-lg font-bold">{active.title}</h2><p className="text-xs text-gray-500 mt-1">{active.description}</p></div><button onClick={()=>void load()} className="rounded-lg border px-4 py-2 text-sm">به‌روزرسانی</button></div>{error&&<div className="rounded-xl bg-red-50 p-4 text-red-700">{error}</div>}{message&&<div className="rounded-xl bg-green-50 p-4 text-green-700">{message}</div>}{loading?<div className="py-16 text-center text-gray-500">در حال بارگذاری...</div>:section==='dashboard'?renderDashboard():section==='audit'?renderAudit():<><div className="grid grid-cols-2 md:grid-cols-4 gap-3">{Object.entries(overview?.counts||{}).map(([k,v])=><div key={k} className="rounded-xl border border-[var(--card-border-color)] bg-[var(--card-bg)] p-4"><div className="text-xs text-gray-500">{k}</div><div className="mt-1 font-bold">{fmt(Number(v)||0)}</div></div>)}</div><div className="rounded-2xl border border-[var(--card-border-color)] bg-[var(--card-bg)] p-5"><div className="mb-4 flex items-center justify-between"><h3 className="font-bold">عملیات اختصاصی {active.title}</h3><span className="text-xs text-gray-500">{capabilities?.actions.length||0} عملیات</span></div>{capabilities?.actions.length?<div className="space-y-5">{capabilities.actions.map(action=><div key={action} className="rounded-xl border border-[var(--card-border-color)] p-4"><div className="mb-3 font-semibold">{labels[action]||action}</div>{renderActionForm(action)}</div>)}</div>:<div className="text-sm text-gray-500">برای این بخش هنوز عملیات تراکنشی تعریف نشده است.</div>}</div></>}</main></div></div>;
};

export default AdminPanelV2;
