import React,{useCallback,useEffect,useState}from'react';
import*as service from'../services/adminAnalysesService';
const fa=(v:number)=>v.toLocaleString('fa-IR');
const pct=(v:number)=>`${v.toLocaleString('fa-IR',{maximumFractionDigits:1})}٪`;
const date=(v?:string|null)=>v?new Date(v).toLocaleString('fa-IR'):'—';
const typeLabels:Record<string,string>={technical:'تکنیکال',fundamental:'بنیادی',comparison:'مقایسه',scalping:'نوسان‌گیری',summary:'خلاصه بازار',portfolio:'سبد سرمایه‌گذاری',other:'سایر'};
const types=[['','همه انواع تحلیل'],['technical','تکنیکال'],['fundamental','بنیادی'],['comparison','مقایسه'],['scalping','نوسان‌گیری'],['summary','خلاصه بازار'],['portfolio','سبد سرمایه‌گذاری']];
export default function AdminAnalysesPanel(){
 const[data,setData]=useState<service.AdminAnalysesResult|null>(null),[analytics,setAnalytics]=useState<service.AdminAnalysisAnalytics|null>(null),[page,setPage]=useState(1),[search,setSearch]=useState(''),[symbol,setSymbol]=useState(''),[status,setStatus]=useState(''),[type,setType]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[loading,setLoading]=useState(false),[analyticsLoading,setAnalyticsLoading]=useState(false),[error,setError]=useState(''),[selected,setSelected]=useState<service.AdminAnalysisItem|null>(null);
 const load=useCallback(async()=>{setLoading(true);setError('');try{setData(await service.getAnalyses({page,limit:20,search,symbol,status,type,from,to}));}catch(e){setError(e instanceof Error?e.message:'خطا در دریافت تحلیل‌ها.');}finally{setLoading(false)}},[page,search,symbol,status,type,from,to]);
 const loadAnalytics=useCallback(async()=>{setAnalyticsLoading(true);try{setAnalytics(await service.getAnalytics());}catch(e){setError(e instanceof Error?e.message:'خطا در دریافت آمار مصرف.');}finally{setAnalyticsLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);useEffect(()=>{void loadAnalytics()},[loadAnalytics]);
 const refresh=()=>{void Promise.all([load(),loadAnalytics()])};
 const reset=()=>{setPage(1);setSearch('');setSymbol('');setStatus('');setType('');setFrom('');setTo('')};
 const remove=async(id:number)=>{if(!window.confirm('آیا از حذف این تحلیل مطمئن هستید؟ این عملیات در Audit Log ثبت می‌شود.'))return;try{await service.deleteAnalysis(id);setSelected(null);await Promise.all([load(),loadAnalytics()])}catch(e){setError(e instanceof Error?e.message:'حذف تحلیل ناموفق بود.')}};
 const s=data?.summary,a=analytics;
 return <div dir="rtl" className="space-y-5">
  <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold">مرکز مدیریت تحلیل‌ها و مصرف منابع</h2><p className="mt-1 text-sm text-gray-500">آمار واقعی مصرف، تحلیل‌های پرتکرار و کنترل نتایج ذخیره‌شده</p></div><button onClick={refresh} disabled={loading||analyticsLoading} className="rounded-xl border px-4 py-2.5 font-semibold disabled:opacity-50">{loading||analyticsLoading?'در حال بروزرسانی...':'بروزرسانی همه'}</button></div>
  <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
   {[['کل تحلیل‌ها',a?.total||0],['۲۴ ساعت اخیر',a?.last24h||0],['۷ روز اخیر',a?.last7d||0],['۳۰ روز اخیر',a?.last30d||0]].map(([l,v])=><div key={l} className="rounded-2xl border bg-[var(--card-bg)] p-4"><span className="text-xs text-gray-500">{l}</span><b className="block mt-2 text-2xl">{fa(Number(v))}</b></div>)}
  </div>
  <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
   <div className="rounded-2xl border bg-[var(--card-bg)] p-4"><span className="text-xs text-gray-500">تکمیل‌شده</span><b className="block mt-2 text-xl">{fa(a?.completed||0)}</b></div>
   <div className="rounded-2xl border bg-[var(--card-bg)] p-4"><span className="text-xs text-gray-500">ناموفق</span><b className="block mt-2 text-xl">{fa(a?.failed||0)}</b><small className="text-gray-500">نرخ خطا: {pct(a?.failedRate||0)}</small></div>
   <div className="rounded-2xl border bg-[var(--card-bg)] p-4"><span className="text-xs text-gray-500">در انتظار</span><b className="block mt-2 text-xl">{fa(a?.pending||0)}</b></div>
   <div className="rounded-2xl border bg-[var(--card-bg)] p-4"><span className="text-xs text-gray-500">دارای نتیجه</span><b className="block mt-2 text-xl">{fa(a?.withResult||0)}</b></div>
  </div>
  <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
   <div className="rounded-2xl border bg-[var(--card-bg)] p-4"><h3 className="font-bold mb-4">مصرف بر اساس نوع تحلیل</h3><div className="space-y-3">{Object.entries(a?.byType||{}).sort((x,y)=>y[1]-x[1]).map(([k,v])=><div key={k}><div className="flex justify-between text-sm"><span>{typeLabels[k]||k}</span><b>{fa(v)}</b></div><div className="mt-1 h-2 rounded-full bg-gray-100 dark:bg-gray-800 overflow-hidden"><div className="h-full rounded-full bg-current opacity-70" style={{width:`${a?.total?Math.max(2,v*100/a.total):0}%`}}/></div></div>)}{!a&&<span className="text-sm text-gray-500">در حال دریافت...</span>}</div></div>
   <div className="rounded-2xl border bg-[var(--card-bg)] p-4"><h3 className="font-bold mb-4">پرتکرارترین نمادها</h3><div className="space-y-2">{(a?.topSymbols||[]).map((x,i)=><div key={x.symbol} className="flex items-center justify-between rounded-xl border p-2.5"><span><span className="text-xs text-gray-400 ml-2">{fa(i+1)}</span><b>{x.symbol}</b></span><span className="text-sm">{fa(x.count)} تحلیل</span></div>)}{a&&!a.topSymbols.length&&<span className="text-sm text-gray-500">داده‌ای موجود نیست.</span>}</div></div>
   <div className="rounded-2xl border bg-[var(--card-bg)] p-4"><h3 className="font-bold mb-4">پرتکرارترین کاربران</h3><div className="space-y-2">{(a?.topUsers||[]).map((x,i)=><div key={x.user} className="flex items-center justify-between rounded-xl border p-2.5"><span className="truncate max-w-[60%]"><span className="text-xs text-gray-400 ml-2">{fa(i+1)}</span>{x.user}</span><span className="text-sm">{fa(x.count)} تحلیل</span></div>)}{a&&!a.topUsers.length&&<span className="text-sm text-gray-500">داده‌ای موجود نیست.</span>}</div></div>
  </div>
  <div className="rounded-2xl border bg-[var(--card-bg)] p-4"><h3 className="font-bold mb-3">فیلتر و مدیریت نتایج</h3><div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-3"><input value={search} onChange={e=>{setPage(1);setSearch(e.target.value)}} placeholder="جستجوی نام کاربری یا ایمیل" className="rounded-xl border p-3 bg-transparent"/><input value={symbol} onChange={e=>{setPage(1);setSymbol(e.target.value)}} placeholder="نماد" className="rounded-xl border p-3 bg-transparent"/><select value={type} onChange={e=>{setPage(1);setType(e.target.value)}} className="rounded-xl border p-3 bg-transparent">{types.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><select value={status} onChange={e=>{setPage(1);setStatus(e.target.value)}} className="rounded-xl border p-3 bg-transparent"><option value="">همه وضعیت‌ها</option><option value="completed">تکمیل‌شده</option><option value="failed">ناموفق</option><option value="pending">در انتظار</option></select><label className="text-xs text-gray-500">از تاریخ<input type="date" value={from} onChange={e=>{setPage(1);setFrom(e.target.value)}} className="mt-1 block w-full rounded-xl border p-2.5 bg-transparent"/></label><label className="text-xs text-gray-500">تا تاریخ<input type="date" value={to} onChange={e=>{setPage(1);setTo(e.target.value)}} className="mt-1 block w-full rounded-xl border p-2.5 bg-transparent"/></label><button onClick={reset} className="rounded-xl border px-4 py-3 font-semibold">پاک‌سازی فیلترها</button><button onClick={()=>void load()} disabled={loading} className="rounded-xl border px-4 py-3 font-semibold disabled:opacity-50">{loading?'در حال دریافت...':'اعمال فیلتر'}</button></div></div>
  {error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
  <div className="overflow-x-auto rounded-2xl border bg-[var(--card-bg)]"><table className="w-full text-sm"><thead><tr className="border-b text-right"><th className="p-4">کاربر</th><th className="p-4">نماد</th><th className="p-4">نوع</th><th className="p-4">زمان</th><th className="p-4">وضعیت</th><th className="p-4">نتیجه</th><th className="p-4">عملیات</th></tr></thead><tbody>{loading&&!data?<tr><td colSpan={7} className="p-8 text-center text-gray-500">در حال بارگذاری...</td></tr>:data?.items.length?data.items.map(x=><tr key={x.id} className="border-b last:border-0"><td className="p-4"><b>{x.name||x.username}</b><div className="text-xs text-gray-500">{x.email||x.username}</div></td><td className="p-4 font-bold">{x.symbol}</td><td className="p-4">{x.analysisType}</td><td className="p-4 whitespace-nowrap">{date(x.createdAt)}</td><td className="p-4">{x.statusLabel}</td><td className="p-4">{x.hasResult?'موجود':'بدون نتیجه'}</td><td className="p-4"><div className="flex gap-2"><button onClick={()=>setSelected(x)} className="rounded-lg border px-3 py-1.5">جزئیات</button><button onClick={()=>void remove(x.id)} className="rounded-lg border border-red-300 px-3 py-1.5 text-red-600">حذف</button></div></td></tr>):<tr><td colSpan={7} className="p-8 text-center text-gray-500">تحلیلی یافت نشد.</td></tr>}</tbody></table></div>
  <div className="flex items-center justify-between"><span className="text-sm text-gray-500">صفحه {fa(data?.pagination.page||page)} از {fa(data?.pagination.totalPages||0)} — {fa(data?.pagination.total||0)} نتیجه</span><div className="flex gap-2"><button disabled={page<=1||loading} onClick={()=>setPage(p=>p-1)} className="rounded-xl border px-4 py-2 disabled:opacity-40">قبلی</button><button disabled={page>=(data?.pagination.totalPages||1)||loading} onClick={()=>setPage(p=>p+1)} className="rounded-xl border px-4 py-2 disabled:opacity-40">بعدی</button></div></div>
  {selected&&<div className="fixed inset-0 z-50 bg-black/40 flex items-center justify-center p-4" onClick={()=>setSelected(null)}><div onClick={e=>e.stopPropagation()} className="w-full max-w-2xl max-h-[85vh] overflow-auto rounded-2xl bg-[var(--card-bg)] p-6"><div className="flex justify-between"><h3 className="text-lg font-bold">جزئیات تحلیل #{fa(selected.id)}</h3><button onClick={()=>setSelected(null)}>✕</button></div><div className="grid grid-cols-2 gap-3 mt-5 text-sm"><div>کاربر: <b>{selected.username}</b></div><div>نماد: <b>{selected.symbol}</b></div><div>نوع: <b>{selected.analysisType}</b></div><div>نتیجه: <b>{selected.hasResult?'موجود':'بدون نتیجه'}</b></div><div>وضعیت: <b>{selected.statusLabel}</b></div><div>زمان: <b>{date(selected.createdAt)}</b></div></div>{selected.result&&<pre dir="ltr" className="mt-5 rounded-xl bg-gray-50 dark:bg-gray-900 p-4 text-xs whitespace-pre-wrap">{selected.result}</pre>}<button onClick={()=>void remove(selected.id)} className="mt-5 rounded-xl bg-red-600 text-white px-4 py-2">حذف تحلیل</button></div></div>}
 </div>}
