import React,{useCallback,useEffect,useMemo,useState}from'react';
import*as apiClient from'../services/apiClient';
import*as adminActionsService from'../services/adminActionsService';
interface Props{onComplete?:()=>Promise<void>|void}
interface MarketResponse{success?:boolean;data?:any;message?:string}
const card='rounded-2xl border border-[var(--card-border-color)] bg-[var(--card-bg)] p-5 shadow-sm';
const fmt=(v:any)=>typeof v==='number'?v.toLocaleString('fa-IR',{maximumFractionDigits:2}):v==null?'—':String(v);
const date=(v:any)=>v?new Date(v).toLocaleString('fa-IR'):'—';
const unwrap=(r:MarketResponse)=>{if(!r?.success)throw new Error(r?.message||'دریافت اطلاعات بازار ناموفق بود.');return r.data??r};
const pick=(o:any,keys:string[])=>{for(const k of keys){if(o?.[k]!=null)return o[k]}return null};
export default function AdminMarketPanel({onComplete=()=>undefined}:Props){
 const[data,setData]=useState<any>(null),[summary,setSummary]=useState<any>(null),[history,setHistory]=useState<any[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[message,setMessage]=useState<string|null>(null);
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const [i,s,h]=await Promise.all([apiClient.get<any>('/v1/market/index'),apiClient.get<any>('/v1/market/summary'),apiClient.get<any>('/v1/market/history?limit=20')]);setData(unwrap(i));setSummary(unwrap(s));const hd=unwrap(h);setHistory(Array.isArray(hd)?hd:Array.isArray(hd?.items)?hd.items:Array.isArray(hd?.data)?hd.data:[]);}catch(e){setError(e instanceof Error?e.message:'خطا در دریافت داده بازار.');}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 const clearCache=async()=>{if(!window.confirm('کش داده بازار پاک شود؟ این عملیات روی سرویس بازار اثر می‌گذارد.'))return;setBusy(true);setError(null);setMessage(null);try{await adminActionsService.executeAction('market','health-check',{clearCache:true});setMessage('درخواست بررسی/به‌روزرسانی بازار با موفقیت اجرا شد.');await load();await onComplete()}catch(e){setError(e instanceof Error?e.message:'اجرای عملیات بازار ناموفق بود.')}finally{setBusy(false)}};
 const index=pick(data,['index','marketIndex','value']);const change=pick(data,['change','indexChange','changePercent']);const mv=pick(data,['marketValue','mv']);const updated=pick(data,['updatedAt','timestamp','lastUpdate','date']);
 const stats=useMemo(()=>({positive:pick(summary,['positive','up','gainers']),negative:pick(summary,['negative','down','losers']),unchanged:pick(summary,['unchanged','neutral']),count:pick(summary,['totalSymbols','symbolCount','count'])}),[summary]);
 return <div dir="rtl" className="space-y-5">{error&&<div className="rounded-xl border border-red-300 bg-red-50 px-4 py-3 text-sm text-red-700 dark:bg-red-950/20 dark:text-red-300">{error}</div>}{message&&<div className="rounded-xl border border-emerald-300 bg-emerald-50 px-4 py-3 text-sm text-emerald-700 dark:bg-emerald-950/20 dark:text-emerald-300">{message}</div>}
  <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-extrabold">مرکز مدیریت بازار</h2><p className="mt-1 text-sm text-gray-500">پایش داده‌های بازار، شاخص، خلاصه معاملات و وضعیت بروزرسانی</p></div><div className="flex gap-2"><button onClick={()=>void load()} disabled={loading} className="rounded-xl border border-[var(--card-border-color)] px-4 py-2 text-sm font-semibold">{loading?'در حال دریافت…':'به‌روزرسانی'}</button><button onClick={()=>void clearCache()} disabled={busy} className="rounded-xl bg-cyan-600 px-4 py-2 text-sm font-semibold text-white">{busy?'در حال اجرا…':'پاک‌سازی کش و بررسی بازار'}</button></div></div>
  <div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-4"><div className={card}><div className="text-sm text-gray-500">شاخص بازار</div><div className="mt-2 text-2xl font-extrabold">{fmt(index)}</div><div className="mt-1 text-xs text-gray-500">آخرین مقدار دریافت‌شده</div></div><div className={card}><div className="text-sm text-gray-500">تغییر شاخص</div><div className="mt-2 text-2xl font-extrabold">{fmt(change)}</div><div className="mt-1 text-xs text-gray-500">تغییر ثبت‌شده در API</div></div><div className={card}><div className="text-sm text-gray-500">ارزش بازار</div><div className="mt-2 text-2xl font-extrabold">{fmt(mv)}</div><div className="mt-1 text-xs text-gray-500">در صورت ارائه توسط منبع</div></div><div className={card}><div className="text-sm text-gray-500">آخرین بروزرسانی</div><div className="mt-2 text-lg font-bold">{date(updated)}</div><div className="mt-1 text-xs text-gray-500">زمان داده بازار</div></div></div>
  <div className="grid grid-cols-2 gap-4 md:grid-cols-4"><div className={card}><div className="text-xs text-gray-500">نمادهای مثبت</div><div className="mt-2 text-xl font-bold">{fmt(stats.positive)}</div></div><div className={card}><div className="text-xs text-gray-500">نمادهای منفی</div><div className="mt-2 text-xl font-bold">{fmt(stats.negative)}</div></div><div className={card}><div className="text-xs text-gray-500">بدون تغییر</div><div className="mt-2 text-xl font-bold">{fmt(stats.unchanged)}</div></div><div className={card}><div className="text-xs text-gray-500">تعداد نمادها</div><div className="mt-2 text-xl font-bold">{fmt(stats.count)}</div></div></div>
  <div className={card}><div className="mb-4 flex items-center justify-between"><div><h3 className="font-bold">آخرین داده‌های تاریخچه بازار</h3><p className="text-xs text-gray-500">برای تشخیص توقف بروزرسانی یا داده‌های قدیمی</p></div><span className="rounded-full bg-gray-100 px-3 py-1 text-xs dark:bg-gray-800">{fmt(history.length)} رکورد</span></div>{history.length===0?<div className="rounded-xl bg-gray-50 p-6 text-center text-sm text-gray-500 dark:bg-gray-900/40">رکورد تاریخچه‌ای از API دریافت نشد.</div>:<div className="overflow-x-auto"><table className="w-full min-w-[720px] text-right text-sm"><thead><tr className="border-b border-[var(--card-border-color)] text-gray-500"><th className="px-3 py-3">زمان</th><th className="px-3 py-3">شاخص</th><th className="px-3 py-3">تغییر</th><th className="px-3 py-3">ارزش بازار</th><th className="px-3 py-3">وضعیت داده</th></tr></thead><tbody>{history.map((r,i)=><tr key={r.id??i} className="border-b border-[var(--card-border-color)] last:border-0"><td className="px-3 py-3">{date(pick(r,['createdAt','timestamp','date','time']))}</td><td className="px-3 py-3 font-semibold">{fmt(pick(r,['index','marketIndex','value']))}</td><td className="px-3 py-3">{fmt(pick(r,['change','indexChange','changePercent']))}</td><td className="px-3 py-3">{fmt(pick(r,['marketValue','mv']))}</td><td className="px-3 py-3"><span className="rounded-full bg-emerald-100 px-2 py-1 text-xs text-emerald-700 dark:bg-emerald-950/30 dark:text-emerald-300">دریافت‌شده</span></td></tr>)}</tbody></table></div>}</div>
 </div>;
}