import React, { useCallback, useEffect, useMemo, useState } from 'react';
import * as adminActionsService from '../services/adminActionsService';
interface Props { onComplete?: () => Promise<void> | void; }
interface ApiKeyRow { id: number|string; userId?: number|string|null; username?: string|null; email?: string|null; name?: string|null; service?: string|null; createdAt?: string|null; isRevoked?: boolean; }
const fmtDate=(v?:string|null)=>v?new Date(v).toLocaleString('fa-IR'):'—';
const AdminApiKeysPanel:React.FC<Props>=({onComplete=()=>undefined})=>{
 const [rows,setRows]=useState<ApiKeyRow[]>([]),[loading,setLoading]=useState(true),[busyId,setBusyId]=useState<number|string|null>(null),[error,setError]=useState<string|null>(null),[query,setQuery]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const result=await adminActionsService.executeAction<unknown[]>('api','list-api-keys',{});setRows(Array.isArray(result)?result as ApiKeyRow[]:[]);}catch(e){setError(e instanceof Error?e.message:'دریافت کلیدهای API ناموفق بود.');}finally{setLoading(false);}},[]);
 useEffect(()=>{void load();},[load]);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return rows;return rows.filter(r=>[r.id,r.userId,r.username,r.email,r.name,r.service].some(v=>String(v??'').toLowerCase().includes(q)));},[rows,query]);
 const revoke=async(id:number|string)=>{if(!window.confirm('آیا از لغو این API Key مطمئن هستید؟'))return;setBusyId(id);setError(null);try{await adminActionsService.executeAction('api','revoke-api-key',{apiKeyId:Number(id)});await load();await onComplete();}catch(e){setError(e instanceof Error?e.message:'لغو API Key ناموفق بود.');}finally{setBusyId(null);}};
 return <div dir="rtl" className="space-y-5">
  <div className="rounded-2xl border border-[var(--card-border-color)] bg-[var(--card-bg)] p-5"><div className="flex flex-col md:flex-row md:items-center justify-between gap-3"><div><h3 className="text-lg font-bold">مدیریت کلیدهای API</h3><p className="mt-1 text-sm text-gray-500">کلیدها بدون نمایش مقدار واقعی مدیریت می‌شوند.</p></div><button onClick={()=>void load()} disabled={loading} className="rounded-xl border px-4 py-2 text-sm disabled:opacity-50">{loading?'در حال دریافت...':'به‌روزرسانی'}</button></div><div className="mt-4 grid grid-cols-1 md:grid-cols-[1fr_auto] gap-3"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="جستجو بر اساس شناسه، کاربر، ایمیل یا نام کلید" className="rounded-xl border bg-transparent px-4 py-2.5 text-sm"/><div className="rounded-xl bg-gray-50 dark:bg-gray-800/50 px-4 py-2.5 text-sm">کلیدها: <b>{filtered.length.toLocaleString('fa-IR')}</b></div></div></div>
  {error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
  <div className="rounded-2xl border border-[var(--card-border-color)] bg-[var(--card-bg)] overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead><tr className="border-b bg-gray-50/70 dark:bg-gray-800/40"><th className="p-3 text-right">شناسه</th><th className="p-3 text-right">مالک</th><th className="p-3 text-right">نام کلید</th><th className="p-3 text-right">سرویس</th><th className="p-3 text-right">تاریخ ایجاد</th><th className="p-3 text-right">وضعیت</th><th className="p-3 text-right">عملیات</th></tr></thead><tbody>{filtered.map(r=><tr key={String(r.id)} className="border-b hover:bg-gray-50/50 dark:hover:bg-gray-800/20"><td className="p-3" dir="ltr">{r.id}</td><td className="p-3"><div className="font-semibold">{r.username||('کاربر '+(r.userId??'—'))}</div><div className="text-xs text-gray-500">{r.email||'—'}</div></td><td className="p-3">{r.name||'بدون نام'}</td><td className="p-3">{r.service||'عمومی'}</td><td className="p-3 whitespace-nowrap">{fmtDate(r.createdAt)}</td><td className="p-3">{r.isRevoked?<span className="rounded-full bg-red-100 px-2.5 py-1 text-xs text-red-700">لغوشده</span>:<span className="rounded-full bg-green-100 px-2.5 py-1 text-xs text-green-700">فعال</span>}</td><td className="p-3">{r.isRevoked?<span className="text-xs text-gray-500">غیرفعال</span>:<button disabled={busyId===r.id} onClick={()=>void revoke(r.id)} className="rounded-lg border border-red-500/50 px-3 py-1.5 text-xs font-semibold text-red-600 disabled:opacity-50">{busyId===r.id?'در حال لغو...':'لغو کلید'}</button>}</td></tr>)}</tbody></table></div>{!loading&&filtered.length===0&&<div className="py-10 text-center text-gray-500">کلیدی مطابق جستجو پیدا نشد.</div>}</div>
 </div>;
};
export default AdminApiKeysPanel;
