import React, { useCallback, useEffect, useMemo, useState } from 'react';
import * as adminService from '../services/adminService';
import type { AdminUserListItem } from '../types';
import { useNotification } from './NotificationSystem';

type UserRow = AdminUserListItem & { subscriptionType?: string | null; analysisLimit24h?: number; analysisUsed24h?: number; };
type Filter = 'all' | 'active' | 'expired' | 'expiring';

const card='rounded-2xl border border-[var(--card-border-color)] bg-[var(--card-bg)] p-5';
const input='w-full rounded-xl border border-[var(--card-border-color)] bg-transparent px-3 py-2.5 text-sm outline-none focus:ring-2 focus:ring-cyan-500/30';
const fmt=(v:number|undefined|null)=>Number(v||0).toLocaleString('fa-IR');
const dateFmt=(v:string|null|undefined)=>v?new Date(v).toLocaleDateString('fa-IR'):'—';
const status=(u:UserRow):'active'|'expired'|'expiring'=>u.isSubscriptionActive?(u.remainingDays<=7?'expiring':'active'):'expired';

const AdminSubscriptionsPanel:React.FC=()=>{
 const [users,setUsers]=useState<UserRow[]>([]); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState<string|null>(null); const [error,setError]=useState<string|null>(null); const [search,setSearch]=useState(''); const [filter,setFilter]=useState<Filter>('all'); const [page,setPage]=useState(1); const [total,setTotal]=useState(0); const [totalPages,setTotalPages]=useState(0); const [selected,setSelected]=useState<UserRow|null>(null); const {addNotification}=useNotification();
 const [form,setForm]=useState({isActive:true,type:'standard',start:'',end:'',days:'30',months:'0',limit:'20',limit24h:'20'});
 const load=useCallback(async(target=page)=>{setLoading(true);setError(null);try{const r=await adminService.getUsers({page:target,limit:20,search});setUsers(r.users as UserRow[]);setTotal(r.pagination.total);setTotalPages(r.pagination.totalPages);setPage(r.pagination.page);}catch(e){setError(e instanceof Error?e.message:'دریافت اشتراک‌ها ناموفق بود.');}finally{setLoading(false);}},[page,search]);
 useEffect(()=>{const t=window.setTimeout(()=>void load(1),300);return()=>window.clearTimeout(t);},[search]);
 const visible=useMemo(()=>users.filter(u=>filter==='all'||status(u)===filter),[users,filter]);
 const stats=useMemo(()=>({active:users.filter(u=>status(u)==='active').length,expired:users.filter(u=>status(u)==='expired').length,expiring:users.filter(u=>status(u)==='expiring').length}),[users]);
 const open=async(u:UserRow)=>{setSelected(u);setForm({isActive:u.isSubscriptionActive,type:u.subscriptionType||'standard',start:u.subscriptionStart?new Date(u.subscriptionStart).toISOString().slice(0,10):'',end:u.subscriptionEnd?new Date(u.subscriptionEnd).toISOString().slice(0,10):'',days:String(u.subscriptionDays||0),months:String(u.subscriptionMonths||0),limit:String(u.analysisLimit||0),limit24h:String(u.analysisLimit24h||u.analysisLimit||0)});};
 const save=async()=>{if(!selected)return;setBusy(String(selected.id));try{const days=Math.max(0,Number(form.days)||0);const months=Math.max(0,Number(form.months)||0);let start=form.start||undefined;let end=form.end||undefined;if(days>0&&!start)start=new Date().toISOString().slice(0,10);if(days>0){const d=new Date(`${start}T00:00:00`);d.setDate(d.getDate()+days);end=d.toISOString().slice(0,10);}await adminService.updateSubscription({userId:selected.id,isSubscriptionActive:form.isActive,subscriptionStart:start||null,subscriptionEnd:end||null,subscriptionDays:days,subscriptionMonths:months,analysisLimit:Math.max(0,Number(form.limit)||0),analysisLimit24h:Math.max(0,Number(form.limit24h)||0),subscriptionType:form.type});addNotification('اشتراک کاربر با موفقیت به‌روزرسانی شد.','success');setSelected(null);await load(page);}catch(e){addNotification(e instanceof Error?e.message:'به‌روزرسانی اشتراک ناموفق بود.','error');}finally{setBusy(null);}};
 return <div className="space-y-5" dir="rtl">
  <div><h2 className="text-2xl font-bold">اشتراک‌ها و اعتبار</h2><p className="mt-1 text-sm text-gray-500">مدیریت وضعیت اشتراک، تمدید، سقف تحلیل و کاربران نزدیک به انقضا</p></div>
  {error&&<div className="rounded-xl border border-red-300 bg-red-50 p-3 text-red-700">{error}</div>}
  <div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><div className={card}><div className="text-xs text-gray-500">فعال</div><b className="text-2xl text-green-600">{fmt(stats.active)}</b></div><div className={card}><div className="text-xs text-gray-500">در آستانه انقضا</div><b className="text-2xl text-amber-600">{fmt(stats.expiring)}</b></div><div className={card}><div className="text-xs text-gray-500">منقضی</div><b className="text-2xl text-red-600">{fmt(stats.expired)}</b></div><div className={card}><div className="text-xs text-gray-500">کل نتایج</div><b className="text-2xl">{fmt(total)}</b></div></div>
  <div className={card}><div className="grid grid-cols-1 md:grid-cols-2 gap-3"><input className={input} value={search} onChange={e=>setSearch(e.target.value)} placeholder="جستجوی نام، نام کاربری، ایمیل یا موبایل"/><select className={input} value={filter} onChange={e=>setFilter(e.target.value as Filter)}><option value="all">همه اشتراک‌ها</option><option value="active">فعال</option><option value="expiring">در آستانه انقضا (۷ روز)</option><option value="expired">منقضی</option></select></div>
   <div className="mt-4 overflow-auto"><table className="w-full min-w-[900px] text-sm"><thead><tr className="border-b"><th className="p-3 text-right">کاربر</th><th className="p-3 text-right">نوع اشتراک</th><th className="p-3 text-right">شروع</th><th className="p-3 text-right">پایان</th><th className="p-3 text-right">اعتبار</th><th className="p-3 text-right">سقف تحلیل</th><th className="p-3 text-right">وضعیت</th><th className="p-3 text-right">عملیات</th></tr></thead><tbody>{visible.map(u=>{const s=status(u);return <tr key={u.id} className="border-b last:border-0 hover:bg-gray-50/50 dark:hover:bg-gray-800/30"><td className="p-3"><div className="font-semibold">{u.name||u.username}</div><div className="text-xs text-gray-500">@{u.username}</div></td><td className="p-3">{u.subscriptionType||'رایگان'}</td><td className="p-3">{dateFmt(u.subscriptionStart)}</td><td className="p-3">{dateFmt(u.subscriptionEnd)}</td><td className="p-3">{s==='expired'?'منقضی':`${fmt(u.remainingDays)} روز`}</td><td className="p-3">{fmt(u.analysisLimit)}</td><td className="p-3"><span className={s==='active'?'text-green-600':s==='expiring'?'text-amber-600':'text-red-600'}>{s==='active'?'فعال':s==='expiring'?'نزدیک به انقضا':'منقضی'}</span></td><td className="p-3"><button onClick={()=>void open(u)} className="rounded-lg border px-3 py-1.5 font-medium hover:bg-cyan-50 dark:hover:bg-cyan-950/20">مدیریت اشتراک</button></td></tr>})}{!visible.length&&<tr><td colSpan={8} className="p-8 text-center text-gray-500">اشتراکی با این فیلتر پیدا نشد.</td></tr>}</tbody></table></div>
   <div className="mt-4 flex items-center justify-between gap-3"><span className="text-xs text-gray-500">صفحه {fmt(page)} از {fmt(totalPages)}</span><div className="flex gap-2"><button disabled={page<=1||loading} onClick={()=>void load(page-1)} className="rounded-lg border px-3 py-2 disabled:opacity-40">قبلی</button><button disabled={page>=totalPages||loading} onClick={()=>void load(page+1)} className="rounded-lg border px-3 py-2 disabled:opacity-40">بعدی</button></div></div>
  </div>
  {selected&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><div className="w-full max-w-2xl rounded-2xl border border-[var(--card-border-color)] bg-[var(--card-bg)] p-5 shadow-xl"><div className="flex items-center justify-between"><div><h3 className="text-xl font-bold">مدیریت اشتراک</h3><p className="text-sm text-gray-500">{selected.name||selected.username} · @{selected.username}</p></div><button onClick={()=>setSelected(null)} className="rounded-lg border px-3 py-1">بستن</button></div><div className="mt-5 grid grid-cols-1 md:grid-cols-2 gap-3"><label className="space-y-1"><span className="text-sm">نوع اشتراک</span><select className={input} value={form.type} onChange={e=>setForm(f=>({...f,type:e.target.value}))}><option value="free">رایگان</option><option value="standard">استاندارد</option><option value="premium">ویژه</option><option value="enterprise">سازمانی</option></select></label><label className="space-y-1"><span className="text-sm">وضعیت</span><select className={input} value={form.isActive?'active':'inactive'} onChange={e=>setForm(f=>({...f,isActive:e.target.value==='active'}))}><option value="active">فعال</option><option value="inactive">غیرفعال</option></select></label><label className="space-y-1"><span className="text-sm">تاریخ شروع</span><input type="date" className={input} value={form.start} onChange={e=>setForm(f=>({...f,start:e.target.value}))}/></label><label className="space-y-1"><span className="text-sm">تاریخ پایان</span><input type="date" className={input} value={form.end} onChange={e=>setForm(f=>({...f,end:e.target.value}))}/></label><label className="space-y-1"><span className="text-sm">مدت اشتراک (روز)</span><input type="number" min="0" className={input} value={form.days} onChange={e=>setForm(f=>({...f,days:e.target.value}))}/></label><label className="space-y-1"><span className="text-sm">مدت اشتراک (ماه)</span><input type="number" min="0" className={input} value={form.months} onChange={e=>setForm(f=>({...f,months:e.target.value}))}/></label><label className="space-y-1"><span className="text-sm">سقف کل تحلیل</span><input type="number" min="0" className={input} value={form.limit} onChange={e=>setForm(f=>({...f,limit:e.target.value}))}/></label><label className="space-y-1"><span className="text-sm">سقف تحلیل ۲۴ ساعت</span><input type="number" min="0" className={input} value={form.limit24h} onChange={e=>setForm(f=>({...f,limit24h:e.target.value}))}/></label></div><div className="mt-5 flex justify-end gap-2"><button onClick={()=>setSelected(null)} className="rounded-xl border px-5 py-2.5">انصراف</button><button disabled={busy===String(selected.id)} onClick={()=>void save()} className="rounded-xl bg-cyan-600 px-5 py-2.5 font-semibold text-white disabled:opacity-50">{busy===String(selected.id)?'در حال ذخیره...':'ذخیره تغییرات'}</button></div></div></div>}
 </div>;
};
export default AdminSubscriptionsPanel;
