import React, { useCallback, useEffect, useMemo, useState } from 'react';
import * as adminDashboardService from '../services/adminDashboardService';
import * as adminControlService from '../services/adminControlService';
import * as adminOperationsService from '../services/adminOperationsService';
import * as adminActionsService from '../services/adminActionsService';
import type { AdminDashboardData } from '../services/adminDashboardService';
import UserManagementLegacy from './UserManagementLegacy';
import { ChartBarIcon, UserGroupIcon, BriefcaseIcon, Cog6ToothIcon, BellIcon, ShieldCheckIcon, PresentationChartLineIcon, ClipboardDocumentIcon, GlobeAltIcon, MagnifyingGlassIcon, LockClosedIcon } from './Icons';

interface AdminPanelProps { isOnline: boolean; onMessageUpdate: () => void; onlineCount: number; }
type AdminSection = adminControlService.AdminModuleKey;
interface ModuleItem { id: AdminSection; title: string; description: string; icon: React.ReactNode; }

const modules: ModuleItem[] = [
 {id:'dashboard',title:'داشبورد مدیریتی',description:'شاخص‌ها و وضعیت کلی سامانه',icon:<ChartBarIcon/>},{id:'users',title:'مدیریت کاربران',description:'کاربران، حساب‌ها و دسترسی‌ها',icon:<UserGroupIcon/>},{id:'subscriptions',title:'اشتراک‌ها و اعتبار',description:'اعتبار، سقف تحلیل و تمدید',icon:<BriefcaseIcon/>},{id:'analysis',title:'مدیریت تحلیل‌ها',description:'کنترل تحلیل و مصرف منابع',icon:<MagnifyingGlassIcon/>},{id:'market',title:'مدیریت بازار',description:'داده‌ها و خلاصه بازار',icon:<GlobeAltIcon/>},{id:'scalping',title:'نوسان‌گیری',description:'کنترل موتور فرصت‌های نوسان‌گیری',icon:<ChartBarIcon/>},{id:'ai',title:'هوش مصنوعی',description:'مدل‌ها و تنظیمات سرویس AI',icon:<PresentationChartLineIcon/>},{id:'prompts',title:'مدیریت پرامپت‌ها',description:'پرامپت‌ها و نسخه‌بندی',icon:<ClipboardDocumentIcon/>},{id:'history',title:'تاریخچه تحلیل‌ها',description:'سوابق و سیاست نگهداری',icon:<ClipboardDocumentIcon/>},{id:'notifications',title:'اطلاع‌رسانی',description:'اعلان‌ها و پیام‌های سیستمی',icon:<BellIcon/>},{id:'monitoring',title:'مانیتورینگ سیستم',description:'پایش سرویس و API',icon:<PresentationChartLineIcon/>},{id:'reports',title:'گزارش‌ها',description:'گزارش‌های مدیریتی و آماری',icon:<ChartBarIcon/>},{id:'security',title:'امنیت و دسترسی',description:'سیاست‌های امنیتی و کنترل دسترسی',icon:<ShieldCheckIcon/>},{id:'settings',title:'تنظیمات سامانه',description:'پیکربندی عمومی نرم‌افزار',icon:<Cog6ToothIcon/>},{id:'maintenance',title:'حالت تعمیرات',description:'قفل دسترسی کاربران هنگام نگهداری',icon:<LockClosedIcon/>},{id:'updates',title:'بروزرسانی و استقرار',description:'نسخه و وضعیت انتشار',icon:<PresentationChartLineIcon/>},{id:'backup',title:'پشتیبان‌گیری و بازیابی',description:'سیاست و سوابق Backup',icon:<BriefcaseIcon/>},{id:'payments',title:'پرداخت‌ها و تراکنش‌ها',description:'پرداخت و سوابق مالی',icon:<BriefcaseIcon/>},{id:'roles',title:'نقش‌ها و مجوزها',description:'نقش و Permission',icon:<ShieldCheckIcon/>},{id:'audit',title:'گزارش Audit Log',description:'ردیابی عملیات مدیریتی',icon:<ClipboardDocumentIcon/>},{id:'sessions',title:'مدیریت نشست‌ها',description:'کنترل نشست‌های کاربران',icon:<LockClosedIcon/>},{id:'api',title:'سرویس‌ها و APIها',description:'پیکربندی و سلامت سرویس‌ها',icon:<GlobeAltIcon/>},{id:'infrastructure',title:'سلامت زیرساخت',description:'دیتابیس، سرور و سرویس‌ها',icon:<PresentationChartLineIcon/>}
];
const fmt=(v:number|undefined|null)=>Number(v||0).toLocaleString('fa-IR');
const StatCard:React.FC<{title:string;value:number;hint:string}>=({title,value,hint})=><div className="rounded-2xl border border-[var(--card-border-color)] bg-[var(--card-bg)] p-5 shadow-sm"><div className="text-sm text-gray-500">{title}</div><div className="mt-2 text-3xl font-extrabold">{fmt(value)}</div><div className="mt-2 text-xs text-gray-500">{hint}</div></div>;

const ACTION_LABELS: Record<string,string> = {
 'activate-user':'فعال‌سازی کاربر','deactivate-user':'غیرفعال‌سازی کاربر','set-subscription':'ثبت اشتراک','delete-analysis':'حذف تحلیل','delete-history-item':'حذف سابقه','broadcast':'ارسال اعلان همگانی','revoke-session':'لغو نشست','revoke-all-user-sessions':'لغو همه نشست‌های کاربر','revoke-api-key':'لغو API Key','assign-role':'تخصیص نقش','set-policy':'ثبت سیاست','set-setting':'ثبت تنظیم','enable':'فعال‌سازی تعمیرات','disable':'غیرفعال‌سازی تعمیرات','set-config':'ثبت تنظیمات AI','set-prompt':'ثبت پرامپت','health-check':'بررسی سلامت','snapshot':'ساخت گزارش Snapshot','set-channel':'تغییر کانال انتشار'
};

const AdminPanel:React.FC<AdminPanelProps>=({isOnline,onMessageUpdate,onlineCount})=>{
 const [section,setSection]=useState<AdminSection>('dashboard');
 const [dashboard,setDashboard]=useState<AdminDashboardData|null>(null); const [modulesState,setModulesState]=useState<adminControlService.AdminModuleRecord[]>([]); const [overview,setOverview]=useState<adminOperationsService.AdminModuleOverview|null>(null); const [capabilities,setCapabilities]=useState<adminActionsService.AdminCapability|null>(null);
 const [config,setConfig]=useState('{}'); const [enabled,setEnabled]=useState(true); const [audit,setAudit]=useState<Record<string,unknown>[]>([]); const [actionPayload,setActionPayload]=useState('{}');
 const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [actionBusy,setActionBusy]=useState(false); const [error,setError]=useState<string|null>(null); const [saved,setSaved]=useState(false); const [actionMessage,setActionMessage]=useState<string|null>(null);
 const active=useMemo(()=>modules.find(x=>x.id===section)||modules[0],[section]);
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const [d,m,o,c]=await Promise.all([adminDashboardService.getAdminDashboard(),adminControlService.getModules(),adminOperationsService.getOverview(section),adminActionsService.getCapabilities(section)]);setDashboard(d);setModulesState(m);setOverview(o);setCapabilities(c);setEnabled(o.enabled);setConfig(JSON.stringify(o.config||{},null,2));setActionMessage(null);if(section==='audit')setAudit(await adminControlService.getAudit(100));}catch(e){setError(e instanceof Error?e.message:'خطا در دریافت اطلاعات پنل مدیریت.');}finally{setLoading(false);}},[section]);
 useEffect(()=>{void load();},[load]);
 const save=async()=>{setSaved(false);setError(null);let parsed:Record<string,unknown>;try{parsed=JSON.parse(config);if(!parsed||Array.isArray(parsed)||typeof parsed!=='object')throw new Error();}catch{setError('تنظیمات باید JSON معتبر و به‌صورت یک شیء باشد.');return;}setSaving(true);try{const o=await adminOperationsService.saveConfig(section,enabled,parsed);setOverview(o);setSaved(true);await load();}catch(e){setError(e instanceof Error?e.message:'ذخیره تنظیمات ناموفق بود.');}finally{setSaving(false);}};
 const execute=async(action:string)=>{setActionBusy(true);setActionMessage(null);setError(null);try{let payload:Record<string,unknown>={};try{const p=JSON.parse(actionPayload);if(!p||Array.isArray(p)||typeof p!=='object')throw new Error();payload=p;}catch{setError('پارامتر عملیات باید JSON معتبر باشد.');setActionBusy(false);return;}const result=await adminActionsService.executeAction(section,action,payload);setActionMessage(`عملیات «${ACTION_LABELS[action]||action}» با موفقیت انجام شد.`);setActionPayload(JSON.stringify(result||{},null,2));await load();}catch(e){setError(e instanceof Error?e.message:'اجرای عملیات ناموفق بود.');}finally{setActionBusy(false);}};
 const renderDashboard=()=> <div className="space-y-6"><div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-4"><StatCard title="کل کاربران" value={dashboard?.totalUsers||0} hint="کاربران ثبت‌شده"/><StatCard title="اشتراک فعال" value={dashboard?.activeSubscriptions||0} hint="اعتبار جاری"/><StatCard title="کل تحلیل‌ها" value={dashboard?.totalAnalyses||0} hint="سوابق تحلیل"/><StatCard title="کل API Key" value={dashboard?.totalApiKeys||0} hint="کلیدهای فعال"/></div><div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-4"><StatCard title="رویدادهای Audit" value={overview?.counts?.total||0} hint="رویدادهای ثبت‌شده"/><StatCard title="نشست‌ها" value={overview?.counts?.sessions||0} hint="نشست‌های ثبت‌شده"/><StatCard title="اعلان‌ها" value={dashboard?.totalNotifications||0} hint="سوابق اعلان"/><StatCard title="ماژول‌ها" value={modules.length} hint="۲۳ بخش مدیریتی"/></div><div className="rounded-2xl border border-[var(--card-border-color)] bg-[var(--card-bg)] p-5"><h3 className="font-bold mb-3">وضعیت سامانه</h3><div className="grid md:grid-cols-3 gap-3"><div className="rounded-xl bg-gray-50 dark:bg-gray-800/60 p-4">اتصال: <b>{isOnline?'آنلاین':'قطع'}</b></div><div className="rounded-xl bg-gray-50 dark:bg-gray-800/60 p-4">کاربران آنلاین: <b>{fmt(onlineCount)}</b></div><div className="rounded-xl bg-gray-50 dark:bg-gray-800/60 p-4">ماژول فعال: <b>{modulesState.filter(x=>x.enabled).length} / ۲۳</b></div></div></div></div>;
 const renderAudit=()=> <div className="rounded-2xl border border-[var(--card-border-color)] bg-[var(--card-bg)] p-5 overflow-auto"><div className="flex justify-between mb-4"><h3 className="font-bold">آخرین رویدادهای مدیریتی</h3><button onClick={()=>void load()} className="rounded-lg border px-3 py-2 text-sm">به‌روزرسانی</button></div><table className="w-full text-sm"><thead><tr className="border-b"><th className="p-3 text-right">عملیات</th><th className="p-3 text-right">ماژول</th><th className="p-3 text-right">مسیر</th><th className="p-3 text-right">وضعیت</th><th className="p-3 text-right">زمان</th></tr></thead><tbody>{audit.map((r,i)=><tr key={String(r.id||i)} className="border-b"><td className="p-3">{String(r.action||'-')}</td><td className="p-3">{modules.find(m=>m.id===r.moduleKey)?.title||String(r.moduleKey||'-')}</td><td className="p-3 ltr">{String(r.path||'-')}</td><td className="p-3">{String(r.statusCode||'-')}</td><td className="p-3">{r.createdAt?new Date(String(r.createdAt)).toLocaleString('fa-IR'):'-'}</td></tr>)}</tbody></table>{audit.length===0&&<div className="py-8 text-center text-gray-500">هنوز رویدادی ثبت نشده است.</div>}</div>;
 const renderActions=()=> capabilities && capabilities.actions.length>0 ? <div className="rounded-2xl border border-[var(--card-border-color)] bg-[var(--card-bg)] p-5"><div className="flex items-center justify-between gap-3"><div><h3 className="font-bold">عملیات واقعی {active.title}</h3><p className="text-xs text-gray-500 mt-1">این عملیات مستقیماً روی داده‌های سامانه اجرا و در Audit Log ثبت می‌شود.</p></div><span className="rounded-full bg-cyan-50 px-3 py-1 text-xs text-cyan-700">{capabilities.actions.length} عملیات</span></div><textarea value={actionPayload} onChange={e=>setActionPayload(e.target.value)} className="mt-4 min-h-[120px] w-full rounded-xl border border-[var(--card-border-color)] bg-transparent p-4 font-mono text-sm ltr" dir="ltr" spellCheck={false} placeholder="پارامتر عملیات به صورت JSON"/><div className="mt-3 flex flex-wrap gap-2">{capabilities.actions.map(action=><button key={action} disabled={actionBusy} onClick={()=>void execute(action)} className="rounded-xl border border-cyan-500/40 px-4 py-2 text-sm font-semibold hover:bg-cyan-50 dark:hover:bg-cyan-950/30 disabled:opacity-50">{ACTION_LABELS[action]||action}</button>)}</div>{actionMessage&&<div className="mt-3 text-sm text-green-600">{actionMessage}</div>}</div> : null;
 const renderModule=()=> <div className="space-y-5"><div className="grid grid-cols-2 md:grid-cols-4 gap-3">{Object.entries(overview?.counts||{}).map(([k,v])=><StatCard key={k} title={k} value={Number(v)||0} hint="اطلاعات واقعی پایگاه داده"/>)}</div>{renderActions()}<div className="rounded-2xl border border-[var(--card-border-color)] bg-[var(--card-bg)] p-5"><div className="flex flex-col md:flex-row md:items-center justify-between gap-4"><div><h3 className="font-bold text-lg">پیکربندی {active.title}</h3><p className="text-sm text-gray-500 mt-1">API: <span dir="ltr">/api/v1/admin-ops/{section}</span></p></div><label className="flex items-center gap-2"><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/><span>{enabled?'فعال':'غیرفعال'}</span></label></div><textarea value={config} onChange={e=>setConfig(e.target.value)} className="mt-5 min-h-[180px] w-full rounded-xl border border-[var(--card-border-color)] bg-transparent p-4 font-mono text-sm ltr" dir="ltr" spellCheck={false}/><div className="mt-4 flex items-center gap-3"><button disabled={saving} onClick={()=>void save()} className="rounded-xl bg-cyan-600 px-6 py-2.5 font-semibold text-white disabled:opacity-50">{saving?'در حال ذخیره...':'ذخیره تنظیمات'}</button>{saved&&<span className="text-green-600 text-sm">ذخیره و ثبت Audit انجام شد.</span>}</div></div>{(section==='users'||section==='subscriptions')&&<div className="rounded-2xl border border-[var(--card-border-color)] bg-[var(--card-bg)] p-4"><UserManagementLegacy isOnline={isOnline} onMessageUpdate={onMessageUpdate} onlineCount={onlineCount}/></div>}</div>;
 return <div dir="rtl" className="mx-auto max-w-[1600px] space-y-5"><div className="rounded-2xl border border-[var(--card-border-color)] bg-[var(--card-bg)] p-5"><div className="flex items-center gap-3"><ShieldCheckIcon className="h-7 w-7 text-cyan-500"/><h1 className="text-2xl font-extrabold">مرکز کنترل مدیریت رونیا</h1></div><p className="mt-2 text-sm text-gray-500">۲۳ ماژول با رابط کاربری، API اختصاصی، احراز هویت ادمین، دیتابیس، Audit Log و عملیات واقعی</p></div><div className="grid grid-cols-1 lg:grid-cols-[270px_minmax(0,1fr)] gap-5 items-start"><aside className="rounded-2xl border border-[var(--card-border-color)] bg-[var(--card-bg)] p-3 lg:sticky lg:top-4"><div className="px-3 py-2 text-xs font-bold text-gray-500">۲۳ بخش مدیریت</div><div className="grid grid-cols-2 lg:grid-cols-1 gap-1 max-h-[72vh] overflow-auto">{modules.map(m=><button key={m.id} onClick={()=>setSection(m.id)} className={`flex items-center gap-3 rounded-xl px-3 py-2.5 text-right text-sm ${section===m.id?'bg-cyan-600 text-white':'hover:bg-gray-100 dark:hover:bg-gray-800'}`}><span>{m.icon}</span><span className="truncate">{m.title}</span></button>)}</div></aside><main className="min-w-0"><div className="mb-4 flex items-center justify-between"><div><h2 className="text-lg font-bold">{active.title}</h2><p className="text-xs text-gray-500 mt-1">{active.description}</p></div><button onClick={()=>void load()} className="rounded-lg border px-4 py-2 text-sm">به‌روزرسانی</button></div>{loading?<div className="py-16 text-center text-gray-500">در حال بارگذاری...</div>:error?<div className="rounded-2xl border border-red-200 bg-red-50 p-6 text-center text-red-700"><p>{error}</p><button onClick={()=>void load()} className="mt-3 rounded-lg bg-red-600 px-5 py-2 text-white">تلاش مجدد</button></div>:section==='dashboard'?renderDashboard():section==='audit'?renderAudit():renderModule()}</main></div></div>;
};
export default AdminPanel;
