import React,{useCallback,useEffect,useState} from 'react';
import * as service from '../services/adminAnalysesService';
const fa=(v:number)=>v.toLocaleString('fa-IR');
const date=(v?:string|null)=>v?new Date(v).toLocaleString('fa-IR'):'—';
export default function AdminAnalysesPanel(){
 const [data,setData]=useState<service.AdminAnalysesResult|null>(null),[page,setPage]=useState(1),[search,setSearch]=useState(''),[symbol,setSymbol]=useState(''),[status,setStatus]=useState(''),[loading,setLoading]=useState(false),[error,setError]=useState(''),[selected,setSelected]=useState<service.AdminAnalysisItem|null>(null);
 const load=useCallback(async()=>{setLoading(true);setError('');try{setData(await service.getAnalyses({page,limit:20,search,symbol,status}));}catch(e){setError(e instanceof Error?e.message:'خطا در دریافت تحلیل‌ها.');}finally{setLoading(false)}},[page,search,symbol,status]);
 useEffect(()=>{void load()},[load]);
 const remove=async(id:number)=>{if(!window.confirm('آیا از حذف این تحلیل مطمئن هستید؟ این عملیات در Audit Log ثبت می‌شود.'))return;try{await service.deleteAnalysis(id);setSelected(null);await load()}catch(e){setError(e instanceof Error?e.message:'حذف تحلیل ناموفق بود.')}};
 const s=data?.summary;
 return <div dir="rtl" className="space-y-5">
  <div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><div className="rounded-2xl border bg-[var(--card-bg)] p-4"><span className="text-xs text-gray-500">کل تحلیل‌ها</span><b className="block mt-2 text-2xl">{fa(s?.total||0)}</b></div><div className="rounded-2xl border bg-[var(--card-bg)] p-4"><span className="text-xs text-gray-500">تکمیل‌شده</span><b className="block mt-2 text-2xl">{fa(s?.completed||0)}</b></div><div className="rounded-2xl border bg-[var(--card-bg)] p-4"><span className="text-xs text-gray-500">ناموفق</span><b className="block mt-2 text-2xl">{fa(s?.failed||0)}</b></div><div className="rounded-2xl border bg-[var(--card-bg)] p-4"><span className="text-xs text-gray-500">اعتبار مصرفی صفحه</span><b className="block mt-2 text-2xl">{fa(s?.credits||0)}</b></div></div>
  <div className="rounded-2xl border bg-[var(--card-bg)] p-4"><div className="grid grid-cols-1 md:grid-cols-4 gap-3"><input value={search} onChange={e=>{setPage(1);setSearch(e.target.value)}} placeholder="جستجوی نام کاربری یا ایمیل" className="rounded-xl border p-3 bg-transparent"/><input value={symbol} onChange={e=>{setPage(1);setSymbol(e.target.value)}} placeholder="نماد" className="rounded-xl border p-3 bg-transparent"/><select value={status} onChange={e=>{setPage(1);setStatus(e.target.value)}} className="rounded-xl border p-3 bg-transparent"><option value="">همه وضعیت‌ها</option><option value="completed">تکمیل‌شده</option><option value="failed">ناموفق</option><option value="pending">در انتظار</option></select><button onClick={()=>void load()} disabled={loading} className="rounded-xl border px-4 py-3 font-semibold disabled:opacity-50">{loading?'در حال دریافت...':'بروزرسانی'}</button></div></div>
  {error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
  <div className="overflow-x-auto rounded-2xl border bg-[var(--card-bg)]"><table className="w-full text-sm"><thead><tr className="border-b text-right"><th className="p-4">کاربر</th><th className="p-4">نماد</th><th className="p-4">نوع</th><th className="p-4">زمان</th><th className="p-4">وضعیت</th><th className="p-4">اعتبار</th><th className="p-4">عملیات</th></tr></thead><tbody>{loading&&!data?<tr><td colSpan={7} className="p-8 text-center text-gray-500">در حال بارگذاری...</td></tr>:data?.items.length?data.items.map(x=><tr key={x.id} className="border-b last:border-0"><td className="p-4"><b>{x.name||x.username}</b><div className="text-xs text-gray-500">{x.email||x.username}</div></td><td className="p-4 font-bold">{x.symbol}</td><td className="p-4">{x.analysisType}</td><td className="p-4 whitespace-nowrap">{date(x.createdAt)}</td><td className="p-4">{x.statusLabel}</td><td className="p-4">{fa(x.credits)}</td><td className="p-4"><div className="flex gap-2"><button onClick={()=>setSelected(x)} className="rounded-lg border px-3 py-1.5">جزئیات</button><button onClick={()=>void remove(x.id)} className="rounded-lg border border-red-300 px-3 py-1.5 text-red-600">حذف</button></div></td></tr>):<tr><td colSpan={7} className="p-8 text-center text-gray-500">تحلیلی یافت نشد.</td></tr>}</tbody></table></div>
  <div className="flex items-center justify-between"><span className="text-sm text-gray-500">صفحه {fa(data?.pagination.page||page)} از {fa(data?.pagination.totalPages||0)}</span><div className="flex gap-2"><button disabled={page<=1||loading} onClick={()=>setPage(p=>p-1)} className="rounded-xl border px-4 py-2 disabled:opacity-40">قبلی</button><button disabled={page>=(data?.pagination.totalPages||1)||loading} onClick={()=>setPage(p=>p+1)} className="rounded-xl border px-4 py-2 disabled:opacity-40">بعدی</button></div></div>
  {selected&&<div className="fixed inset-0 z-50 bg-black/40 flex items-center justify-center p-4" onClick={()=>setSelected(null)}><div onClick={e=>e.stopPropagation()} className="w-full max-w-2xl max-h-[85vh] overflow-auto rounded-2xl bg-[var(--card-bg)] p-6"><div className="flex justify-between"><h3 className="text-lg font-bold">جزئیات تحلیل #{fa(selected.id)}</h3><button onClick={()=>setSelected(null)}>✕</button></div><div className="grid grid-cols-2 gap-3 mt-5 text-sm"><div>کاربر: <b>{selected.username}</b></div><div>نماد: <b>{selected.symbol}</b></div><div>نوع: <b>{selected.analysisType}</b></div><div>اعتبار: <b>{fa(selected.credits)}</b></div><div>وضعیت: <b>{selected.statusLabel}</b></div><div>زمان: <b>{date(selected.createdAt)}</b></div></div>{selected.result&&<pre dir="ltr" className="mt-5 rounded-xl bg-gray-50 dark:bg-gray-900 p-4 text-xs whitespace-pre-wrap">{selected.result}</pre>}<button onClick={()=>void remove(selected.id)} className="mt-5 rounded-xl bg-red-600 text-white px-4 py-2">حذف تحلیل</button></div></div>}
 </div>
}
