import React,{useCallback,useEffect,useState}from'react';
import*as svc from'../services/adminActionsService';
interface Props{onComplete?:()=>Promise<void>|void}
type Health={database?:string;node?:string;uptimeSeconds?:number;memory?:{rss:number;heapUsed:number;heapTotal:number};checkedAt?:string;status?:string};
const n=(v:number)=>Math.round(v/1024/1024).toLocaleString('fa-IR');
const AdminMonitoringPanel:React.FC<Props>=({onComplete=()=>undefined})=>{const[h,setH]=useState<Health|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null);
const load=useCallback(async()=>{setLoading(true);setError(null);try{const x=await svc.executeAction<Health>('monitoring','health-check',{});setH(x);await onComplete()}catch(e){setError(e instanceof Error?e.message:'بررسی سلامت سامانه ناموفق بود.')}finally{setLoading(false)}},[onComplete]);
useEffect(()=>{void load()},[load]);const uptime=h?.uptimeSeconds??0;const hours=Math.floor(uptime/3600),mins=Math.floor((uptime%3600)/60);
return <div dir="rtl" className="space-y-5"><div className="rounded-2xl border border-[var(--card-border-color)] bg-[var(--card-bg)] p-5"><div className="flex items-center justify-between gap-3"><div><h3 className="text-lg font-bold">پایش و سلامت سامانه</h3><p className="mt-1 text-sm text-gray-500">وضعیت لحظه‌ای Backend، پایگاه داده و منابع پردازشی</p></div><button onClick={()=>void load()} disabled={loading} className="rounded-xl border px-4 py-2 text-sm disabled:opacity-50">{loading?'در حال بررسی...':'بررسی مجدد'}</button></div></div>
{error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
<div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">{[['Backend',h?.status||'—'],['پایگاه داده',h?.database||'—'],['Node.js',h?.node||'—'],['Uptime',hours+' ساعت و '+mins+' دقیقه']].map(([a,b])=><div key={a} className="rounded-2xl border border-[var(--card-border-color)] bg-[var(--card-bg)] p-5"><div className="text-sm text-gray-500">{a}</div><div className="mt-2 text-xl font-extrabold">{b}</div></div>)}</div>
<div className="rounded-2xl border border-[var(--card-border-color)] bg-[var(--card-bg)] p-5"><h4 className="font-bold">مصرف حافظه Backend</h4><div className="mt-4 grid grid-cols-1 sm:grid-cols-3 gap-3"><div className="rounded-xl border p-4"><span className="text-xs text-gray-500">RSS</span><div className="mt-1 font-bold">{h?.memory?n(h.memory.rss)+' MB':'—'}</div></div><div className="rounded-xl border p-4"><span className="text-xs text-gray-500">Heap استفاده‌شده</span><div className="mt-1 font-bold">{h?.memory?n(h.memory.heapUsed)+' MB':'—'}</div></div><div className="rounded-xl border p-4"><span className="text-xs text-gray-500">Heap کل</span><div className="mt-1 font-bold">{h?.memory?n(h.memory.heapTotal)+' MB':'—'}</div></div></div>{h?.checkedAt&&<div className="mt-4 text-xs text-gray-500">آخرین بررسی: {new Date(h.checkedAt).toLocaleString('fa-IR')}</div>}</div></div>};export default AdminMonitoringPanel;
