import React, { useCallback, useEffect, useMemo, useState } from 'react';
import * as apiClient from '../services/apiClient';
import * as adminActionsService from '../services/adminActionsService';

interface PromptRow { name:string; version:number; active:boolean; value:string; updatedAt?:string|null; }
const card='rounded-2xl border border-[var(--card-border-color)] bg-[var(--card-bg)] p-5 shadow-sm';
const input='w-full rounded-xl border border-[var(--card-border-color)] bg-transparent px-3 py-2.5 text-sm outline-none focus:ring-2 focus:ring-cyan-500/30';
const AdminPromptsPanel:React.FC<{onComplete?:()=>void}>=({onComplete})=>{
 const [rows,setRows]=useState<PromptRow[]>([]); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null); const [message,setMessage]=useState<string|null>(null); const [name,setName]=useState(''); const [value,setValue]=useState(''); const [selected,setSelected]=useState<PromptRow|null>(null);
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const r=await apiClient.get<PromptRow[]>('/admin-ai/prompts');if(!r.success||!r.data)throw new Error(r.message||'دریافت پرامپت‌ها ناموفق بود.');setRows(r.data);}catch(e){setError(e instanceof Error?e.message:'دریافت پرامپت‌ها ناموفق بود.');}finally{setLoading(false);}},[]);
 useEffect(()=>{void load();},[load]);
 const names=useMemo(()=>Array.from(new Set(rows.map(x=>x.name))),[rows]);
 const selectName=(n:string)=>{setName(n);const active=rows.find(x=>x.name===n&&x.active)||rows.find(x=>x.name===n);setSelected(active||null);setValue(active?.value||'');};
 const save=async()=>{if(!name.trim()||!value.trim()){setError('نام و متن پرامپت الزامی است.');return;}setBusy(true);setError(null);setMessage(null);try{const r=await adminActionsService.executeAction('prompts','set-prompt',{name:name.trim(),value});if(!r)throw new Error('ذخیره پرامپت ناموفق بود.');setMessage('نسخه جدید پرامپت با موفقیت ذخیره شد.');await load();onComplete?.();}catch(e){setError(e instanceof Error?e.message:'ذخیره پرامپت ناموفق بود.');}finally{setBusy(false);}};
 const activate=async(row:PromptRow)=>{setBusy(true);setError(null);setMessage(null);try{const r=await apiClient.post<{saved?:boolean}>('/admin-ai/prompts/activate',{name:row.name,version:row.version});if(!r.success)throw new Error(r.message||'فعال‌سازی ناموفق بود.');setMessage(`نسخه ${row.version} پرامپت «${row.name}» فعال شد.`);await load();onComplete?.();}catch(e){setError(e instanceof Error?e.message:'فعال‌سازی پرامپت ناموفق بود.');}finally{setBusy(false);}};
 if(loading&&!rows.length)return <div className="p-6 text-center text-gray-500">در حال دریافت پرامپت‌ها...</div>;
 return <div dir="rtl" className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-extrabold">مرکز مدیریت پرامپت‌ها</h2><p className="mt-1 text-sm text-gray-500">نسخه‌بندی، ویرایش و فعال‌سازی امن پرامپت‌های سامانه</p></div><button onClick={()=>void load()} disabled={loading||busy} className="rounded-xl border px-4 py-2 text-sm font-semibold">↻ بروزرسانی</button></div>
 {error&&<div className="rounded-xl border border-rose-300 bg-rose-50 p-4 text-sm text-rose-700">{error}</div>}{message&&<div className="rounded-xl border border-emerald-300 bg-emerald-50 p-4 text-sm text-emerald-700">{message}</div>}
 <div className="grid grid-cols-1 lg:grid-cols-3 gap-6"><div className={`${card} lg:col-span-1`}><h3 className="font-bold">پرامپت‌ها</h3><div className="mt-4 space-y-2">{names.map(n=><button key={n} onClick={()=>selectName(n)} className={`w-full rounded-xl border px-3 py-3 text-right text-sm ${name===n?'border-cyan-500 bg-cyan-50 dark:bg-cyan-950/20':'border-[var(--card-border-color)]'}`}>{n}<span className="block mt-1 text-xs text-gray-500">{rows.filter(x=>x.name===n).length} نسخه</span></button>)}{!names.length&&<p className="text-sm text-gray-500">پرامپت ثبت‌شده‌ای وجود ندارد.</p>}</div></div>
 <div className={`${card} lg:col-span-2`}><h3 className="font-bold">ویرایش / ایجاد نسخه</h3><div className="mt-4 grid gap-3"><input className={input} value={name} onChange={e=>setName(e.target.value)} placeholder="نام پرامپت" dir="ltr"/><textarea className={`${input} min-h-[280px]`} value={value} onChange={e=>setValue(e.target.value)} placeholder="متن پرامپت..." dir="ltr" spellCheck={false}/><div className="flex flex-wrap items-center gap-3"><button disabled={busy} onClick={()=>void save()} className="rounded-xl bg-cyan-600 px-5 py-2.5 font-bold text-white disabled:opacity-50">ذخیره نسخه جدید</button>{selected&&<span className="text-xs text-gray-500">نسخه فعلی: {selected.version} {selected.active?'(فعال)':''}</span>}</div></div></div></div>
 <div className={card}><h3 className="font-bold">تاریخچه نسخه‌ها</h3><div className="mt-4 overflow-auto"><table className="w-full min-w-[700px] text-sm"><thead><tr className="border-b"><th className="p-3 text-right">نام</th><th className="p-3 text-right">نسخه</th><th className="p-3 text-right">وضعیت</th><th className="p-3 text-right">آخرین بروزرسانی</th><th className="p-3 text-right">عملیات</th></tr></thead><tbody>{rows.map(row=><tr key={`${row.name}:${row.version}`} className="border-b"><td className="p-3" dir="ltr">{row.name}</td><td className="p-3">{row.version}</td><td className="p-3">{row.active?<span className="text-emerald-600 font-semibold">فعال</span>:<span className="text-gray-500">غیرفعال</span>}</td><td className="p-3">{row.updatedAt?new Date(row.updatedAt).toLocaleString('fa-IR'):'—'}</td><td className="p-3 flex gap-2"><button disabled={busy} onClick={()=>{setName(row.name);setValue(row.value);setSelected(row);}} className="rounded-lg border px-3 py-1.5 text-xs">ویرایش</button>{!row.active&&<button disabled={busy} onClick={()=>void activate(row)} className="rounded-lg border border-cyan-500/50 px-3 py-1.5 text-xs">فعال‌سازی</button>}</td></tr>)}</tbody></table></div></div></div>;
};
export default AdminPromptsPanel;
