import React, { useCallback, useEffect, useState } from 'react';
import { getPortfolioCorrelation, type PortfolioCorrelationResult } from '../services/portfolioCorrelationService';

interface Props { isOnline: boolean; }
const pct = (v: number) => `${v > 0 ? '+' : ''}${(v * 100).toFixed(1)}%`;

const PortfolioCorrelationAnalysis: React.FC<Props> = ({ isOnline }) => {
  const [data, setData] = useState<PortfolioCorrelationResult | null>(null);
  const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { if (!isOnline) { setError('برای محاسبه همبستگی سبد باید آنلاین باشید.'); return; } setLoading(true); setError(null); try { setData(await getPortfolioCorrelation()); } catch (e: any) { setError(e?.response?.data?.message || e?.message || 'محاسبه همبستگی سبد ناموفق بود.'); } finally { setLoading(false); } }, [isOnline]);
  useEffect(() => { load(); }, [load]);
  return <div dir="rtl" className="space-y-5">
    <div className="flex items-center justify-between gap-3 flex-wrap"><div><h2 className="text-2xl font-black">همبستگی و تمرکز ریسک مشترک</h2><p className="text-sm text-gray-500 dark:text-gray-400 mt-1">مقایسه حرکت روزانه نمادهای سبد بر اساس تاریخچه واقعی و تاریخ ورود هر موقعیت</p></div><button type="button" onClick={load} disabled={loading || !isOnline} className="rounded-xl bg-cyan-600 text-white px-4 py-2 font-bold disabled:opacity-50">{loading ? 'در حال محاسبه...' : 'بروزرسانی'}</button></div>
    {error && <div className="rounded-xl border border-red-300 bg-red-50 dark:bg-red-950/20 p-4 text-red-700 dark:text-red-300">{error}</div>}
    {data && <>
      <div className="grid grid-cols-2 md:grid-cols-3 gap-3"><div className="rounded-2xl border border-[var(--color-border)] bg-white/80 dark:bg-gray-900/60 p-4"><p className="text-xs text-gray-500">تعداد نمادها</p><p className="mt-2 text-xl font-black">{data.symbols.length}</p></div><div className="rounded-2xl border border-[var(--color-border)] bg-white/80 dark:bg-gray-900/60 p-4"><p className="text-xs text-gray-500">تعداد جفت‌ها</p><p className="mt-2 text-xl font-black">{data.pairs.length}</p></div><div className="rounded-2xl border border-[var(--color-border)] bg-white/80 dark:bg-gray-900/60 p-4"><p className="text-xs text-gray-500">میانگین قدرمطلق همبستگی</p><p className="mt-2 text-xl font-black">{data.averageAbsoluteCorrelation == null ? '—' : pct(data.averageAbsoluteCorrelation)}</p></div></div>
      <div className="rounded-2xl border border-[var(--color-border)] bg-white/80 dark:bg-gray-900/60 overflow-x-auto"><div className="p-4 border-b border-[var(--color-border)]"><h3 className="font-black text-lg">جفت‌های با همبستگی بالا</h3><p className="text-xs text-gray-500 mt-1">قدر مطلق همبستگی ۰٫۷۰ یا بیشتر به‌عنوان هم‌حرکتی بالا نمایش داده می‌شود.</p></div>{data.highCorrelationPairs.length ? <table className="w-full text-sm"><thead><tr className="text-right text-gray-500"><th className="p-3">نماد اول</th><th className="p-3">نماد دوم</th><th className="p-3">همبستگی</th><th className="p-3">مشاهدات مشترک</th></tr></thead><tbody>{data.highCorrelationPairs.map(p => <tr key={`${p.left}-${p.right}`} className="border-t border-[var(--color-border)]"><td className="p-3 font-black">{p.left}</td><td className="p-3 font-black">{p.right}</td><td className={`p-3 font-mono ${p.correlation < 0 ? 'text-cyan-600' : 'text-amber-600'}`}>{pct(p.correlation)}</td><td className="p-3 font-mono">{p.observations}</td></tr>)}</tbody></table> : <div className="p-6 text-center text-gray-500">جفت دارای همبستگی بالا با داده معتبر کافی پیدا نشد.</div>}</div>
      <div className="rounded-2xl border border-[var(--color-border)] bg-white/80 dark:bg-gray-900/60 overflow-x-auto"><div className="p-4 border-b border-[var(--color-border)]"><h3 className="font-black">جدول کامل همبستگی جفت‌ها</h3></div>{data.pairs.length ? <table className="w-full text-sm"><thead><tr className="text-right text-gray-500"><th className="p-3">نماد اول</th><th className="p-3">نماد دوم</th><th className="p-3">همبستگی</th><th className="p-3">مشاهدات</th></tr></thead><tbody>{data.pairs.map(p => <tr key={`all-${p.left}-${p.right}`} className="border-t border-[var(--color-border)]"><td className="p-3">{p.left}</td><td className="p-3">{p.right}</td><td className="p-3 font-mono">{pct(p.correlation)}</td><td className="p-3 font-mono">{p.observations}</td></tr>)}</tbody></table> : <div className="p-6 text-center text-gray-500">برای محاسبه همبستگی حداقل دو نماد با تاریخچه مشترک معتبر لازم است.</div>}</div>
      <div className="rounded-xl border border-[var(--color-border)] p-4 text-xs text-gray-500">این بخش صرفاً تحلیل آماری توصیفی است؛ همبستگی بالا به معنی رابطه علّی نیست و هیچ مدل هوش مصنوعی یا داده ساختگی استفاده نشده است.</div>
    </>}
  </div>;
};
export default PortfolioCorrelationAnalysis;
