import React,{useEffect,useMemo,useState}from'react';
import{createJournalEntry,deleteJournalEntry,getJournal,TraderJournalEntry}from'../services/traderJournalService';
import{PlusIcon,TrashIcon}from'./Icons';
const initial={symbol:'',side:'BUY' as const,tradeDate:new Date().toISOString().slice(0,10),quantity:'',entryPrice:'',exitPrice:'',setup:'',emotion:'',thesis:'',lesson:'',notes:''};
const num=(n:number|null)=>n==null?'—':new Intl.NumberFormat('fa-IR').format(Math.round(n));
export default function TraderJournal(){const[items,setItems]=useState<TraderJournalEntry[]>([]),[form,setForm]=useState(initial),[busy,setBusy]=useState(false),[error,setError]=useState('');
const load=async()=>{try{setItems(await getJournal());setError('')}catch(e:any){setError(e?.message||'خطا در دریافت دفترچه')}};useEffect(()=>{void load()},[]);
const stats=useMemo(()=>{const c=items.filter(x=>x.pnl!=null),p=c.reduce((s,x)=>s+(x.pnl||0),0);return{all:items.length,closed:c.length,pnl:p}},[items]);
const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);try{await createJournalEntry({...form,quantity:Number(form.quantity),entryPrice:Number(form.entryPrice),exitPrice:form.exitPrice?Number(form.exitPrice):null});setForm(initial);await load()}catch(e:any){setError(e?.message||'ثبت ناموفق بود')}finally{setBusy(false)}};
const remove=async(id:string)=>{if(!window.confirm('این رکورد حذف شود؟'))return;try{await deleteJournalEntry(id);setItems(x=>x.filter(i=>i.id!==id))}catch(e:any){setError(e?.message||'حذف ناموفق بود')}};
return <div dir="rtl" className="space-y-5"><header><h2 className="text-2xl font-extrabold">دفترچه معاملات</h2><p className="text-sm text-gray-500 mt-1">ثبت دلیل معامله، وضعیت ذهنی، نتیجه و درس‌آموخته‌های هر معامله.</p></header>
<div className="grid sm:grid-cols-3 gap-3"><div className="p-4 rounded-xl border"><div className="text-xs text-gray-500">کل رکوردها</div><div className="text-2xl font-bold mt-1">{stats.all}</div></div><div className="p-4 rounded-xl border"><div className="text-xs text-gray-500">معاملات بسته</div><div className="text-2xl font-bold mt-1">{stats.closed}</div></div><div className="p-4 rounded-xl border"><div className="text-xs text-gray-500">سود/زیان ثبت‌شده</div><div className="text-2xl font-bold mt-1">{num(stats.pnl)}</div></div></div>
<form onSubmit={submit} className="p-4 rounded-xl border space-y-3"><div className="grid grid-cols-2 md:grid-cols-5 gap-2"><input required className="border rounded-lg p-2" placeholder="نماد" value={form.symbol} onChange={e=>setForm({...form,symbol:e.target.value})}/><select className="border rounded-lg p-2" value={form.side} onChange={e=>setForm({...form,side:e.target.value as 'BUY'|'SELL'})}><option value="BUY">خرید</option><option value="SELL">فروش</option></select><input required type="date" className="border rounded-lg p-2" value={form.tradeDate} onChange={e=>setForm({...form,tradeDate:e.target.value})}/><input required type="number" min="1" className="border rounded-lg p-2" placeholder="تعداد" value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})}/><input required type="number" min="0" className="border rounded-lg p-2" placeholder="قیمت ورود" value={form.entryPrice} onChange={e=>setForm({...form,entryPrice:e.target.value})}/></div>
<div className="grid grid-cols-1 md:grid-cols-3 gap-2"><input type="number" min="0" className="border rounded-lg p-2" placeholder="قیمت خروج اختیاری" value={form.exitPrice} onChange={e=>setForm({...form,exitPrice:e.target.value})}/><input className="border rounded-lg p-2" placeholder="ستاپ" value={form.setup} onChange={e=>setForm({...form,setup:e.target.value})}/><input className="border rounded-lg p-2" placeholder="احساس/وضعیت ذهنی" value={form.emotion} onChange={e=>setForm({...form,emotion:e.target.value})}/></div>
<textarea className="border rounded-lg p-2 w-full" placeholder="دلیل ورود یا خروج" value={form.thesis} onChange={e=>setForm({...form,thesis:e.target.value})}/><textarea className="border rounded-lg p-2 w-full" placeholder="درس‌آموخته" value={form.lesson} onChange={e=>setForm({...form,lesson:e.target.value})}/><textarea className="border rounded-lg p-2 w-full" placeholder="یادداشت تکمیلی" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/><button disabled={busy} className="px-4 py-2 rounded-lg font-bold flex items-center gap-2" style={{backgroundColor:'var(--btn-primary-bg)',color:'var(--btn-primary-color)'}}><PlusIcon/>{busy?'در حال ثبت...':'ثبت معامله'}</button></form>
{error&&<div className="p-3 rounded-lg border border-red-300 text-red-600">{error}</div>}{items.length===0?<div className="text-center py-10 text-gray-500">هنوز رکوردی ثبت نشده است.</div>:items.map(x=><article key={x.id} className="p-4 rounded-xl border"><div className="flex justify-between"><div><b>{x.symbol}</b><span className="mx-2">{x.side==='BUY'?'خرید':'فروش'}</span><span className="text-xs text-gray-500">{x.tradeDate}</span></div><button className="text-red-500" onClick={()=>void remove(x.id)}><TrashIcon/></button></div><div className="grid grid-cols-2 md:grid-cols-4 gap-2 mt-3 text-sm"><span>تعداد: {num(x.quantity)}</span><span>ورود: {num(x.entryPrice)}</span><span>خروج: {num(x.exitPrice)}</span><span>سود/زیان: {num(x.pnl)}</span></div>{x.thesis&&<p className="mt-2 text-sm"><b>دلیل:</b> {x.thesis}</p>}{x.lesson&&<p className="mt-1 text-sm"><b>درس:</b> {x.lesson}</p>}{x.setup&&<p className="text-xs text-gray-500 mt-1">ستاپ: {x.setup} {x.emotion&&(' | احساس: '+x.emotion)}</p>}</article>)}</div>}