import React, { useEffect, useMemo, useState } from 'react';
import * as adminService from '../services/adminService';
import { useNotification } from './NotificationSystem';

interface UserManagementProps { isOnline: boolean; onMessageUpdate: () => void; onlineCount: number; }
interface ManagedUser { id: string|number; username: string; email?: string|null; firstName?: string|null; lastName?: string|null; mobile?: string|null; isActive: boolean; roleId?: number|null; roleName?: string|null; subscriptionEnd?: string|null; remainingDays?: number|null; }

const roleTitle=(name?:string|null,title?:string|null)=> title?.trim() || ({SUPERADMIN:'مدیر ارشد',ADMIN:'مدیر سامانه',USER:'کاربر'} as Record<string,string>)[String(name||'').toUpperCase()] || name || 'بدون نقش';
const displayName=(u:ManagedUser)=>[u.firstName,u.lastName].filter(Boolean).join(' ').trim()||u.username;

const UserManagementRBAC:React.FC<UserManagementProps>=({isOnline,onlineCount})=>{
 const [users,setUsers]=useState<ManagedUser[]>([]); const [roles,setRoles]=useState<adminService.AdminRole[]>([]); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState<string|null>(null); const [search,setSearch]=useState(''); const [roleFilter,setRoleFilter]=useState('all'); const [statusFilter,setStatusFilter]=useState('all'); const [error,setError]=useState<string|null>(null); const {addNotification}=useNotification();
 const [form,setForm]=useState({username:'',password:'',firstName:'',lastName:'',email:'',mobile:'',roleId:'',subscriptionDays:'30',analysisLimit:'20',analysisLimit24h:'20'});
 const load=async()=>{setLoading(true);setError(null);try{const [u,r]=await Promise.all([adminService.getUsers(),adminService.getRoles()]);setUsers(u as ManagedUser[]);setRoles(r);}catch(e){setError(e instanceof Error?e.message:'خطا در دریافت اطلاعات کاربران.');}finally{setLoading(false);}};
 useEffect(()=>{void load();},[]);
 useEffect(()=>{if(!form.roleId&&roles.length)setForm(f=>({...f,roleId:String(roles.find(r=>r.name.toUpperCase()==='USER')?.id||roles[0].id)}));},[roles,form.roleId]);
 const filtered=useMemo(()=>users.filter(u=>{const q=search.trim().toLowerCase();const match=!q||[u.username,u.email,u.firstName,u.lastName,u.mobile].some(v=>String(v||'').toLowerCase().includes(q));const rm=roleFilter==='all'||String(u.roleId)===roleFilter;const sm=statusFilter==='all'||(statusFilter==='active'?u.isActive:!u.isActive);return match&&rm&&sm;}),[users,search,roleFilter,statusFilter]);
 const create=async(e:React.FormEvent)=>{e.preventDefault();if(!form.username.trim()||form.password.length<6){addNotification('نام کاربری و رمز عبور معتبر وارد کنید.','error');return;}setBusy('create');try{await adminService.createUser({username:form.username.trim(),password:form.password,email:form.email||null,firstName:form.firstName||null,lastName:form.lastName||null,mobile:form.mobile||null,roleId:Number(form.roleId)||null,isActive:true,subscriptionDays:Number(form.subscriptionDays)||0,isSubscriptionActive:true,analysisLimit:Number(form.analysisLimit)||0,analysisLimit24h:Number(form.analysisLimit24h)||0});addNotification('کاربر با موفقیت ایجاد شد.','success');setForm(f=>({...f,username:'',password:'',firstName:'',lastName:'',email:'',mobile:''}));await load();}catch(e){addNotification(e instanceof Error?e.message:'ایجاد کاربر ناموفق بود.','error');}finally{setBusy(null);}};
 const changeRole=async(u:ManagedUser,roleId:number)=>{if(roleId===Number(u.roleId))return;setBusy(`role-${u.id}`);try{await adminService.changeUserRole(u.id,roleId);addNotification('نقش کاربر تغییر کرد.','success');await load();}catch(e){addNotification(e instanceof Error?e.message:'تغییر نقش ناموفق بود.','error');}finally{setBusy(null);}};
 const toggle=async(u:ManagedUser)=>{setBusy(`active-${u.id}`);try{await adminService.toggleUserActive(u.id,!u.isActive);addNotification(u.isActive?'کاربر غیرفعال شد.':'کاربر فعال شد.','success');await load();}catch(e){addNotification(e instanceof Error?e.message:'تغییر وضعیت ناموفق بود.','error');}finally{setBusy(null);}};
 if(loading)return <div className="py-10 text-center text-gray-500">در حال بارگذاری کاربران و نقش‌ها...</div>;
 return <div className="max-w-7xl mx-auto space-y-6" dir="rtl">
  <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-2xl font-bold">مدیریت کاربران</h2><p className="text-sm text-gray-500 mt-1">نقش‌ها مستقیماً از RBAC خوانده می‌شوند و دیگر به نقش‌های ثابت USER/ADMIN وابسته نیستند.</p></div>{isOnline&&<span className="text-sm text-green-600">● {onlineCount} کاربر آنلاین</span>}</div>
  {error&&<div className="rounded-xl border border-red-300 bg-red-50 p-3 text-red-700">{error}</div>}
  <form onSubmit={create} className="rounded-2xl border border-[var(--card-border-color)] bg-[var(--card-bg)] p-5 shadow-sm"><h3 className="font-bold mb-4">افزودن کاربر جدید</h3><fieldset disabled={!isOnline||busy==='create'} className="grid grid-cols-1 md:grid-cols-3 gap-3 disabled:opacity-60">
   {([['firstName','نام'],['lastName','نام خانوادگی'],['username','نام کاربری'],['password','کلمه عبور'],['email','ایمیل'],['mobile','موبایل']] as const).map(([key,label])=><input key={key} type={key==='password'?'password':key==='email'?'email':'text'} placeholder={label} value={form[key]} onChange={e=>setForm(f=>({...f,[key]:e.target.value}))} className="border rounded-xl px-3 py-2 bg-transparent" required={key==='username'||key==='password'} />)}
   <select value={form.roleId} onChange={e=>setForm(f=>({...f,roleId:e.target.value}))} className="border rounded-xl px-3 py-2 bg-transparent">{roles.map(r=><option key={r.id} value={r.id}>{roleTitle(r.name,r.title)}</option>)}</select>
   <input type="number" min="0" placeholder="مدت اشتراک (روز)" value={form.subscriptionDays} onChange={e=>setForm(f=>({...f,subscriptionDays:e.target.value}))} className="border rounded-xl px-3 py-2 bg-transparent" />
   <input type="number" min="0" placeholder="سقف تحلیل" value={form.analysisLimit} onChange={e=>setForm(f=>({...f,analysisLimit:e.target.value}))} className="border rounded-xl px-3 py-2 bg-transparent" />
   <input type="number" min="0" placeholder="سقف تحلیل ۲۴ ساعت" value={form.analysisLimit24h} onChange={e=>setForm(f=>({...f,analysisLimit24h:e.target.value}))} className="border rounded-xl px-3 py-2 bg-transparent" />
   <button className="md:col-span-3 rounded-xl px-5 py-2 font-bold bg-cyan-600 text-white disabled:opacity-50" disabled={!isOnline||busy==='create'}>{busy==='create'?'در حال ایجاد...':'ایجاد کاربر'}</button>
  </fieldset></form>
  <div className="rounded-2xl border border-[var(--card-border-color)] bg-[var(--card-bg)] p-5"><div className="grid grid-cols-1 md:grid-cols-3 gap-3 mb-4"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="جستجوی نام، نام کاربری، ایمیل یا موبایل" className="border rounded-xl px-3 py-2 bg-transparent"/><select value={roleFilter} onChange={e=>setRoleFilter(e.target.value)} className="border rounded-xl px-3 py-2 bg-transparent"><option value="all">همه نقش‌ها</option>{roles.map(r=><option key={r.id} value={r.id}>{roleTitle(r.name,r.title)}</option>)}</select><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)} className="border rounded-xl px-3 py-2 bg-transparent"><option value="all">همه وضعیت‌ها</option><option value="active">فعال</option><option value="inactive">غیرفعال</option></select></div>
   <div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b"><th className="p-3 text-right">کاربر</th><th className="p-3 text-right">نقش</th><th className="p-3 text-right">اشتراک</th><th className="p-3 text-right">وضعیت</th><th className="p-3 text-right">عملیات</th></tr></thead><tbody>{filtered.map(u=><tr key={u.id} className="border-b last:border-0"><td className="p-3"><div className="font-semibold">{displayName(u)}</div><div className="text-xs text-gray-500">@{u.username}{u.email?` · ${u.email}`:''}</div></td><td className="p-3"><select value={u.roleId??''} disabled={busy===`role-${u.id}`} onChange={e=>void changeRole(u,Number(e.target.value))} className="border rounded-lg px-2 py-1 bg-transparent">{roles.map(r=><option key={r.id} value={r.id}>{roleTitle(r.name,r.title)}</option>)}</select></td><td className="p-3">{u.remainingDays!=null?`${u.remainingDays} روز`:u.subscriptionEnd?new Date(u.subscriptionEnd).toLocaleDateString('fa-IR'):'-'}</td><td className="p-3"><span className={u.isActive?'text-green-600':'text-red-600'}>{u.isActive?'فعال':'غیرفعال'}</span></td><td className="p-3"><button onClick={()=>void toggle(u)} disabled={busy===`active-${u.id}`} className="rounded-lg border px-3 py-1">{u.isActive?'غیرفعال‌سازی':'فعال‌سازی'}</button></td></tr>)}</tbody></table></div><div className="text-xs text-gray-500 mt-3">{filtered.length.toLocaleString('fa-IR')} کاربر نمایش داده می‌شود.</div>
  </div>
 </div>;
};
export default UserManagementRBAC;
