import React, { useEffect, useMemo, useState } from 'react';
import * as adminService from '../services/adminService';
import type { AdminUserListItem } from '../types';
import { useNotification } from './NotificationSystem';

interface UserManagementProps { isOnline: boolean; onMessageUpdate: () => void; onlineCount: number; }
type ManagedUser = AdminUserListItem & { firstName?: string|null; lastName?: string|null; roleId?: number|null; roleName?: string|null; roleTitle?: string|null; subscriptionType?: string|null; analysisLimit24h?: number; analysisUsed24h?: number; lastLoginAt?: string|null; loginCount?: number; };
type DetailUser = ManagedUser & { counts?: { analysis?: number; apiKeys?: number; notifications?: number; sessions?: number } };

const roleTitle=(name?:string|null,title?:string|null)=>title?.trim()||({SUPERADMIN:'مدیر ارشد',ADMIN:'مدیر سامانه',USER:'کاربر'} as Record<string,string>)[String(name||'').toUpperCase()]||name||'بدون نقش';
const displayName=(u:ManagedUser)=>[u.firstName,u.lastName].filter(Boolean).join(' ').trim()||u.name||u.username;
const fmt=(v:number|null|undefined)=>Number(v||0).toLocaleString('fa-IR');
const dateFmt=(v:string|null|undefined)=>{if(!v)return '—';const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleDateString('fa-IR');};
const dateInput=(v:string|null|undefined)=>{if(!v)return '';const d=new Date(v);return Number.isNaN(d.getTime())?'':d.toISOString().slice(0,10);};

const UserManagementRBAC:React.FC<UserManagementProps>=({isOnline,onlineCount})=>{
 const [users,setUsers]=useState<ManagedUser[]>([]);
 const [roles,setRoles]=useState<adminService.AdminRole[]>([]);
 const [loading,setLoading]=useState(true);
 const [busy,setBusy]=useState<string|null>(null);
 const [search,setSearch]=useState('');
 const [roleFilter,setRoleFilter]=useState('all');
 const [statusFilter,setStatusFilter]=useState('all');
 const [page,setPage]=useState(1);
 const [total,setTotal]=useState(0);
 const [totalPages,setTotalPages]=useState(0);
 const [detail,setDetail]=useState<DetailUser|null>(null);
 const [detailLoading,setDetailLoading]=useState(false);
 const [error,setError]=useState<string|null>(null);
 const {addNotification}=useNotification();
 const pageSize=20;
 const [form,setForm]=useState({username:'',password:'',firstName:'',lastName:'',email:'',mobile:'',roleId:'',subscriptionDays:'30',analysisLimit:'20',analysisLimit24h:'20'});
 const [editForm,setEditForm]=useState({username:'',firstName:'',lastName:'',email:'',mobile:'',isActive:true});
 const [subscriptionForm,setSubscriptionForm]=useState({isSubscriptionActive:false,subscriptionDays:'0',analysisLimit:'0',analysisLimit24h:'0',subscriptionStart:'',subscriptionEnd:''});
 const [newPassword,setNewPassword]=useState('');

 const load=async(targetPage=page)=>{setLoading(true);setError(null);try{const result=await adminService.getUsers({page:targetPage,limit:pageSize,search,roleId:roleFilter==='all'?undefined:Number(roleFilter),isActive:statusFilter==='all'?undefined:statusFilter==='active'});setUsers(result.users as ManagedUser[]);setTotal(result.pagination.total);setTotalPages(result.pagination.totalPages);setPage(result.pagination.page);}catch(e){setError(e instanceof Error?e.message:'خطا در دریافت اطلاعات کاربران.');}finally{setLoading(false);}};
 useEffect(()=>{void adminService.getRoles().then(setRoles).catch(e=>setError(e instanceof Error?e.message:'دریافت نقش‌ها ناموفق بود.'));},[]);
 useEffect(()=>{const t=window.setTimeout(()=>void load(1),300);return()=>window.clearTimeout(t);},[search,roleFilter,statusFilter]);
 useEffect(()=>{if(!form.roleId&&roles.length)setForm(f=>({...f,roleId:String(roles.find(r=>r.name.toUpperCase()==='USER')?.id||roles[0].id)}));},[roles,form.roleId]);
 const activeCount=useMemo(()=>users.filter(u=>u.isActive).length,[users]);
 const create=async(e:React.FormEvent)=>{e.preventDefault();if(!form.username.trim()||form.password.length<6){addNotification('نام کاربری و رمز عبور معتبر وارد کنید.','error');return;}setBusy('create');try{await adminService.createUser({username:form.username.trim(),password:form.password,email:form.email||null,firstName:form.firstName||null,lastName:form.lastName||null,mobile:form.mobile||null,roleId:Number(form.roleId)||null,isActive:true,subscriptionDays:Number(form.subscriptionDays)||0,isSubscriptionActive:true,analysisLimit:Number(form.analysisLimit)||0,analysisLimit24h:Number(form.analysisLimit24h)||0});addNotification('کاربر با موفقیت ایجاد شد.','success');setForm(f=>({...f,username:'',password:'',firstName:'',lastName:'',email:'',mobile:''}));await load(1);}catch(e){addNotification(e instanceof Error?e.message:'ایجاد کاربر ناموفق بود.','error');}finally{setBusy(null);}};
 const changeRole=async(u:ManagedUser,roleId:number)=>{if(roleId===Number(u.roleId))return;setBusy(`role-${u.id}`);try{await adminService.changeUserRole(u.id,roleId);addNotification('نقش کاربر تغییر کرد.','success');await load(page);if(detail?.id===u.id)setDetail(d=>d?{...d,roleId}:d);}catch(e){addNotification(e instanceof Error?e.message:'تغییر نقش ناموفق بود.','error');}finally{setBusy(null);}};
 const toggle=async(u:ManagedUser)=>{if(!window.confirm(u.isActive?'آیا از غیرفعال‌سازی این کاربر مطمئن هستید؟':'آیا از فعال‌سازی این کاربر مطمئن هستید؟'))return;setBusy(`active-${u.id}`);try{await adminService.toggleUserActive(u.id,!u.isActive);addNotification(u.isActive?'کاربر غیرفعال شد.':'کاربر فعال شد.','success');await load(page);if(detail?.id===u.id)setDetail(d=>d?{...d,isActive:!u.isActive}:d);}catch(e){addNotification(e instanceof Error?e.message:'تغییر وضعیت ناموفق بود.','error');}finally{setBusy(null);}};
 const openDetail=async(u:ManagedUser)=>{setDetailLoading(true);setError(null);setNewPassword('');try{const d=await adminService.getUser(u.id);if(!d)throw new Error('اطلاعات کاربر یافت نشد.');const next=d as DetailUser;setDetail(next);setEditForm({username:next.username||'',firstName:next.firstName||'',lastName:next.lastName||'',email:next.email||'',mobile:next.mobile||next.phone||'',isActive:!!next.isActive});setSubscriptionForm({isSubscriptionActive:!!next.isSubscriptionActive,subscriptionDays:String(Math.max(0,Number(next.remainingDays)||0)),analysisLimit:String(Number(next.analysisLimit)||0),analysisLimit24h:String(Number(next.analysisLimit24h)||0),subscriptionStart:dateInput(next.subscriptionStart),subscriptionEnd:dateInput(next.subscriptionEnd)});}catch(e){setError(e instanceof Error?e.message:'دریافت جزئیات کاربر ناموفق بود.');}finally{setDetailLoading(false);}};
 const saveBasic=async()=>{if(!detail)return;setBusy('save-basic');try{const updated=await adminService.updateUser(detail.id,{username:editForm.username.trim(),firstName:editForm.firstName.trim()||null,lastName:editForm.lastName.trim()||null,email:editForm.email.trim()||null,mobile:editForm.mobile.trim()||null,isActive:editForm.isActive});if(updated)setDetail(d=>d?{...d,...updated,firstName:editForm.firstName,lastName:editForm.lastName,email:editForm.email,mobile:editForm.mobile,isActive:editForm.isActive}:d);addNotification('اطلاعات کاربر با موفقیت ذخیره شد.','success');await load(page);}catch(e){addNotification(e instanceof Error?e.message:'ذخیره اطلاعات کاربر ناموفق بود.','error');}finally{setBusy(null);}};
 const saveSubscription=async()=>{if(!detail)return;setBusy('save-subscription');try{const updated=await adminService.updateSubscription({userId:detail.id,isSubscriptionActive:subscriptionForm.isSubscriptionActive,subscriptionDays:Number(subscriptionForm.subscriptionDays)||0,analysisLimit:Number(subscriptionForm.analysisLimit)||0,analysisLimit24h:Number(subscriptionForm.analysisLimit24h)||0,subscriptionStart:subscriptionForm.subscriptionStart||null,subscriptionEnd:subscriptionForm.subscriptionEnd||null});if(updated)setDetail(d=>d?{...d,...updated}:d);addNotification('اشتراک و محدودیت‌های کاربر به‌روزرسانی شد.','success');await load(page);}catch(e){addNotification(e instanceof Error?e.message:'به‌روزرسانی اشتراک ناموفق بود.','error');}finally{setBusy(null);}};
 const resetPassword=async()=>{if(!detail)return;if(newPassword.length<6){addNotification('رمز عبور جدید باید حداقل ۶ کاراکتر باشد.','error');return;}if(!window.confirm('آیا از تغییر رمز عبور این کاربر مطمئن هستید؟'))return;setBusy('reset-password');try{const ok=await adminService.resetUserPassword(detail.id,newPassword);if(!ok)throw new Error('ریست رمز عبور انجام نشد.');setNewPassword('');addNotification('رمز عبور کاربر با موفقیت تغییر کرد.','success');}catch(e){addNotification(e instanceof Error?e.message:'ریست رمز عبور ناموفق بود.','error');}finally{setBusy(null);}};
 if(loading&&users.length===0)return <div className="py-10 text-center text-gray-500">در حال بارگذاری کاربران...</div>;
 return <div className="user-management-rbac-workstation max-w-7xl mx-auto space-y-5" dir="rtl">
  <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-2xl font-bold">مدیریت کاربران</h2><p className="text-sm text-gray-500 mt-1">جستجو، فیلتر، صفحه‌بندی، کنترل وضعیت و مشاهده جزئیات کاربران</p></div>{isOnline&&<span className="text-sm text-green-600">● {fmt(onlineCount)} کاربر آنلاین</span>}</div>
  {error&&<div className="rounded-xl border border-red-300 bg-red-50 p-3 text-red-700">{error}</div>}
  <div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><div className="rounded-2xl border border-[var(--card-border-color)] bg-[var(--card-bg)] p-4"><div className="text-xs text-gray-500">کل کاربران</div><b className="text-2xl">{fmt(total)}</b></div><div className="rounded-2xl border border-[var(--card-border-color)] bg-[var(--card-bg)] p-4"><div className="text-xs text-gray-500">فعال در صفحه</div><b className="text-2xl text-green-600">{fmt(activeCount)}</b></div><div className="rounded-2xl border border-[var(--card-border-color)] bg-[var(--card-bg)] p-4"><div className="text-xs text-gray-500">صفحه</div><b className="text-2xl">{fmt(page)} از {fmt(totalPages)}</b></div><div className="rounded-2xl border border-[var(--card-border-color)] bg-[var(--card-bg)] p-4"><div className="text-xs text-gray-500">نمایش در هر صفحه</div><b className="text-2xl">{fmt(pageSize)}</b></div></div>
  <form onSubmit={create} className="rounded-2xl border border-[var(--card-border-color)] bg-[var(--card-bg)] p-5 shadow-sm"><h3 className="font-bold mb-4">افزودن کاربر جدید</h3><fieldset disabled={!isOnline||busy==='create'} className="grid grid-cols-1 md:grid-cols-3 gap-3 disabled:opacity-60">{([['firstName','نام'],['lastName','نام خانوادگی'],['username','نام کاربری'],['password','کلمه عبور'],['email','ایمیل'],['mobile','موبایل']] as const).map(([key,label])=><input key={key} type={key==='password'?'password':key==='email'?'email':'text'} placeholder={label} value={form[key]} onChange={e=>setForm(f=>({...f,[key]:e.target.value}))} className="border rounded-xl px-3 py-2 bg-transparent" required={key==='username'||key==='password'} />)}<select value={form.roleId} onChange={e=>setForm(f=>({...f,roleId:e.target.value}))} className="border rounded-xl px-3 py-2 bg-transparent">{roles.map(r=><option key={r.id} value={r.id}>{roleTitle(r.name,r.title)}</option>)}</select><input type="number" min="0" placeholder="مدت اشتراک (روز)" value={form.subscriptionDays} onChange={e=>setForm(f=>({...f,subscriptionDays:e.target.value}))} className="border rounded-xl px-3 py-2 bg-transparent"/><input type="number" min="0" placeholder="سقف تحلیل" value={form.analysisLimit} onChange={e=>setForm(f=>({...f,analysisLimit:e.target.value}))} className="border rounded-xl px-3 py-2 bg-transparent"/><input type="number" min="0" placeholder="سقف تحلیل ۲۴ ساعت" value={form.analysisLimit24h} onChange={e=>setForm(f=>({...f,analysisLimit24h:e.target.value}))} className="border rounded-xl px-3 py-2 bg-transparent"/><button className="md:col-span-3 rounded-xl px-5 py-2 font-bold bg-cyan-600 text-white disabled:opacity-50" disabled={!isOnline||busy==='create'}>{busy==='create'?'در حال ایجاد...':'ایجاد کاربر'}</button></fieldset></form>
  <div className="rounded-2xl border border-[var(--card-border-color)] bg-[var(--card-bg)] p-5"><div className="grid grid-cols-1 md:grid-cols-3 gap-3 mb-4"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="جستجوی نام، نام کاربری، ایمیل، موبایل یا شناسه ملی" className="border rounded-xl px-3 py-2 bg-transparent"/><select value={roleFilter} onChange={e=>setRoleFilter(e.target.value)} className="border rounded-xl px-3 py-2 bg-transparent"><option value="all">همه نقش‌ها</option>{roles.map(r=><option key={r.id} value={r.id}>{roleTitle(r.name,r.title)}</option>)}</select><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)} className="border rounded-xl px-3 py-2 bg-transparent"><option value="all">همه وضعیت‌ها</option><option value="active">فعال</option><option value="inactive">غیرفعال</option></select></div>
   <div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b"><th className="p-3 text-right">کاربر</th><th className="p-3 text-right">نقش</th><th className="p-3 text-right">اشتراک</th><th className="p-3 text-right">آخرین ورود</th><th className="p-3 text-right">وضعیت</th><th className="p-3 text-right">عملیات</th></tr></thead><tbody>{users.map(u=><tr key={u.id} className="border-b last:border-0 hover:bg-gray-50/60 dark:hover:bg-gray-800/30"><td className="p-3"><button className="text-right" onClick={()=>void openDetail(u)}><div className="font-semibold hover:text-cyan-600">{displayName(u)}</div><div className="text-xs text-gray-500">@{u.username}{u.email?` · ${u.email}`:''}</div></button></td><td className="p-3"><select value={u.roleId??''} disabled={busy===`role-${u.id}`} onChange={e=>void changeRole(u,Number(e.target.value))} className="border rounded-lg px-2 py-1 bg-transparent">{roles.map(r=><option key={r.id} value={r.id}>{roleTitle(r.name,r.title)}</option>)}</select></td><td className="p-3"><div className={u.isSubscriptionActive?'text-green-600':'text-gray-500'}>{u.isSubscriptionActive?'فعال':'منقضی'}</div><div className="text-xs text-gray-500">{u.remainingDays>0?`${fmt(u.remainingDays)} روز باقی‌مانده`:dateFmt(u.subscriptionEnd)}</div></td><td className="p-3 text-gray-600">{dateFmt(u.lastLoginAt)}</td><td className="p-3"><span className={u.isActive?'text-green-600':'text-red-600'}>{u.isActive?'فعال':'غیرفعال'}</span></td><td className="p-3"><div className="flex flex-wrap gap-2"><button onClick={()=>void openDetail(u)} className="rounded-lg border px-3 py-1">جزئیات</button><button onClick={()=>void toggle(u)} disabled={busy===`active-${u.id}`} className="rounded-lg border px-3 py-1">{u.isActive?'غیرفعال‌سازی':'فعال‌سازی'}</button></div></td></tr>)}{!users.length&&<tr><td colSpan={6} className="p-8 text-center text-gray-500">کاربری با این فیلترها پیدا نشد.</td></tr>}</tbody></table></div>
   <div className="mt-4 flex flex-wrap items-center justify-between gap-3"><span className="text-xs text-gray-500">{fmt(total)} کاربر در نتایج</span><div className="flex items-center gap-2"><button disabled={page<=1||loading} onClick={()=>void load(page-1)} className="rounded-lg border px-3 py-2 disabled:opacity-40">قبلی</button><span className="text-sm">صفحه {fmt(page)} از {fmt(totalPages)}</span><button disabled={page>=totalPages||loading} onClick={()=>void load(page+1)} className="rounded-lg border px-3 py-2 disabled:opacity-40">بعدی</button></div></div>
  </div>
  {(detail||detailLoading)&&<div className="fixed inset-0 z-50 bg-black/40 p-4 flex items-center justify-center" onMouseDown={e=>{if(e.target===e.currentTarget)setDetail(null)}}><div className="w-full max-w-4xl max-h-[90vh] overflow-y-auto rounded-2xl border border-[var(--card-border-color)] bg-[var(--card-bg)] shadow-xl p-5" dir="rtl">{detailLoading?<div className="py-10 text-center">در حال دریافت جزئیات...</div>:detail&&<><div className="flex items-start justify-between gap-3"><div><h3 className="text-xl font-bold">{displayName(detail)}</h3><p className="text-sm text-gray-500">@{detail.username}</p></div><button onClick={()=>setDetail(null)} className="rounded-lg border px-3 py-1">بستن</button></div>
   <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mt-5">{[['تحلیل‌ها',detail.counts?.analysis],['کلیدهای API',detail.counts?.apiKeys],['اعلان‌ها',detail.counts?.notifications],['نشست‌ها',detail.counts?.sessions]].map(([label,value])=><div key={String(label)} className="rounded-xl border p-3"><div className="text-xs text-gray-500">{label}</div><b className="text-xl">{fmt(value as number)}</b></div>)}</div>
   <div className="grid grid-cols-1 lg:grid-cols-2 gap-4 mt-5">
    <div className="rounded-xl border p-4"><div className="flex items-center justify-between mb-3"><b>اطلاعات حساب</b><span className={detail.isActive?'text-green-600':'text-red-600'}>{detail.isActive?'فعال':'غیرفعال'}</span></div><div className="grid grid-cols-1 md:grid-cols-2 gap-3"><input value={editForm.firstName} onChange={e=>setEditForm(f=>({...f,firstName:e.target.value}))} placeholder="نام" className="border rounded-xl px-3 py-2 bg-transparent"/><input value={editForm.lastName} onChange={e=>setEditForm(f=>({...f,lastName:e.target.value}))} placeholder="نام خانوادگی" className="border rounded-xl px-3 py-2 bg-transparent"/><input value={editForm.username} onChange={e=>setEditForm(f=>({...f,username:e.target.value}))} placeholder="نام کاربری" className="border rounded-xl px-3 py-2 bg-transparent"/><input value={editForm.email} onChange={e=>setEditForm(f=>({...f,email:e.target.value}))} type="email" placeholder="ایمیل" className="border rounded-xl px-3 py-2 bg-transparent"/><input value={editForm.mobile} onChange={e=>setEditForm(f=>({...f,mobile:e.target.value}))} placeholder="موبایل" className="border rounded-xl px-3 py-2 bg-transparent"/><label className="flex items-center gap-2 border rounded-xl px-3 py-2"><input type="checkbox" checked={editForm.isActive} onChange={e=>setEditForm(f=>({...f,isActive:e.target.checked}))}/><span>حساب فعال باشد</span></label></div><div className="mt-3 flex justify-end"><button onClick={()=>void saveBasic()} disabled={busy==='save-basic'} className="rounded-xl bg-cyan-600 text-white px-4 py-2 font-bold disabled:opacity-50">{busy==='save-basic'?'در حال ذخیره...':'ذخیره اطلاعات'}</button></div></div>
    <div className="rounded-xl border p-4"><b>اشتراک و مصرف</b><div className="grid grid-cols-1 md:grid-cols-2 gap-3 mt-3"><label className="flex items-center gap-2 border rounded-xl px-3 py-2"><input type="checkbox" checked={subscriptionForm.isSubscriptionActive} onChange={e=>setSubscriptionForm(f=>({...f,isSubscriptionActive:e.target.checked}))}/><span>اشتراک فعال باشد</span></label><input type="number" min="0" value={subscriptionForm.subscriptionDays} onChange={e=>setSubscriptionForm(f=>({...f,subscriptionDays:e.target.value}))} placeholder="روز اشتراک" className="border rounded-xl px-3 py-2 bg-transparent"/><input type="number" min="0" value={subscriptionForm.analysisLimit} onChange={e=>setSubscriptionForm(f=>({...f,analysisLimit:e.target.value}))} placeholder="سقف تحلیل" className="border rounded-xl px-3 py-2 bg-transparent"/><input type="number" min="0" value={subscriptionForm.analysisLimit24h} onChange={e=>setSubscriptionForm(f=>({...f,analysisLimit24h:e.target.value}))} placeholder="سقف تحلیل ۲۴ ساعت" className="border rounded-xl px-3 py-2 bg-transparent"/><label className="text-xs text-gray-500">شروع اشتراک<input type="date" value={subscriptionForm.subscriptionStart} onChange={e=>setSubscriptionForm(f=>({...f,subscriptionStart:e.target.value}))} className="mt-1 w-full border rounded-xl px-3 py-2 bg-transparent text-sm"/></label><label className="text-xs text-gray-500">پایان اشتراک<input type="date" value={subscriptionForm.subscriptionEnd} onChange={e=>setSubscriptionForm(f=>({...f,subscriptionEnd:e.target.value}))} className="mt-1 w-full border rounded-xl px-3 py-2 bg-transparent text-sm"/></label></div><div className="mt-3 flex justify-between items-center gap-3 text-xs text-gray-500"><span>مصرف ۲۴ ساعته: {fmt(detail.analysisUsed24h)} از {fmt(detail.analysisLimit24h)}</span><button onClick={()=>void saveSubscription()} disabled={busy==='save-subscription'} className="rounded-xl bg-cyan-600 text-white px-4 py-2 font-bold text-sm disabled:opacity-50">{busy==='save-subscription'?'در حال ذخیره...':'ذخیره اشتراک'}</button></div></div>
    <div className="rounded-xl border p-4 lg:col-span-2"><b>امنیت حساب</b><div className="mt-3 flex flex-col md:flex-row gap-3"><input type="password" minLength={6} value={newPassword} onChange={e=>setNewPassword(e.target.value)} placeholder="رمز عبور جدید — حداقل ۶ کاراکتر" className="flex-1 border rounded-xl px-3 py-2 bg-transparent"/><button onClick={()=>void resetPassword()} disabled={busy==='reset-password'||newPassword.length<6} className="rounded-xl border px-4 py-2 font-bold disabled:opacity-50">{busy==='reset-password'?'در حال تغییر...':'تغییر رمز عبور'}</button></div></div>
   </div>
   <div className="grid grid-cols-1 md:grid-cols-2 gap-3 mt-4 text-sm"><div className="rounded-xl border p-4"><b>اطلاعات تکمیلی</b><div className="mt-3 space-y-2"><div>نقش: {roleTitle(detail.roleName,detail.roleTitle)}</div><div>ثبت‌نام: {dateFmt(detail.createdAt)}</div><div>آخرین ورود: {dateFmt(detail.lastLoginAt)}</div><div>تعداد ورود: {fmt(detail.loginCount)}</div></div></div><div className="rounded-xl border p-4"><b>خلاصه اشتراک</b><div className="mt-3 space-y-2"><div>نوع اشتراک: {detail.subscriptionType||'—'}</div><div>روز باقی‌مانده: {fmt(detail.remainingDays)}</div><div>پایان اشتراک: {dateFmt(detail.subscriptionEnd)}</div><div>سقف تحلیل: {fmt(detail.analysisLimit)}</div></div></div></div>
  </>}</div></div>}
 </div>;
};
export default UserManagementRBAC;
