import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { getDashboardData } from '../../services/dashboardService';
import { createSubscriptionPayment, getMySubscription } from '../../services/subscriptionService';
import type { SubscriptionState } from '../../services/subscriptionService';
import type { DashboardData, DashboardMover } from '../../types/dashboard';

interface DashboardProps { isOnline?: boolean; onNavigate?: (target: string) => void; unreadAlertCount?: number; subscriptionDaysRemaining?: number | null; subscriptionExpired?: boolean; }
const nf = new Intl.NumberFormat('fa-IR', { maximumFractionDigits: 2 });
const formatNumber = (v: number | null | undefined) => v == null || !Number.isFinite(v) ? '—' : nf.format(v);
const formatPercent = (v: number) => { const t = new Intl.NumberFormat('fa-IR', { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(Math.abs(v)); return v > 0 ? `+${t}٪` : v < 0 ? `−${t}٪` : '۰٫۰۰٪'; };
const formatDate = (v?: string | null) => { if (!v) return '—'; const d = new Date(v); return Number.isNaN(d.getTime()) ? '—' : new Intl.DateTimeFormat('fa-IR', { dateStyle: 'medium' }).format(d); };
const Card: React.FC<{ children: React.ReactNode; className?: string }> = ({ children, className = '' }) => <section className={`dashboard-card rounded-2xl border border-[var(--color-border)] bg-[var(--color-surface)] p-4 shadow-sm ${className}`}>{children}</section>;

const MoverList: React.FC<{ title: string; items: DashboardMover[]; showVolume?: boolean }> = ({ title, items, showVolume = false }) => <Card><div className="mb-4 flex items-center justify-between"><h3 className="font-bold text-[var(--color-text-primary)]">{title}</h3><span className="text-xs text-slate-500">۱۰ نماد</span></div>{items.length === 0 ? <div className="rounded-xl bg-black/5 px-3 py-6 text-center text-sm text-slate-500 dark:bg-white/5">داده‌ای در دسترس نیست</div> : <div className="space-y-2">{items.map((item, i) => <div key={`${item.symbol}-${i}`} className="flex items-center justify-between rounded-xl px-3 py-2 hover:bg-black/5 dark:hover:bg-white/5"><div className="min-w-0"><div className="text-sm font-bold text-[var(--color-text-primary)]">{item.symbol}</div>{item.name && <div className="truncate text-xs text-slate-500">{item.name}</div>}</div><div className="text-left"><div className="text-sm font-bold tabular-nums text-[var(--color-text-primary)]">{formatNumber(item.price)}</div><div className="text-xs font-bold tabular-nums">{showVolume ? `حجم ${formatNumber(item.volume)}` : <span className={item.changePercent >= 0 ? 'text-[var(--color-positive)]' : 'text-[var(--color-negative)]'}>{formatPercent(item.changePercent)}</span>}</div></div></div>)}</div>}</Card>;

const SummaryCard: React.FC<{ title: string; value: string; detail?: string; onClick?: () => void }> = ({ title, value, detail, onClick }) => <button type="button" onClick={onClick} className="dashboard-summary-card rounded-2xl border border-[var(--color-border)] bg-[var(--color-surface)] p-5 text-right shadow-sm transition hover:-translate-y-0.5"><div className="text-sm font-bold text-slate-500">{title}</div><div className="mt-3 text-2xl font-black tabular-nums text-[var(--color-text-primary)]">{value}</div>{detail && <div className="mt-1 text-xs text-slate-500">{detail}</div>}</button>;

const SubscriptionCard: React.FC<{ state: SubscriptionState | null; fallbackDays: number | null; fallbackExpired: boolean; onRenew: () => Promise<void>; renewing: boolean; onNavigate?: (target: string) => void }> = ({ state, fallbackDays, fallbackExpired, onRenew, renewing, onNavigate }) => { const sub = state?.subscription ?? null; const expired = state ? !state.hasAccess || !state.isActive : fallbackExpired; const days = state ? state.daysRemaining : fallbackDays; const name = sub?.plan?.name || (state?.hasAccess ? 'اشتراک فعال' : 'بدون اشتراک فعال'); return <Card><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="text-sm font-bold text-slate-500">وضعیت اشتراک</div><div className="mt-2 text-xl font-black text-[var(--color-text-primary)]">{name}</div><div className={`mt-1 text-sm font-bold ${expired ? 'text-[var(--color-negative)]' : 'text-[var(--color-positive)]'}`}>{expired ? 'پایان‌یافته' : days == null ? 'فعال' : `${formatNumber(days)} روز باقی‌مانده`}</div>{sub?.expiresAt && <div className="mt-1 text-xs text-slate-500">تاریخ پایان: {formatDate(sub.expiresAt)}</div>}</div><div className="flex flex-wrap gap-2"><button type="button" onClick={() => onNavigate?.('profile')} className="rounded-xl border border-[var(--color-border)] px-4 py-2 text-sm font-bold text-[var(--color-text-primary)]">جزئیات اشتراک</button><button type="button" disabled={renewing} onClick={() => void onRenew()} className="rounded-xl bg-cyan-600 px-4 py-2 text-sm font-black text-white disabled:opacity-50">{renewing ? 'در حال انتقال…' : 'تمدید اشتراک'}</button></div></div></Card>; };

const Dashboard: React.FC<DashboardProps> = ({ isOnline = true, onNavigate, unreadAlertCount = 0, subscriptionDaysRemaining = null, subscriptionExpired = false }) => {
  const [data, setData] = useState<DashboardData | null>(null); const [subscription, setSubscription] = useState<SubscriptionState | null>(null); const [loading, setLoading] = useState(true); const [renewing, setRenewing] = useState(false); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { if (!isOnline) { setError('اتصال به سرور در دسترس نیست.'); setLoading(false); return; } setError(null); setLoading(true); try { const [d, s] = await Promise.allSettled([getDashboardData(unreadAlertCount, subscriptionDaysRemaining, subscriptionExpired), getMySubscription()]); if (d.status === 'fulfilled') setData(d.value); else throw d.reason; if (s.status === 'fulfilled') setSubscription(s.value); } catch (e) { console.error('[Dashboard]', e); setError('دریافت اطلاعات داشبورد انجام نشد.'); } finally { setLoading(false); } }, [isOnline, unreadAlertCount, subscriptionDaysRemaining, subscriptionExpired]);
  useEffect(() => { void load(); }, [load]);
  const handleRenew = useCallback(async () => { const planId = subscription?.subscription?.planId; if (!planId) { onNavigate?.('profile'); return; } setRenewing(true); try { const payment = await createSubscriptionPayment(planId); window.location.assign(payment.redirectUrl); } catch (e) { console.error('[Dashboard] renewal', e); setError('ایجاد درخواست تمدید اشتراک انجام نشد.'); } finally { setRenewing(false); } }, [onNavigate, subscription]);
  const marketStatus = useMemo(() => data?.market?.indices[0]?.isMarketOpen ? 'بازار باز است' : 'بازار بسته است', [data]); const personal = data?.personal;
  if (loading && !data) return <div dir="rtl" className="space-y-4 animate-pulse"><div className="h-32 rounded-2xl bg-slate-200/40 dark:bg-white/5"/><div className="grid gap-4 md:grid-cols-3"><div className="h-28 rounded-2xl bg-slate-200/40 dark:bg-white/5"/><div className="h-28 rounded-2xl bg-slate-200/40 dark:bg-white/5"/><div className="h-28 rounded-2xl bg-slate-200/40 dark:bg-white/5"/></div></div>;
  return <div dir="rtl" className="page-shell trader-dashboard-page dashboard-workstation space-y-5">
    <header className="dashboard-inline-header flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-2xl font-black text-[var(--color-text-primary)]">داشبورد بازار</h1><p className="mt-1 text-sm text-slate-500">نمای کلی بازار، دارایی‌های شخصی، هشدارها و رویدادهای کدال</p></div><div className="flex items-center gap-2"><span className="rounded-full bg-black/5 px-3 py-1 text-xs font-bold text-slate-500 dark:bg-white/5">{marketStatus}</span><button type="button" onClick={() => void load()} className="rounded-xl border border-[var(--color-border)] px-3 py-2 text-sm font-bold text-[var(--color-text-primary)]">به‌روزرسانی</button></div></header>
    {error && <div className="rounded-xl border border-red-500/20 bg-red-500/10 px-4 py-3 text-sm text-red-500">{error}</div>}
    <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{(data?.market?.indices ?? []).map(index => <div key={index.name} className="rounded-2xl border border-[var(--color-border)] bg-[var(--color-surface)] p-5 shadow-sm"><div className="text-sm font-bold text-slate-500">{index.name}</div><div className="mt-3 text-2xl font-black tabular-nums text-[var(--color-text-primary)]">{formatNumber(index.value)}</div><div className={`mt-2 text-sm font-bold ${index.changeValue >= 0 ? 'text-[var(--color-positive)]' : 'text-[var(--color-negative)]'}`}>{formatNumber(index.changeValue)} ({formatPercent(index.changePercent)})</div></div>)}<div className="rounded-2xl border border-[var(--color-border)] bg-[var(--color-surface)] p-5"><div className="text-sm font-bold text-slate-500">ارزش معاملات</div><div className="mt-3 text-2xl font-black text-[var(--color-text-primary)]">{formatNumber(data?.market?.totalValue)}</div></div><div className="rounded-2xl border border-[var(--color-border)] bg-[var(--color-surface)] p-5"><div className="text-sm font-bold text-slate-500">حجم معاملات</div><div className="mt-3 text-2xl font-black text-[var(--color-text-primary)]">{formatNumber(data?.market?.totalVolume)}</div></div><div className="rounded-2xl border border-[var(--color-border)] bg-[var(--color-surface)] p-5"><div className="text-sm font-bold text-slate-500">تعداد معاملات</div><div className="mt-3 text-2xl font-black text-[var(--color-text-primary)]">{formatNumber(data?.market?.totalTrades)}</div></div></section>
    <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3"><SummaryCard title="دیده‌بان‌ها" value={formatNumber(personal?.watchlistCount ?? 0)} detail={`${formatNumber(personal?.watchlistSymbolCount ?? 0)} نماد در دیده‌بان`} onClick={() => onNavigate?.('portfolio')}/><SummaryCard title="سبد سهام" value={formatNumber(personal?.portfolioCount ?? 0)} detail={`سرمایه ثبت‌شده: ${formatNumber(personal?.portfolioInvestedValue ?? 0)} ریال`} onClick={() => onNavigate?.('portfolio')}/><SummaryCard title="هشدارهای خوانده‌نشده" value={formatNumber(personal?.unreadAlertCount ?? 0)} detail="مشاهده همه هشدارها" onClick={() => onNavigate?.('notifications')}/></section>
    <SubscriptionCard state={subscription} fallbackDays={subscriptionDaysRemaining} fallbackExpired={subscriptionExpired} onRenew={handleRenew} renewing={renewing} onNavigate={onNavigate}/>
    <div className="grid gap-5 lg:grid-cols-3"><MoverList title="بیشترین رشد" items={data?.gainers ?? []}/><MoverList title="بیشترین افت" items={data?.losers ?? []}/><MoverList title="بیشترین حجم" items={data?.highVolume ?? []} showVolume/></div>
    <section className="grid gap-5 lg:grid-cols-2">
      <Card><div className="mb-4 flex items-center justify-between"><div><h3 className="font-bold text-[var(--color-text-primary)]">هشدارها و اطلاعیه‌های فعال</h3><p className="mt-1 text-xs text-slate-500">موارد خوانده‌نشده کاربر</p></div><button type="button" onClick={() => onNavigate?.('notifications')} className="rounded-lg border border-[var(--color-border)] px-3 py-1.5 text-xs font-bold">نمایش همه</button></div>{(data?.alerts ?? []).length === 0 ? <div className="rounded-xl bg-black/5 px-3 py-6 text-center text-sm text-slate-500 dark:bg-white/5">هشدار خوانده‌نشده‌ای وجود ندارد.</div> : <div className="space-y-2">{data?.alerts.map(a => <button key={a.id} type="button" onClick={() => onNavigate?.('notifications')} className="w-full rounded-xl border border-[var(--color-border)] p-3 text-right hover:bg-black/5 dark:hover:bg-white/5"><div className="text-sm font-bold text-[var(--color-text-primary)]">{a.message}</div><div className="mt-1 text-xs text-slate-500">{formatDate(a.createdAt)}</div></button>)}</div>}</Card>
      <Card><div className="mb-4"><h3 className="font-bold text-[var(--color-text-primary)]">آخرین رویدادهای کدال</h3><p className="mt-1 text-xs text-slate-500">فقط داده واقعی منبع کدال نمایش داده می‌شود.</p></div>{(data?.codalEvents ?? []).length === 0 ? <div className="rounded-xl bg-black/5 px-3 py-6 text-center text-sm text-slate-500 dark:bg-white/5">منبع رویدادهای کدال هنوز به داشبورد متصل نیست.</div> : <div className="space-y-2">{data?.codalEvents.map(e => <div key={e.id} className="rounded-xl border border-[var(--color-border)] p-3">{e.url ? <a href={e.url} target="_blank" rel="noreferrer" className="text-sm font-bold text-cyan-600 hover:underline">{e.title}</a> : <div className="text-sm font-bold text-[var(--color-text-primary)]">{e.title}</div>}<div className="mt-1 flex gap-2 text-xs text-slate-500">{e.symbol && <span>{e.symbol}</span>}{e.publishedAt && <span>{formatDate(e.publishedAt)}</span>}</div></div>)}</div>}</Card>
    </section>
    <Card><div className="mb-4"><h3 className="font-bold text-[var(--color-text-primary)]">وضعیت صنایع و گروه‌ها</h3><p className="mt-1 text-xs text-slate-500">مرتب‌سازی بر اساس تغییرات روزانه.</p></div>{(data?.industries ?? []).length === 0 ? <div className="rounded-xl bg-black/5 px-3 py-6 text-center text-sm text-slate-500 dark:bg-white/5">اطلاعات صنایع در سرویس بازار در دسترس نیست.</div> : <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{data?.industries.map(i => <div key={i.name} className="flex items-center justify-between rounded-xl border border-[var(--color-border)] px-3 py-3"><div><div className="text-sm font-bold text-[var(--color-text-primary)]">{i.name}</div>{i.symbolCount != null && <div className="text-xs text-slate-500">{formatNumber(i.symbolCount)} نماد</div>}</div><div className={`font-black tabular-nums ${i.changePercent >= 0 ? 'text-[var(--color-positive)]' : 'text-[var(--color-negative)]'}`}>{formatPercent(i.changePercent)}</div></div>)}</div>}</Card>
    <Card><div className="mb-4"><h3 className="font-bold text-[var(--color-text-primary)]">دسترسی سریع</h3><p className="mt-1 text-xs text-slate-500">ابزارهای اصلی بدون وابستگی به هوش مصنوعی</p></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><button type="button" onClick={() => onNavigate?.('analysis')} className="rounded-xl border border-cyan-500/20 bg-cyan-500/10 p-4 text-right"><div className="font-black">تحلیل نماد</div><div className="mt-1 text-xs text-slate-500">بررسی یک سهم</div></button><button type="button" onClick={() => onNavigate?.('dailyFilters')} className="rounded-xl border border-[var(--color-border)] p-4 text-right"><div className="font-black">فیلتر و Screener</div><div className="mt-1 text-xs text-slate-500">پیدا کردن نمادها</div></button><button type="button" onClick={() => onNavigate?.('portfolio')} className="rounded-xl border border-[var(--color-border)] p-4 text-right"><div className="font-black">سبد سهام</div><div className="mt-1 text-xs text-slate-500">مدیریت دارایی</div></button><button type="button" onClick={() => onNavigate?.('comparison')} className="rounded-xl border border-[var(--color-border)] p-4 text-right"><div className="font-black">مقایسه نمادها</div><div className="mt-1 text-xs text-slate-500">مقایسه چند سهم</div></button></div></Card>
    <div className="text-center text-xs text-slate-500">آخرین بروزرسانی: {formatDate(data?.fetchedAt)}</div>
  </div>;
};
export default Dashboard;
